---
driver:
  name: dokken
  chef_version: 17.6.18
  privileged: true
verifier:
  name: inspec
transport:
  name: dokken
provisioner:
  name: dokken
platforms:
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]
suites:
  - name: default
    run_list:
      - recipe[cdo-mysql::server]
  - name: stop
    run_list:
      - recipe[cdo-mysql::server]
      - recipe[test-mysql::stop]
  - name: readwrite
    run_list:
      - recipe[test-mysql::readwrite]
      - recipe[cdo-mysql::proxy]
    attributes:
      cdo-secrets:
        db_writer: mysql://root:test-password@127.0.0.1:3300
        db_reader: mysql://root:test-password@127.0.0.1:3301
