---
driver:
  name: dokken
  chef_version: 15.2.20
transport:
  name: dokken
provisioner:
  name: dokken
verifier:
  name:  inspec
platforms:
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]
suites:
  - name: default
    run_list:
      - recipe[cdo-analytics]
