name: Install test packages and environment
jobs:
description: 'Install the packages needed to run rake tests for unit test and UI tests'
runs:
  using: "composite"
  steps:
    - name: Get actions code
      uses: actions/checkout@v3
    - name: Verify actions
      uses: ./.github/actions/start-server-job-actions
    - name: Install mysql
      uses: ./.github/actions/install-mysql
    - name: Install test variables
      uses: ./.github/actions/install-test-variables
    - name: Install Ruby
      uses: ./.github/actions/install-ruby
    - name: Install apt packages
      uses: ./.github/actions/install-apt-packages
    - name: Install node
      uses: ./.github/actions/install-node
    - name: Install rake
      uses: ./.github/actions/install-rake-dependencies
