apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/cred-type: generic
  data:
    - secretKey: secret
      remoteRef:
        key: {{ .Values.externalSecret.awsSecretName | quote }}
