apiVersion: v2
name: external-dns-codeai-k8s
description: Local chart for ExternalDNS values on codeai-k8s
type: application
version: 0.1.0

dependencies:
  - name: external-dns
    repository: https://kubernetes-sigs.github.io/external-dns/
    version: 1.20.0
