=begin
#Clever API

#The Clever API

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Clever
  class AssignmentState
    DRAFT = "draft".freeze
    SCHEDULED = "scheduled".freeze
    OPEN = "open".freeze
    LOCKED = "locked".freeze

    def self.all_vars
      @all_vars ||= [DRAFT, SCHEDULED, OPEN, LOCKED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AssignmentState.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AssignmentState"
    end
  end
end
