=begin
#Clever API

#The Clever API

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Clever
  class GradingType
    POINTS = "points".freeze
    PERCENT = "percent".freeze
    PASS_FAIL = "pass_fail".freeze
    LETTER_GRADE = "letter_grade".freeze

    def self.all_vars
      @all_vars ||= [POINTS, PERCENT, PASS_FAIL, LETTER_GRADE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if GradingType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #GradingType"
    end
  end
end
