=begin
#Clever API

#The Clever API

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Clever
  class School < ApiModelBase
    attr_accessor :created

    attr_accessor :district

    attr_accessor :ext

    attr_accessor :high_grade

    attr_accessor :id

    attr_accessor :last_modified

    attr_accessor :location

    attr_accessor :low_grade

    attr_accessor :mdr_number

    attr_accessor :name

    attr_accessor :nces_id

    attr_accessor :phone

    attr_accessor :principal

    attr_accessor :school_number

    attr_accessor :sis_id

    attr_accessor :state_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'created' => :'created',
        :'district' => :'district',
        :'ext' => :'ext',
        :'high_grade' => :'high_grade',
        :'id' => :'id',
        :'last_modified' => :'last_modified',
        :'location' => :'location',
        :'low_grade' => :'low_grade',
        :'mdr_number' => :'mdr_number',
        :'name' => :'name',
        :'nces_id' => :'nces_id',
        :'phone' => :'phone',
        :'principal' => :'principal',
        :'school_number' => :'school_number',
        :'sis_id' => :'sis_id',
        :'state_id' => :'state_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'created' => :'String',
        :'district' => :'String',
        :'ext' => :'Object',
        :'high_grade' => :'String',
        :'id' => :'String',
        :'last_modified' => :'String',
        :'location' => :'Location',
        :'low_grade' => :'String',
        :'mdr_number' => :'String',
        :'name' => :'String',
        :'nces_id' => :'String',
        :'phone' => :'String',
        :'principal' => :'Principal',
        :'school_number' => :'String',
        :'sis_id' => :'String',
        :'state_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'high_grade',
        :'low_grade',
        :'mdr_number',
        :'nces_id',
        :'phone',
        :'state_id'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Clever::School` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Clever::School`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'created')
        self.created = attributes[:'created']
      end

      if attributes.key?(:'district')
        self.district = attributes[:'district']
      end

      if attributes.key?(:'ext')
        self.ext = attributes[:'ext']
      end

      if attributes.key?(:'high_grade')
        self.high_grade = attributes[:'high_grade']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'last_modified')
        self.last_modified = attributes[:'last_modified']
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.key?(:'low_grade')
        self.low_grade = attributes[:'low_grade']
      end

      if attributes.key?(:'mdr_number')
        self.mdr_number = attributes[:'mdr_number']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'nces_id')
        self.nces_id = attributes[:'nces_id']
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      end

      if attributes.key?(:'principal')
        self.principal = attributes[:'principal']
      end

      if attributes.key?(:'school_number')
        self.school_number = attributes[:'school_number']
      end

      if attributes.key?(:'sis_id')
        self.sis_id = attributes[:'sis_id']
      end

      if attributes.key?(:'state_id')
        self.state_id = attributes[:'state_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      high_grade_validator = EnumAttributeValidator.new('String', ["InfantToddler", "Preschool", "PreKindergarten", "TransitionalKindergarten", "Kindergarten", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "PostGraduate", "Ungraded", "Other", ""])
      return false unless high_grade_validator.valid?(@high_grade)
      low_grade_validator = EnumAttributeValidator.new('String', ["InfantToddler", "Preschool", "PreKindergarten", "TransitionalKindergarten", "Kindergarten", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "PostGraduate", "Ungraded", "Other", ""])
      return false unless low_grade_validator.valid?(@low_grade)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] high_grade Object to be assigned
    def high_grade=(high_grade)
      validator = EnumAttributeValidator.new('String', ["InfantToddler", "Preschool", "PreKindergarten", "TransitionalKindergarten", "Kindergarten", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "PostGraduate", "Ungraded", "Other", ""])
      unless validator.valid?(high_grade)
        fail ArgumentError, "invalid value for \"high_grade\", must be one of #{validator.allowable_values}."
      end
      @high_grade = high_grade
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] low_grade Object to be assigned
    def low_grade=(low_grade)
      validator = EnumAttributeValidator.new('String', ["InfantToddler", "Preschool", "PreKindergarten", "TransitionalKindergarten", "Kindergarten", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "PostGraduate", "Ungraded", "Other", ""])
      unless validator.valid?(low_grade)
        fail ArgumentError, "invalid value for \"low_grade\", must be one of #{validator.allowable_values}."
      end
      @low_grade = low_grade
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          created == o.created &&
          district == o.district &&
          ext == o.ext &&
          high_grade == o.high_grade &&
          id == o.id &&
          last_modified == o.last_modified &&
          location == o.location &&
          low_grade == o.low_grade &&
          mdr_number == o.mdr_number &&
          name == o.name &&
          nces_id == o.nces_id &&
          phone == o.phone &&
          principal == o.principal &&
          school_number == o.school_number &&
          sis_id == o.sis_id &&
          state_id == o.state_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [created, district, ext, high_grade, id, last_modified, location, low_grade, mdr_number, name, nces_id, phone, principal, school_number, sis_id, state_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
