=begin
#Clever API

#The Clever API

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Clever
  class Student < ApiModelBase
    attr_accessor :created

    attr_accessor :credentials

    attr_accessor :disability

    attr_accessor :dob

    attr_accessor :ell_status

    attr_accessor :enrollments

    attr_accessor :ext

    attr_accessor :frl_status

    attr_accessor :gender

    attr_accessor :gifted_status

    attr_accessor :grade

    attr_accessor :graduation_year

    attr_accessor :hispanic_ethnicity

    attr_accessor :home_language

    attr_accessor :home_language_code

    attr_accessor :iep_status

    attr_accessor :last_modified

    attr_accessor :legacy_id

    attr_accessor :location

    attr_accessor :preferred_name

    attr_accessor :race

    attr_accessor :school

    attr_accessor :schools

    attr_accessor :section_504_status

    attr_accessor :sis_id

    attr_accessor :state_id

    attr_accessor :student_number

    attr_accessor :unweighted_gpa

    attr_accessor :weighted_gpa

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'created' => :'created',
        :'credentials' => :'credentials',
        :'disability' => :'disability',
        :'dob' => :'dob',
        :'ell_status' => :'ell_status',
        :'enrollments' => :'enrollments',
        :'ext' => :'ext',
        :'frl_status' => :'frl_status',
        :'gender' => :'gender',
        :'gifted_status' => :'gifted_status',
        :'grade' => :'grade',
        :'graduation_year' => :'graduation_year',
        :'hispanic_ethnicity' => :'hispanic_ethnicity',
        :'home_language' => :'home_language',
        :'home_language_code' => :'home_language_code',
        :'iep_status' => :'iep_status',
        :'last_modified' => :'last_modified',
        :'legacy_id' => :'legacy_id',
        :'location' => :'location',
        :'preferred_name' => :'preferred_name',
        :'race' => :'race',
        :'school' => :'school',
        :'schools' => :'schools',
        :'section_504_status' => :'section_504_status',
        :'sis_id' => :'sis_id',
        :'state_id' => :'state_id',
        :'student_number' => :'student_number',
        :'unweighted_gpa' => :'unweighted_gpa',
        :'weighted_gpa' => :'weighted_gpa'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'created' => :'String',
        :'credentials' => :'Credentials',
        :'disability' => :'Disability',
        :'dob' => :'String',
        :'ell_status' => :'String',
        :'enrollments' => :'Array<SchoolEnrollment>',
        :'ext' => :'Object',
        :'frl_status' => :'String',
        :'gender' => :'String',
        :'gifted_status' => :'String',
        :'grade' => :'String',
        :'graduation_year' => :'String',
        :'hispanic_ethnicity' => :'String',
        :'home_language' => :'String',
        :'home_language_code' => :'String',
        :'iep_status' => :'String',
        :'last_modified' => :'String',
        :'legacy_id' => :'String',
        :'location' => :'Location',
        :'preferred_name' => :'PreferredName',
        :'race' => :'String',
        :'school' => :'String',
        :'schools' => :'Array<String>',
        :'section_504_status' => :'String',
        :'sis_id' => :'String',
        :'state_id' => :'String',
        :'student_number' => :'String',
        :'unweighted_gpa' => :'String',
        :'weighted_gpa' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'dob',
        :'ell_status',
        :'frl_status',
        :'gender',
        :'gifted_status',
        :'grade',
        :'graduation_year',
        :'hispanic_ethnicity',
        :'home_language',
        :'home_language_code',
        :'iep_status',
        :'race',
        :'section_504_status',
        :'state_id',
        :'student_number',
        :'unweighted_gpa',
        :'weighted_gpa'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Clever::Student` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Clever::Student`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'created')
        self.created = attributes[:'created']
      end

      if attributes.key?(:'credentials')
        self.credentials = attributes[:'credentials']
      end

      if attributes.key?(:'disability')
        self.disability = attributes[:'disability']
      end

      if attributes.key?(:'dob')
        self.dob = attributes[:'dob']
      end

      if attributes.key?(:'ell_status')
        self.ell_status = attributes[:'ell_status']
      end

      if attributes.key?(:'enrollments')
        if (value = attributes[:'enrollments']).is_a?(Array)
          self.enrollments = value
        end
      end

      if attributes.key?(:'ext')
        self.ext = attributes[:'ext']
      end

      if attributes.key?(:'frl_status')
        self.frl_status = attributes[:'frl_status']
      end

      if attributes.key?(:'gender')
        self.gender = attributes[:'gender']
      end

      if attributes.key?(:'gifted_status')
        self.gifted_status = attributes[:'gifted_status']
      end

      if attributes.key?(:'grade')
        self.grade = attributes[:'grade']
      end

      if attributes.key?(:'graduation_year')
        self.graduation_year = attributes[:'graduation_year']
      end

      if attributes.key?(:'hispanic_ethnicity')
        self.hispanic_ethnicity = attributes[:'hispanic_ethnicity']
      end

      if attributes.key?(:'home_language')
        self.home_language = attributes[:'home_language']
      end

      if attributes.key?(:'home_language_code')
        self.home_language_code = attributes[:'home_language_code']
      end

      if attributes.key?(:'iep_status')
        self.iep_status = attributes[:'iep_status']
      end

      if attributes.key?(:'last_modified')
        self.last_modified = attributes[:'last_modified']
      end

      if attributes.key?(:'legacy_id')
        self.legacy_id = attributes[:'legacy_id']
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.key?(:'preferred_name')
        self.preferred_name = attributes[:'preferred_name']
      end

      if attributes.key?(:'race')
        self.race = attributes[:'race']
      end

      if attributes.key?(:'school')
        self.school = attributes[:'school']
      end

      if attributes.key?(:'schools')
        if (value = attributes[:'schools']).is_a?(Array)
          self.schools = value
        end
      end

      if attributes.key?(:'section_504_status')
        self.section_504_status = attributes[:'section_504_status']
      end

      if attributes.key?(:'sis_id')
        self.sis_id = attributes[:'sis_id']
      end

      if attributes.key?(:'state_id')
        self.state_id = attributes[:'state_id']
      end

      if attributes.key?(:'student_number')
        self.student_number = attributes[:'student_number']
      end

      if attributes.key?(:'unweighted_gpa')
        self.unweighted_gpa = attributes[:'unweighted_gpa']
      end

      if attributes.key?(:'weighted_gpa')
        self.weighted_gpa = attributes[:'weighted_gpa']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      pattern = Regexp.new(/(?:[0-9]{1,2})\/([0-9]{1,2})\/([0-9]{4})/)
      if !@dob.nil? && @dob !~ pattern
        invalid_properties.push("invalid value for \"dob\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@dob.nil? && @dob !~ Regexp.new(/(?:[0-9]{1,2})\/([0-9]{1,2})\/([0-9]{4})/)
      ell_status_validator = EnumAttributeValidator.new('String', ["Y", "N", ""])
      return false unless ell_status_validator.valid?(@ell_status)
      frl_status_validator = EnumAttributeValidator.new('String', ["Free", "Reduced", "Paid", "Other", ""])
      return false unless frl_status_validator.valid?(@frl_status)
      gender_validator = EnumAttributeValidator.new('String', ["M", "F", "X", ""])
      return false unless gender_validator.valid?(@gender)
      gifted_status_validator = EnumAttributeValidator.new('String', ["Y", "N", ""])
      return false unless gifted_status_validator.valid?(@gifted_status)
      grade_validator = EnumAttributeValidator.new('String', ["InfantToddler", "Preschool", "PreKindergarten", "TransitionalKindergarten", "Kindergarten", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "PostGraduate", "Ungraded", "Other", ""])
      return false unless grade_validator.valid?(@grade)
      hispanic_ethnicity_validator = EnumAttributeValidator.new('String', ["Y", "N", ""])
      return false unless hispanic_ethnicity_validator.valid?(@hispanic_ethnicity)
      home_language_validator = EnumAttributeValidator.new('String', ["Galician", "Sindhi", "Vietnamese", "Cebuano", "Hawaiian", "Ewe", "Turkish", "Amharic", "Polish", "Oromo", "Maltese", "Krio", "Russian", "Shona", "Nepali", "Indonesian", "Tahitian", "Tsonga", "Tongan", "Burmese", "Irish", "Armenian", "Spanish", "Catalan", "Malay", "Malagasy", "Hmong", "Hindi", "Dogri", "Swedish", "Arabic", "Swahili", "Punjabi", "Azerbaijani", "Assamese", "French", "Georgian", "English", "Tamil", "Tatar", "German", "Romanian", "Bashkir", "Quechua", "Albanian", "Croatian", "Manipuri", "Bosnian", "Malayalam", "Gujarati", "Aymara", "Chichewa", "Javanese", "Faroese", "Serbian", "Xhosa", "Fijian", "Greek", "Belarusian", "Sinhala", "Uzbek", "Zulu", "Farsi", "Italian", "Other", "Cabo Verdean", "Haitian Creole", "Hebrew", "Kirundi", "Lower Sorbian", "Divehi", "Sundanese", "Maori", "Upper Sorbian", "Kinyarwanda", "Czech", "Bengali", "Sesotho", "Twi", "Japanese", "Queretaro Otomi", "Kyrgyz", "Welsh", "Mongolian", "Konkani", "Odia", "Guarani", "Kannada", "Lithuanian", "Samoan", "Somali", "Kazakh", "Hungarian", "Laotian", "Maithili", "Yoruba", "Luganda", "Hausa", "Thai", "Slovenian", "Bulgarian", "Dari", "Telugu", "Igbo", "Bambara", "Luxembourgish", "Chuukese", "Mizo", "Inuktitut", "Filipino", "Marshallese", "Ilocano", "Northern Sotho", "Tibetan", "Marathi", "Tajik", "Chinese", "Corsican", "Tagalog", "Dutch", "Urdu", "Portuguese", "Korean", "Estonian", "Danish", "Afrikaans", "Ukrainian", "Scots Gaelic", "Kurdish (Kurmanji)", "Macedonian", "Yucatec Maya", "Inuinnaqtun", "Cantonese", "Norwegian", "Basque", "Karen", "Yiddish", "Khmer", "Mandarin", "Setswana", "Tigrinya", "Icelandic", "Uyghur", "Kurdish (Sorani)", "Lingala", "Latvian", "Pashto", "Frisian", "Bhojpuri", "Finnish", "Slovak", "Turkmen"])
      return false unless home_language_validator.valid?(@home_language)
      home_language_code_validator = EnumAttributeValidator.new('String', ["bak", "mya", "cpp", "ikt", "ckb", "lin", "tgk", "cym", "yue", "nya", "dan", "mah", "jav", "mar", "tat", "guj", "nob", "sna", "slk", "zho", "ilo", "lug", "nep", "uzb", "fij", "aze", "kat", "hau", "kaz", "twi", "ces", "prs", "fao", "kan", "kur", "lav", "lit", "mni", "nso", "urd", "asm", "ind", "tel", "tuk", "bam", "bos", "hmn", "ita", "mal", "smo", "ben", "ewe", "deu", "hin", "por", "que", "sot", "afr", "eus", "heb", "kor", "mkd", "pol", "srp", "tha", "div", "dgo", "kar", "mai", "tsn", "tir", "cos", "isl", "mon", "ron", "yor", "zul", "other", "fas", "fra", "run", "sun", "tur", "amh", "aym", "nld", "hun", "ibo", "jpn", "bod", "ukr", "eng", "gle", "lao", "tam", "cat", "chk", "glg", "msa", "orm", "mlt", "mri", "lus", "snd", "yid", "hye", "knn", "dsb", "swe", "hsb", "ell", "otq", "tgl", "iku", "kin", "kri", "mlg", "pus", "rus", "gla", "tah", "xho", "ara", "hat", "sqi", "fry", "spa", "grn", "ltz", "yua", "ori", "uig", "tso", "khm", "kir", "vie", "bho", "ceb", "haw", "slv", "som", "swa", "ton", "bel", "est", "fin", "cmn", "sin", "bul", "hrv", "fil", "pan"])
      return false unless home_language_code_validator.valid?(@home_language_code)
      race_validator = EnumAttributeValidator.new('String', ["Caucasian", "Asian", "Black or African American", "American Indian", "Hawaiian or Other Pacific Islander", "Two or More Races", "Unknown", ""])
      return false unless race_validator.valid?(@race)
      section_504_status_validator = EnumAttributeValidator.new('String', ["Y", "N", ""])
      return false unless section_504_status_validator.valid?(@section_504_status)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] dob Value to be assigned
    def dob=(dob)
      pattern = Regexp.new(/(?:[0-9]{1,2})\/([0-9]{1,2})\/([0-9]{4})/)
      if !dob.nil? && dob !~ pattern
        fail ArgumentError, "invalid value for \"dob\", must conform to the pattern #{pattern}."
      end

      @dob = dob
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] ell_status Object to be assigned
    def ell_status=(ell_status)
      validator = EnumAttributeValidator.new('String', ["Y", "N", ""])
      unless validator.valid?(ell_status)
        fail ArgumentError, "invalid value for \"ell_status\", must be one of #{validator.allowable_values}."
      end
      @ell_status = ell_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] frl_status Object to be assigned
    def frl_status=(frl_status)
      validator = EnumAttributeValidator.new('String', ["Free", "Reduced", "Paid", "Other", ""])
      unless validator.valid?(frl_status)
        fail ArgumentError, "invalid value for \"frl_status\", must be one of #{validator.allowable_values}."
      end
      @frl_status = frl_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] gender Object to be assigned
    def gender=(gender)
      validator = EnumAttributeValidator.new('String', ["M", "F", "X", ""])
      unless validator.valid?(gender)
        fail ArgumentError, "invalid value for \"gender\", must be one of #{validator.allowable_values}."
      end
      @gender = gender
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] gifted_status Object to be assigned
    def gifted_status=(gifted_status)
      validator = EnumAttributeValidator.new('String', ["Y", "N", ""])
      unless validator.valid?(gifted_status)
        fail ArgumentError, "invalid value for \"gifted_status\", must be one of #{validator.allowable_values}."
      end
      @gifted_status = gifted_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] grade Object to be assigned
    def grade=(grade)
      validator = EnumAttributeValidator.new('String', ["InfantToddler", "Preschool", "PreKindergarten", "TransitionalKindergarten", "Kindergarten", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "PostGraduate", "Ungraded", "Other", ""])
      unless validator.valid?(grade)
        fail ArgumentError, "invalid value for \"grade\", must be one of #{validator.allowable_values}."
      end
      @grade = grade
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] hispanic_ethnicity Object to be assigned
    def hispanic_ethnicity=(hispanic_ethnicity)
      validator = EnumAttributeValidator.new('String', ["Y", "N", ""])
      unless validator.valid?(hispanic_ethnicity)
        fail ArgumentError, "invalid value for \"hispanic_ethnicity\", must be one of #{validator.allowable_values}."
      end
      @hispanic_ethnicity = hispanic_ethnicity
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] home_language Object to be assigned
    def home_language=(home_language)
      validator = EnumAttributeValidator.new('String', ["Galician", "Sindhi", "Vietnamese", "Cebuano", "Hawaiian", "Ewe", "Turkish", "Amharic", "Polish", "Oromo", "Maltese", "Krio", "Russian", "Shona", "Nepali", "Indonesian", "Tahitian", "Tsonga", "Tongan", "Burmese", "Irish", "Armenian", "Spanish", "Catalan", "Malay", "Malagasy", "Hmong", "Hindi", "Dogri", "Swedish", "Arabic", "Swahili", "Punjabi", "Azerbaijani", "Assamese", "French", "Georgian", "English", "Tamil", "Tatar", "German", "Romanian", "Bashkir", "Quechua", "Albanian", "Croatian", "Manipuri", "Bosnian", "Malayalam", "Gujarati", "Aymara", "Chichewa", "Javanese", "Faroese", "Serbian", "Xhosa", "Fijian", "Greek", "Belarusian", "Sinhala", "Uzbek", "Zulu", "Farsi", "Italian", "Other", "Cabo Verdean", "Haitian Creole", "Hebrew", "Kirundi", "Lower Sorbian", "Divehi", "Sundanese", "Maori", "Upper Sorbian", "Kinyarwanda", "Czech", "Bengali", "Sesotho", "Twi", "Japanese", "Queretaro Otomi", "Kyrgyz", "Welsh", "Mongolian", "Konkani", "Odia", "Guarani", "Kannada", "Lithuanian", "Samoan", "Somali", "Kazakh", "Hungarian", "Laotian", "Maithili", "Yoruba", "Luganda", "Hausa", "Thai", "Slovenian", "Bulgarian", "Dari", "Telugu", "Igbo", "Bambara", "Luxembourgish", "Chuukese", "Mizo", "Inuktitut", "Filipino", "Marshallese", "Ilocano", "Northern Sotho", "Tibetan", "Marathi", "Tajik", "Chinese", "Corsican", "Tagalog", "Dutch", "Urdu", "Portuguese", "Korean", "Estonian", "Danish", "Afrikaans", "Ukrainian", "Scots Gaelic", "Kurdish (Kurmanji)", "Macedonian", "Yucatec Maya", "Inuinnaqtun", "Cantonese", "Norwegian", "Basque", "Karen", "Yiddish", "Khmer", "Mandarin", "Setswana", "Tigrinya", "Icelandic", "Uyghur", "Kurdish (Sorani)", "Lingala", "Latvian", "Pashto", "Frisian", "Bhojpuri", "Finnish", "Slovak", "Turkmen"])
      unless validator.valid?(home_language)
        fail ArgumentError, "invalid value for \"home_language\", must be one of #{validator.allowable_values}."
      end
      @home_language = home_language
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] home_language_code Object to be assigned
    def home_language_code=(home_language_code)
      validator = EnumAttributeValidator.new('String', ["bak", "mya", "cpp", "ikt", "ckb", "lin", "tgk", "cym", "yue", "nya", "dan", "mah", "jav", "mar", "tat", "guj", "nob", "sna", "slk", "zho", "ilo", "lug", "nep", "uzb", "fij", "aze", "kat", "hau", "kaz", "twi", "ces", "prs", "fao", "kan", "kur", "lav", "lit", "mni", "nso", "urd", "asm", "ind", "tel", "tuk", "bam", "bos", "hmn", "ita", "mal", "smo", "ben", "ewe", "deu", "hin", "por", "que", "sot", "afr", "eus", "heb", "kor", "mkd", "pol", "srp", "tha", "div", "dgo", "kar", "mai", "tsn", "tir", "cos", "isl", "mon", "ron", "yor", "zul", "other", "fas", "fra", "run", "sun", "tur", "amh", "aym", "nld", "hun", "ibo", "jpn", "bod", "ukr", "eng", "gle", "lao", "tam", "cat", "chk", "glg", "msa", "orm", "mlt", "mri", "lus", "snd", "yid", "hye", "knn", "dsb", "swe", "hsb", "ell", "otq", "tgl", "iku", "kin", "kri", "mlg", "pus", "rus", "gla", "tah", "xho", "ara", "hat", "sqi", "fry", "spa", "grn", "ltz", "yua", "ori", "uig", "tso", "khm", "kir", "vie", "bho", "ceb", "haw", "slv", "som", "swa", "ton", "bel", "est", "fin", "cmn", "sin", "bul", "hrv", "fil", "pan"])
      unless validator.valid?(home_language_code)
        fail ArgumentError, "invalid value for \"home_language_code\", must be one of #{validator.allowable_values}."
      end
      @home_language_code = home_language_code
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] race Object to be assigned
    def race=(race)
      validator = EnumAttributeValidator.new('String', ["Caucasian", "Asian", "Black or African American", "American Indian", "Hawaiian or Other Pacific Islander", "Two or More Races", "Unknown", ""])
      unless validator.valid?(race)
        fail ArgumentError, "invalid value for \"race\", must be one of #{validator.allowable_values}."
      end
      @race = race
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] section_504_status Object to be assigned
    def section_504_status=(section_504_status)
      validator = EnumAttributeValidator.new('String', ["Y", "N", ""])
      unless validator.valid?(section_504_status)
        fail ArgumentError, "invalid value for \"section_504_status\", must be one of #{validator.allowable_values}."
      end
      @section_504_status = section_504_status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          created == o.created &&
          credentials == o.credentials &&
          disability == o.disability &&
          dob == o.dob &&
          ell_status == o.ell_status &&
          enrollments == o.enrollments &&
          ext == o.ext &&
          frl_status == o.frl_status &&
          gender == o.gender &&
          gifted_status == o.gifted_status &&
          grade == o.grade &&
          graduation_year == o.graduation_year &&
          hispanic_ethnicity == o.hispanic_ethnicity &&
          home_language == o.home_language &&
          home_language_code == o.home_language_code &&
          iep_status == o.iep_status &&
          last_modified == o.last_modified &&
          legacy_id == o.legacy_id &&
          location == o.location &&
          preferred_name == o.preferred_name &&
          race == o.race &&
          school == o.school &&
          schools == o.schools &&
          section_504_status == o.section_504_status &&
          sis_id == o.sis_id &&
          state_id == o.state_id &&
          student_number == o.student_number &&
          unweighted_gpa == o.unweighted_gpa &&
          weighted_gpa == o.weighted_gpa
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [created, credentials, disability, dob, ell_status, enrollments, ext, frl_status, gender, gifted_status, grade, graduation_year, hispanic_ethnicity, home_language, home_language_code, iep_status, last_modified, legacy_id, location, preferred_name, race, school, schools, section_504_status, sis_id, state_id, student_number, unweighted_gpa, weighted_gpa].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
