=begin
#Clever API

#The Clever API

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Clever
  class Submission < ApiModelBase
    attr_accessor :assignment_id

    attr_accessor :attachments

    attr_accessor :created

    attr_accessor :extra_attempts

    attr_accessor :flags

    attr_accessor :grade

    attr_accessor :grade_comment

    attr_accessor :grade_points

    attr_accessor :grader_id

    attr_accessor :id

    attr_accessor :last_modified

    attr_accessor :override_due_date

    attr_accessor :state

    attr_accessor :user_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'assignment_id' => :'assignment_id',
        :'attachments' => :'attachments',
        :'created' => :'created',
        :'extra_attempts' => :'extra_attempts',
        :'flags' => :'flags',
        :'grade' => :'grade',
        :'grade_comment' => :'grade_comment',
        :'grade_points' => :'grade_points',
        :'grader_id' => :'grader_id',
        :'id' => :'id',
        :'last_modified' => :'last_modified',
        :'override_due_date' => :'override_due_date',
        :'state' => :'state',
        :'user_id' => :'user_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'assignment_id' => :'String',
        :'attachments' => :'Array<Attachment>',
        :'created' => :'String',
        :'extra_attempts' => :'Integer',
        :'flags' => :'Array<SubmissionFlag>',
        :'grade' => :'String',
        :'grade_comment' => :'String',
        :'grade_points' => :'Float',
        :'grader_id' => :'String',
        :'id' => :'String',
        :'last_modified' => :'String',
        :'override_due_date' => :'String',
        :'state' => :'SubmissionState',
        :'user_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'created',
        :'grade',
        :'grade_comment',
        :'grader_id',
        :'last_modified',
        :'override_due_date',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Clever::Submission` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Clever::Submission`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'assignment_id')
        self.assignment_id = attributes[:'assignment_id']
      end

      if attributes.key?(:'attachments')
        if (value = attributes[:'attachments']).is_a?(Array)
          self.attachments = value
        end
      end

      if attributes.key?(:'created')
        self.created = attributes[:'created']
      end

      if attributes.key?(:'extra_attempts')
        self.extra_attempts = attributes[:'extra_attempts']
      end

      if attributes.key?(:'flags')
        if (value = attributes[:'flags']).is_a?(Array)
          self.flags = value
        end
      end

      if attributes.key?(:'grade')
        self.grade = attributes[:'grade']
      end

      if attributes.key?(:'grade_comment')
        self.grade_comment = attributes[:'grade_comment']
      end

      if attributes.key?(:'grade_points')
        self.grade_points = attributes[:'grade_points']
      end

      if attributes.key?(:'grader_id')
        self.grader_id = attributes[:'grader_id']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'last_modified')
        self.last_modified = attributes[:'last_modified']
      end

      if attributes.key?(:'override_due_date')
        self.override_due_date = attributes[:'override_due_date']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          assignment_id == o.assignment_id &&
          attachments == o.attachments &&
          created == o.created &&
          extra_attempts == o.extra_attempts &&
          flags == o.flags &&
          grade == o.grade &&
          grade_comment == o.grade_comment &&
          grade_points == o.grade_points &&
          grader_id == o.grader_id &&
          id == o.id &&
          last_modified == o.last_modified &&
          override_due_date == o.override_due_date &&
          state == o.state &&
          user_id == o.user_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [assignment_id, attachments, created, extra_attempts, flags, grade, grade_comment, grade_points, grader_id, id, last_modified, override_due_date, state, user_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
