---
driver:
  name: dokken
  chef_version: 12.7.2
transport:
  name: dokken
provisioner:
  name: dokken
platforms:
  - name: ubuntu-14.04
    driver:
      image: dokken/ubuntu-14.04
      pid_one_command: /sbin/init
    run_list:
      - recipe[apt]
suites:
  - name: default
    run_list:
      - recipe[cdo-redis]
