// Minimal replica of the legacy avatar mapping
// (apps/src/templates/studioHomepages/teacherHomepageV2/sectionAvatars/
// avatarConstants.js) so the read-only card label matches legacy without
// importing across the bundle boundary. Order is the wire contract:
// avatar_color/avatar_emoji are indexes into these arrays.

export const EMOJIS = [
  '🔥',
  '🐧',
  '👾',
  '👻',
  '🌈',
  '🤖',
  '🍄',
  '🚀',
  '🦕',
  '🛼',
  '😺',
  '☔',
  '🍩',
  '🐙',
  '🐝',
  '🥨',
  '☎️',
  '🐼',
  '🧩',
  '🐬',
  '🦄',
] as const;

export const EMOJI_LABELS = [
  'Fire',
  'Penguin',
  'Alien',
  'Ghost',
  'Rainbow',
  'Robot',
  'Mushroom',
  'Rocket',
  'Dinosaur',
  'Roller Skate',
  'Cat',
  'Umbrella',
  'Doughnut',
  'Octopus',
  'Bee',
  'Pretzel',
  'Phone',
  'Panda',
  'Puzzle Piece',
  'Dolphin',
  'Unicorn',
] as const;

export const COLORS = [
  '#EB1460',
  '#F62CAF',
  '#9C1AB1',
  '#6633B9',
  '#3D4DB7',
  '#1093F5',
  '#00BBD5',
  '#009687',
  '#46AF4A',
  '#88C440',
  '#CCDD1E',
  '#FFEC16',
  '#FFC100',
  '#FF9800',
  '#FF6505',
  '#F62C2C',
  '#7A5547',
  '#9D9D9D',
  '#5E7C8B',
  '#000000',
] as const;

export const COLOR_LABELS = [
  'Magenta',
  'Pink',
  'Purple',
  'Dark Purple',
  'Navy Blue',
  'Blue',
  'Aqua Blue',
  'Teal',
  'Green',
  'Light Green',
  'Yellow Green',
  'Yellow',
  'Orange Yellow',
  'Orange',
  'Red Orange',
  'Red',
  'Brown',
  'Gray',
  'Blue Gray',
  'Black',
] as const;
