/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MSeatsRouteImport } from './routes/m/seats'
import { Route as MJourneyRouteImport } from './routes/m/journey'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as MLessonLessonIdRouteImport } from './routes/m/lesson.$lessonId'
import { Route as ProjectsLabTypeChannelIdEditRouteImport } from './routes/projects/$labType/$channelId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSeatsRoute = MSeatsRouteImport.update({
  id: '/m/seats',
  path: '/m/seats',
  getParentRoute: () => rootRouteImport,
} as any)
const MJourneyRoute = MJourneyRouteImport.update({
  id: '/m/journey',
  path: '/m/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MLessonLessonIdRoute = MLessonLessonIdRouteImport.update({
  id: '/m/lesson/$lessonId',
  path: '/m/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsLabTypeChannelIdEditRoute =
  ProjectsLabTypeChannelIdEditRouteImport.update({
    id: '/projects/$labType/$channelId/edit',
    path: '/projects/$labType/$channelId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/m/journey': typeof MJourneyRoute
  '/m/seats': typeof MSeatsRoute
  '/m/lesson/$lessonId': typeof MLessonLessonIdRoute
  '/projects/$labType/$channelId/edit': typeof ProjectsLabTypeChannelIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/m/journey': typeof MJourneyRoute
  '/m/seats': typeof MSeatsRoute
  '/m/lesson/$lessonId': typeof MLessonLessonIdRoute
  '/projects/$labType/$channelId/edit': typeof ProjectsLabTypeChannelIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/m/journey': typeof MJourneyRoute
  '/m/seats': typeof MSeatsRoute
  '/m/lesson/$lessonId': typeof MLessonLessonIdRoute
  '/projects/$labType/$channelId/edit': typeof ProjectsLabTypeChannelIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses/$slug'
    | '/m/journey'
    | '/m/seats'
    | '/m/lesson/$lessonId'
    | '/projects/$labType/$channelId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses/$slug'
    | '/m/journey'
    | '/m/seats'
    | '/m/lesson/$lessonId'
    | '/projects/$labType/$channelId/edit'
  id:
    | '__root__'
    | '/'
    | '/courses/$slug'
    | '/m/journey'
    | '/m/seats'
    | '/m/lesson/$lessonId'
    | '/projects/$labType/$channelId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  MJourneyRoute: typeof MJourneyRoute
  MSeatsRoute: typeof MSeatsRoute
  MLessonLessonIdRoute: typeof MLessonLessonIdRoute
  ProjectsLabTypeChannelIdEditRoute: typeof ProjectsLabTypeChannelIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/seats': {
      id: '/m/seats'
      path: '/m/seats'
      fullPath: '/m/seats'
      preLoaderRoute: typeof MSeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/journey': {
      id: '/m/journey'
      path: '/m/journey'
      fullPath: '/m/journey'
      preLoaderRoute: typeof MJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/lesson/$lessonId': {
      id: '/m/lesson/$lessonId'
      path: '/m/lesson/$lessonId'
      fullPath: '/m/lesson/$lessonId'
      preLoaderRoute: typeof MLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$labType/$channelId/edit': {
      id: '/projects/$labType/$channelId/edit'
      path: '/projects/$labType/$channelId/edit'
      fullPath: '/projects/$labType/$channelId/edit'
      preLoaderRoute: typeof ProjectsLabTypeChannelIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  MJourneyRoute: MJourneyRoute,
  MSeatsRoute: MSeatsRoute,
  MLessonLessonIdRoute: MLessonLessonIdRoute,
  ProjectsLabTypeChannelIdEditRoute: ProjectsLabTypeChannelIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
