/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LevelsLevelIdRouteImport } from './routes/levels/$levelId'
import { Route as ProjectsLabTypeChannelIdEditRouteImport } from './routes/projects/$labType/$channelId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsLevelIdRoute = LevelsLevelIdRouteImport.update({
  id: '/levels/$levelId',
  path: '/levels/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsLabTypeChannelIdEditRoute =
  ProjectsLabTypeChannelIdEditRouteImport.update({
    id: '/projects/$labType/$channelId/edit',
    path: '/projects/$labType/$channelId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/levels/$levelId': typeof LevelsLevelIdRoute
  '/projects/$labType/$channelId/edit': typeof ProjectsLabTypeChannelIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/levels/$levelId': typeof LevelsLevelIdRoute
  '/projects/$labType/$channelId/edit': typeof ProjectsLabTypeChannelIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/levels/$levelId': typeof LevelsLevelIdRoute
  '/projects/$labType/$channelId/edit': typeof ProjectsLabTypeChannelIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/levels/$levelId' | '/projects/$labType/$channelId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/levels/$levelId' | '/projects/$labType/$channelId/edit'
  id:
    | '__root__'
    | '/'
    | '/levels/$levelId'
    | '/projects/$labType/$channelId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LevelsLevelIdRoute: typeof LevelsLevelIdRoute
  ProjectsLabTypeChannelIdEditRoute: typeof ProjectsLabTypeChannelIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$levelId': {
      id: '/levels/$levelId'
      path: '/levels/$levelId'
      fullPath: '/levels/$levelId'
      preLoaderRoute: typeof LevelsLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$labType/$channelId/edit': {
      id: '/projects/$labType/$channelId/edit'
      path: '/projects/$labType/$channelId/edit'
      fullPath: '/projects/$labType/$channelId/edit'
      preLoaderRoute: typeof ProjectsLabTypeChannelIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LevelsLevelIdRoute: LevelsLevelIdRoute,
  ProjectsLabTypeChannelIdEditRoute: ProjectsLabTypeChannelIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
