import {ParticipantAudience} from '@cdo/apps/generated/curriculum/sharedCourseConstants';
import {Section} from '@cdo/apps/templates/teacherDashboard/types/teacherSectionTypes';

export const MockAgeGatedSections: Section[] = [
  {
    id: 11,
    name: 'Algebra Period 1',
    studentCount: 14,
    loginType: 'word',
    code: 'ABCDEF',
    providerManaged: false,
    hidden: false,
    participantType: ParticipantAudience.student,
    atRiskAgeGatedDate: new Date('2025-01-01T00:00:00-05:00'),
    atRiskAgeGatedUsState: 'CO',
    grades: ['3', '4', '5'],
    aiTutorEnabled: false,
    courseDisplayName: null,
    isAssignedStandaloneCourse: false,
    lessonExtras: false,
    pairingAllowed: false,
    restrictSection: false,
    sharingDisabled: false,
    ttsAutoplayEnabled: false,
    unitName: null,
  },
  {
    id: 12,
    name: 'Algebra Period 2',
    studentCount: 19,
    loginType: 'word',
    code: 'EEB206',
    providerManaged: false,
    hidden: false,
    participantType: ParticipantAudience.student,
    atRiskAgeGatedDate: new Date('2025-01-01T00:00:00-05:00'),
    atRiskAgeGatedUsState: 'CO',
    grades: [],
    aiTutorEnabled: false,
    courseDisplayName: null,
    isAssignedStandaloneCourse: false,
    lessonExtras: false,
    pairingAllowed: false,
    restrictSection: false,
    sharingDisabled: false,
    ttsAutoplayEnabled: false,
    unitName: null,
  },
  {
    id: 13,
    name: 'Period 3',
    studentCount: 22,
    loginType: 'word',
    code: 'HPRWHG',
    providerManaged: false,
    hidden: false,
    participantType: ParticipantAudience.student,
    atRiskAgeGatedDate: new Date('2025-01-01T00:00:00-05:00'),
    atRiskAgeGatedUsState: 'CO',
    grades: [],
    aiTutorEnabled: false,
    courseDisplayName: null,
    isAssignedStandaloneCourse: false,
    lessonExtras: false,
    pairingAllowed: false,
    restrictSection: false,
    sharingDisabled: false,
    ttsAutoplayEnabled: false,
    unitName: null,
  },
  {
    id: 14,
    name: 'Young students',
    studentCount: 22,
    loginType: 'word',
    code: 'FJDISO',
    providerManaged: false,
    hidden: false,
    participantType: ParticipantAudience.student,
    atRiskAgeGatedDate: new Date('2025-01-01T00:00:00-05:00'),
    atRiskAgeGatedUsState: 'CO',
    grades: ['1', '2', '3'],
    aiTutorEnabled: false,
    courseDisplayName: null,
    isAssignedStandaloneCourse: false,
    lessonExtras: false,
    pairingAllowed: false,
    restrictSection: false,
    sharingDisabled: false,
    ttsAutoplayEnabled: false,
    unitName: null,
  },
];
