import {ParticipantAudience} from '@cdo/apps/generated/curriculum/sharedCourseConstants';
import {RowType} from '@cdo/apps/templates/manageStudents/manageStudentsRedux';
import {ChildAccountComplianceStates} from '@cdo/generated-scripts/sharedConstants';

export const MockStudentData = [
  {
    id: 1,
    name: 'Clark Kent',
    username: 'clark_kent',
    sectionId: 101,
    hasEverSignedIn: false,
    dependsOnThisSectionForLogin: true,
    loginType: 'google_oauth2',
    rowType: RowType.STUDENT,
    age: 10,
    atRiskAgeGatedStudent: true,
    childAccountComplianceState: ChildAccountComplianceStates.LOCKED_OUT,
    latestPermissionRequestSentAt: null,
  },
  {
    id: 2,
    name: 'Joe Smith',
    username: 'joe_smith',
    sectionId: 101,
    hasEverSignedIn: false,
    dependsOnThisSectionForLogin: true,
    loginType: 'google_oauth2',
    rowType: RowType.STUDENT,
    age: 10,
    atRiskAgeGatedStudent: false,
    childAccountComplianceState: '',
    latestPermissionRequestSentAt: null,
  },
  {
    id: 3,
    name: 'test student',
    username: 'test_student3',
    sectionId: 101,
    hasEverSignedIn: false,
    dependsOnThisSectionForLogin: true,
    loginType: 'google_oauth2',
    rowType: RowType.STUDENT,
    age: 10,
    atRiskAgeGatedStudent: true,
    childAccountComplianceState: ChildAccountComplianceStates.GRACE_PERIOD,
    latestPermissionRequestSentAt: null,
  },
  {
    id: 4,
    name: 'fake student',
    username: 'fake_student4',
    sectionId: 101,
    hasEverSignedIn: false,
    dependsOnThisSectionForLogin: true,
    loginType: 'google_oauth2',
    rowType: RowType.STUDENT,
    age: 10,
    atRiskAgeGatedStudent: false,
    childAccountComplianceState: '',
    latestPermissionRequestSentAt: null,
  },
  {
    id: 5,
    name: 'Kent Clark',
    username: 'fake_student5',
    sectionId: 101,
    hasEverSignedIn: false,
    dependsOnThisSectionForLogin: true,
    loginType: 'google_oauth2',
    rowType: RowType.STUDENT,
    age: 10,
    atRiskAgeGatedStudent: true,
    childAccountComplianceState:
      ChildAccountComplianceStates.PERMISSION_GRANTED,
    latestPermissionRequestSentAt: new Date(),
  },
];

export const MockAgeGatedSections = [
  {
    id: 11,
    name: 'Algebra Period 1',
    teacherName: 'Ms. Frizzle',
    linkToProgress: 'to Progress tab',
    assignedTitle: 'CS in Algebra',
    linkToAssigned: 'to Course',
    studentCount: 14,
    linkToStudents: 'to Manage Students tab',
    loginType: 'word',
    code: 'ABCDEF',
    providerManaged: false,
    hidden: false,
    participantType: ParticipantAudience.student,
    atRiskAgeGated: true,
    grades: ['3', '4', '5'],
  },
  {
    id: 12,
    name: 'Algebra Period 2',
    teacherName: 'Ms. Frizzle',
    linkToProgress: 'to Progress tab',
    assignedTitle: 'CS in Algebra',
    linkToAssigned: 'to Course',
    studentCount: 19,
    linkToStudents: 'to Manage Students tab',
    loginType: 'word',
    code: 'EEB206',
    providerManaged: false,
    hidden: false,
    participantType: ParticipantAudience.student,
    atRiskAgeGated: true,
    grades: undefined,
  },
  {
    id: 13,
    name: 'Period 3',
    teacherName: 'Ms. Frizzle',
    linkToProgress: 'to Progress tab',
    assignedTitle: 'Course 4',
    linkToAssigned: 'to Course',
    studentCount: 22,
    linkToStudents: 'to Manage Students tab',
    loginType: 'word',
    code: 'HPRWHG',
    providerManaged: false,
    hidden: false,
    participantType: ParticipantAudience.student,
    atRiskAgeGated: true,
    grades: undefined,
  },
  {
    id: 14,
    name: 'Young students',
    teacherName: 'Ms. Frizzle',
    linkToProgress: 'to Progress tab',
    assignedTitle: 'Course 4',
    linkToAssigned: 'to Course',
    studentCount: 22,
    linkToStudents: 'to Manage Students tab',
    loginType: 'word',
    code: 'FJDISO',
    providerManaged: false,
    hidden: false,
    participantType: ParticipantAudience.student,
    atRiskAgeGated: true,
    grades: ['1', '2', '3'],
  },
];
