=begin
#Clever API

#The Clever API

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

# Common files
require 'clever_client/api_client'
require 'clever_client/api_error'
require 'clever_client/api_model_base'
require 'clever_client/version'
require 'clever_client/configuration'

# Models
require 'clever_client/models/assignee_mode'
require 'clever_client/models/assignment'
require 'clever_client/models/assignment_request'
require 'clever_client/models/assignment_response'
require 'clever_client/models/assignment_state'
require 'clever_client/models/attachment'
require 'clever_client/models/attachment_request'
require 'clever_client/models/attendance'
require 'clever_client/models/attendance_response'
require 'clever_client/models/attendance_status'
require 'clever_client/models/attendance_type'
require 'clever_client/models/bad_request'
require 'clever_client/models/contact'
require 'clever_client/models/course'
require 'clever_client/models/course_object'
require 'clever_client/models/course_response'
require 'clever_client/models/courses_response'
require 'clever_client/models/credentials'
require 'clever_client/models/disability'
require 'clever_client/models/district'
require 'clever_client/models/district_admin'
require 'clever_client/models/district_contact'
require 'clever_client/models/district_object'
require 'clever_client/models/district_response'
require 'clever_client/models/districts_response'
require 'clever_client/models/event'
require 'clever_client/models/event_response'
require 'clever_client/models/events_response'
require 'clever_client/models/grading_scale'
require 'clever_client/models/grading_scale_entry'
require 'clever_client/models/grading_type'
require 'clever_client/models/internal_error'
require 'clever_client/models/link'
require 'clever_client/models/lms_status'
require 'clever_client/models/location'
require 'clever_client/models/name'
require 'clever_client/models/not_found'
require 'clever_client/models/preferred_name'
require 'clever_client/models/principal'
require 'clever_client/models/resource'
require 'clever_client/models/resource_object'
require 'clever_client/models/resource_response'
require 'clever_client/models/resources_response'
require 'clever_client/models/roles'
require 'clever_client/models/school'
require 'clever_client/models/school_enrollment'
require 'clever_client/models/school_object'
require 'clever_client/models/school_response'
require 'clever_client/models/schools_response'
require 'clever_client/models/section'
require 'clever_client/models/section_object'
require 'clever_client/models/section_response'
require 'clever_client/models/sections_response'
require 'clever_client/models/staff'
require 'clever_client/models/student'
require 'clever_client/models/student_relationship'
require 'clever_client/models/submission'
require 'clever_client/models/submission_flag'
require 'clever_client/models/submission_request'
require 'clever_client/models/submission_response'
require 'clever_client/models/submission_state'
require 'clever_client/models/submission_type'
require 'clever_client/models/submissions_link'
require 'clever_client/models/submissions_response'
require 'clever_client/models/teacher'
require 'clever_client/models/term'
require 'clever_client/models/term_object'
require 'clever_client/models/term_response'
require 'clever_client/models/terms_response'
require 'clever_client/models/unauthorized'
require 'clever_client/models/user'
require 'clever_client/models/user_object'
require 'clever_client/models/user_response'
require 'clever_client/models/users_response'
require 'clever_client/models/courses_created'
require 'clever_client/models/courses_deleted'
require 'clever_client/models/courses_updated'
require 'clever_client/models/districts_created'
require 'clever_client/models/districts_deleted'
require 'clever_client/models/districts_updated'
require 'clever_client/models/resources_created'
require 'clever_client/models/resources_deleted'
require 'clever_client/models/resources_updated'
require 'clever_client/models/schools_created'
require 'clever_client/models/schools_deleted'
require 'clever_client/models/schools_updated'
require 'clever_client/models/sections_created'
require 'clever_client/models/sections_deleted'
require 'clever_client/models/sections_updated'
require 'clever_client/models/terms_created'
require 'clever_client/models/terms_deleted'
require 'clever_client/models/terms_updated'
require 'clever_client/models/users_created'
require 'clever_client/models/users_deleted'
require 'clever_client/models/users_updated'

# APIs
require 'clever_client/api/attendance_api'
require 'clever_client/api/data_api'
require 'clever_client/api/events_api'
require 'clever_client/api/lms_connect_api'

module Clever
  class << self
    # Customize default settings for the SDK using block.
    #   Clever.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
