kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: git-shallow-fetch
  image: wintercdo/code-dot-org:0.7
  depends_on: [ clone ]
  commands:
    - sudo chown -R circleci:circleci .

    - docker/git_shallow_fetch.sh

- name: unit-tests
  image: wintercdo/code-dot-org:0.7
  depends_on: [ git-shallow-fetch ]
  environment:
    CLOUDFRONT_KEY_PAIR_ID:
      from_secret: CLOUDFRONT_KEY_PAIR_ID
    CLOUDFRONT_PRIVATE_KEY:
      from_secret: CLOUDFRONT_PRIVATE_KEY
    PROPERTIES_ENCRYPTION_KEY:
      from_secret: PROPERTIES_ENCRYPTION_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - pwd
    - whoami
    - id -u
    - id -g
    - ls -alh
    - /entrypoint.sh docker/unit_tests.sh

- name: ui-tests
  image: wintercdo/code-dot-org:0.7
  depends_on: [ git-shallow-fetch ]
  environment:
    CLOUDFRONT_KEY_PAIR_ID:
      from_secret: CLOUDFRONT_KEY_PAIR_ID
    CLOUDFRONT_PRIVATE_KEY:
      from_secret: CLOUDFRONT_PRIVATE_KEY
    PROPERTIES_ENCRYPTION_KEY:
      from_secret: PROPERTIES_ENCRYPTION_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    APPLITOOLS_KEY:
      from_secret: APPLITOOLS_KEY
    FIREBASE_NAME:
      from_secret: FIREBASE_NAME
    SAUCE_USERNAME:
      from_secret: SAUCE_USERNAME
    SAUCE_ACCESS_KEY:
      from_secret: SAUCE_ACCESS_KEY
  commands:
    - pwd
    - whoami
    - id -u
    - id -g
    - ls -alh
    - sudo chown -R circleci:circleci .
    - /entrypoint.sh docker/ui_tests.sh

trigger:
  branch:
  - drone
