skip_frontmatter: true
inherits_from: .haml-lint_todo.yml

linters:
  TrailingWhitespace:
    exclude:
      - '/**/pegasus/**/*.haml'
      - 'pegasus/**/*.haml'

  # Custom rule
  ConsistentQuotationMark:
    enabled: true
    include:
      - '/**/*mailer*/**/*.haml'
exclude:
- '/**/pegasus/test/fixtures/**/*.haml'
- 'pegasus/test/fixtures/**/*.haml'
require:
- './tools/customLinters/haml-lint-consistent-quotation-mark.rb'
