skip_frontmatter: true
inherits_from: .haml-lint_todo.yml

linters:
  TrailingWhitespace:
    exclude:
      - '/**/pegasus/**/*.haml'
      - 'pegasus/**/*.haml'

  ConsistentQuotationMark:
    enabled: true
exclude:
- '/**/pegasus/test/fixtures/**/*.haml'
- 'pegasus/test/fixtures/**/*.haml'
require:
- './haml-lint-consistent-quotation-mark.rb'