skip_frontmatter: true
inherits_from: .haml-lint_todo.yml

linters:
  TrailingWhitespace:
    exclude:
      - '/**/pegasus/**/*.haml'
      - 'pegasus/**/*.haml'

  # Custom rule
  OnlyAllowedCharacters:
    enabled: true
    include:
      - '/**/*mailer*/**/*.haml'
exclude:
- '/**/pegasus/test/fixtures/**/*.haml'
- 'pegasus/test/fixtures/**/*.haml'
require:
- './tools/customLinters/haml_lint_only_allowed_characters.rb'
