# Mark GitHub Status API as failed if Hound finds any violations.
fail_on_violations: true

ruby:
  config_file: .rubocop.yml

eslint:
  enabled: true
  config_file: .eslintrc.js

scss:
  config_file: .scss-lint.yml

haml:
  config_file: .haml-lint.yml
