# Mark GitHub Status API as failed if Hound finds any violations.
fail_on_violations: true

ruby:
  config_file: .rubocop.yml

javascript:
  enabled: false

scss:
  config_file: .scss-lint.yml

haml:
  config_file: .haml-lint.yml
