# Mark GitHub Status API as failed if Hound finds any violations.
fail_on_violations: true

ruby:
  config_file: .rubocop.yml

javascript:
  enabled: false
eslint:
  enabled: true
  config_file: .eslintrc.js

scss:
  enabled: false

haml:
  config_file: .haml-lint.yml
