inherit_from:
  - .rubocop_hound.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'apps/**/*'
    - 'dashboard/scripts/**/*'
    - 'dashboard/db/**/*'
  RunRailsCops: true
  DisplayCopNames: true

# Listed are rules we don't plan to enable in the foreseeable future.
# Add rules we plan to fix (but are currently failing) to .rubocop_todo.yml.

Style/BarePercentLiterals:
  Enabled: false

# Require trailing dots for method chaining in ruby
# example:
# MyObject.
#   myMethod().
#   mySecondMethod()
Style/DotPosition:
  EnforcedStyle: trailing

Style/ExtraSpacing:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/NumericLiterals:
  Enabled: true
  MinDigits: 7
