inherit_from:
  - .rubocop_hound.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'apps/**/*'
    - 'dashboard/db/**/*'
    - 'dashboard/db/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.2

# Listed are rules we don't plan to enable in the foreseeable future.
# Add rules we plan to fix (but are currently failing) to .rubocop_todo.yml.

Style/BarePercentLiterals:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

# Require trailing dots for method chaining in ruby
# example:
# MyObject.
#   myMethod().
#   mySecondMethod()
Style/DotPosition:
  EnforcedStyle: trailing

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true 

Style/ExtraSpacing:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/WordArray:
  MinSize: 5

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/NumericLiterals:
  MinDigits: 7
