inherit_from:
  - .rubocop_hound.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'apps/**/*'
    - 'dashboard/db/schema.rb'
    - 'pegasus/test/test_string.rb' # Parser does not support non-utf8 escape sequences
  DisplayCopNames: true
  TargetRubyVersion: 2.5

Rails:
  Enabled: true

# BEGIN CODE.ORG OVERRIDES

Rails/Delegate:
  Include:
    - dashboard/**/*

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Style/EmptyElse:
  EnforcedStyle: empty

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/NumericLiterals:
  MinDigits: 7

Style/Semicolon:
  AllowAsExpressionSeparator: true

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/WordArray:
  MinSize: 5

# END CODE.ORG OVERRIDES

# BEGIN BLACKLIST: Below are rules we don't plan to enable in the forseeable
# future. Rules we plan to fix (but are currently failing) belong in
# .rubocop_todo.yml.
Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrivialAccessors:
  AllowDSLWriters: true

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# END BLACKLIST
