inherit_from:
  - .rubocop_hound.yml
  - .rubocop_new.yml
  - .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rails-accessibility
  - './tools/customLinters/rubocop_only_allowed_characters.rb'

AllCops:
  SuggestExtensions: false
  Exclude:
    - 'apps/**/*'
    - 'dashboard/db/schema.rb'
    - 'pegasus/test/test_string.rb' # Parser does not support non-utf8 escape sequences
  DisplayCopNames: true
  TargetRubyVersion: 2.7

Rails:
  Enabled: true
  Include:
    - dashboard/**/* # only run Rails cops on Rails-specific code
  Exclude:
    - dashboard/legacy/**/*

# BEGIN CODE.ORG OVERRIDES

CustomCops/OnlyAllowedCharacters:
  Include:
    - '**/*_mailer.rb'

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

# This Cop by default uses a custom Include directive which in our
# project would also include pegasus
# see https://github.com/rubocop/rubocop-rails/blob/d81af275bba3d06e30156596c2c057cf68f8272b/config/default.yml#L213C11-L213C11
Rails/AssertNot:
  Include:
    - dashboard/**/test/**/*

Rails/Date:
  EnforcedStyle: strict

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/EmptyElse:
  EnforcedStyle: empty

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/NumericLiterals:
  MinDigits: 7

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/WordArray:
  MinSize: 5

# END CODE.ORG OVERRIDES

# BEGIN BLOCKLIST: Below are rules we don't plan to enable in the forseeable
# future. Rules we plan to fix (but are currently failing) belong in
# .rubocop_todo.yml.
Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# ActiveRecord does not implement a `detect` method and `find` has its own
# meaning. Correcting ActiveRecord methods with this cop should be considered
# unsafe, so out of an abundance of caution disable this everywhere.
Performance/Detect:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrivialAccessors:
  AllowDSLWriters: true

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# END BLOCKLIST
