# This is an SCSS linter for the backend, using scss-lint
# which is no longer supported: https://github.com/sds/scss-lint#notice-consider-other-tools-before-adopting-scss-lint
# On the frontend, we are using stylelint-scss, whose
# config can be found in apps/stylelint.config.js
scss_files: 'dashboard/app/**/*.scss'

linters:
  LeadingZero:
    style: include_zero
  QualifyingElement:
    allow_element_with_attribute: true
    allow_element_with_class: true
  Shorthand:
    allowed_shorthands: [1, 2, 4]
  SingleLinePerProperty:
    allow_single_line_rule_sets: false

  # Ignored rules: we don't plan to enable these in the foreseeable future.
  IdSelector:
    enabled: false
  NestingDepth:
    enabled: false
  PropertyCount:
    enabled: false
  PropertySortOrder:
    enabled: false
  SelectorDepth:
    enabled: false

  # Rules we should either ignore or fix (but are currently failing).
  BorderZero:
    enabled: false
  Comment:
    enabled: false
  DeclarationOrder:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  ImportantRule:
    enabled: false
  MergeableSelector:
    enabled: false
  NameFormat:
    enabled: false
  SelectorFormat:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  StringQuotes:
    enabled: false
  UnnecessaryParentReference:
    enabled: false
  VendorPrefix:
    enabled: false
