#!/usr/bin/env ruby
# Self-contained wrapper script to run foreman on our project's three processes.

proc = <<Procfile
dashboard: rake build:dashboard && bin/dashboard-server
pegasus: rake build:pegasus && bin/pegasus-server
blockly: rake build:blockly && MOOC_DEV=1 bin/blockly-dev
Procfile

require 'tempfile'
procfile = Tempfile.new 'procfile'
procfile.write(proc)
procfile.close

def load_gem(name)
  begin
    gem name
  rescue LoadError
    system("gem install #{name}")
    Gem.clear_paths
    retry
  end
  require name
end

load_gem 'foreman'
system "foreman start -f #{procfile.path} -d #{__dir__}"
