apiVersion: v1
kind: Service
metadata:
  name: cdo-mysql
  labels:
    app.kubernetes.io/component: mysql
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
  selector:
    app.kubernetes.io/component: mysql
