apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdo-mysql
  labels:
    app.kubernetes.io/component: mysql
spec:
  serviceName: cdo-mysql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mysql
    spec:
      containers:
        - name: db
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cdo-local-secrets
                  key: _mysql_root_password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql/
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
