DEFAULT_SPRITES_LIST = [
  {name: 'bear', key: 'category_animals/bear'},
  {name: 'bee', key: 'category_animals/bee'},
  {name: 'brown bunny', key: 'category_animals/bunny1_ready'},
  {name: 'purple bunny', key: 'category_animals/bunny2'},
  {name: 'corgi', key: 'category_animals/corgi'},
  {name: 'cow', key: 'category_animals/cow'},
  {name: 'crab', key: 'category_animals/crab'},
  {name: 'elephant', key: 'category_animals/elephant2'},
  {name: 'fish', key: 'category_animals/fish'},
  {name: 'hippo', key: 'category_animals/hippo_gray'},
  {name: 'ladybug', key: 'category_animals/ladybug'},
  {name: 'mouse', key: 'category_animals/mouse'},
  {name: 'pig', key: 'category_animals/pig'},
  {name: 'bell', key: 'category_generic_items/bell'},
  {name: 'book', key: 'category_generic_items/book'},
  {name: 'compass', key: 'category_generic_items/compass'},
  {name: 'computer monitor', key: 'category_generic_items/computer_monitor'},
  {name: 'first aid kit', key: 'category_generic_items/first_aid'},
  {name: 'keys', key: 'category_generic_items/keys'},
  {name: 'money', key: 'category_generic_items/money'},
  {name: 'paint pallette', key: 'category_generic_items/paint_pallette'},
  {name: 'potion', key: 'category_generic_items/flask'},
  {name: 'tablet', key: 'category_generic_items/tablet'},
  {name: 'teapot', key: 'category_generic_items/teapot'},
  {name: 'boat', key: 'category_vehicles/boat'},
  {name: 'black car', key: 'category_vehicles/car_black'},
  {name: 'blue car', key: 'category_vehicles/car_blue'},
  {name: 'green car', key: 'category_vehicles/car_green'},
  {name: 'red car', key: 'category_vehicles/car_red'},
  {name: 'yellow car', key: 'category_vehicles/car_yellow'},
  {name: 'blue plane', key: 'category_vehicles/planeBlue1'},
  {name: 'red plane', key: 'category_vehicles/planeRed1'},
  {name: 'blue alien', key: 'category_characters/alienBlue'},
  {name: 'green alien', key: 'category_characters/alienGreen'},
  {name: 'pink alien', key: 'category_characters/alienPink'},
  {name: 'yellow alien', key: 'category_characters/alienYellow'},
  {name: 'ghost', key: 'category_characters/ghost'},
  {name: 'orange monster', key: 'category_characters/orange_monster'},
  {name: 'green monster', key: 'category_characters/happy_critter'},
  {name: 'purple monster', key: 'category_characters/purple_monster'},
  {name: 'cloud', key: 'category_environment/cloud'},
  {name: 'rock', key: 'category_environment/rock'},
  {name: 'sun', key: 'category_environment/sun'},
  {name: 'apple', key: 'category_food/apple'},
  {name: 'carrot', key: 'category_food/carrot'},
  {name: 'cupcake', key: 'category_food/cupcake'},
  {name: 'mushroom', key: 'category_food/mushroom_red'},
  {name: 'watermelon', key: 'category_food/sliced_watermelon'},
  {name: 'gold coin', key: 'category_gameplay/coin_gold'},
  {name: 'silver coin', key: 'category_gameplay/coin_silver'},
  {name: 'target', key: 'category_gameplay/target_red3_outline'},
  {name: 'cactus', key: 'category_obstacles/cactus'},
  {name: 'wheat', key: 'category_obstacles/wheat'},
  {name: 'soap', key: 'category_generic_items/soap'},
  {name: 'cave', key: 'category_backgrounds/background_cave'},
  {name: 'court', key: 'category_backgrounds/background_court'},
  {name: 'desert', key: 'category_backgrounds/background_desert'},
  {name: 'grid', key: 'category_backgrounds/background_grid'},
  {name: 'rainbow', key: 'category_backgrounds/background_rainbow'},
  {name: 'sci_fi', key: 'category_backgrounds/background_scifi'},
  {name: 'space', key: 'category_backgrounds/background_space'},
  {name: 'underwater', key: 'category_backgrounds/background_underwater'},
  {name: 'city', key: 'category_backgrounds/city'},
  {name: 'floating_grass', key: 'category_backgrounds/floating_grass'},
  {name: 'living_room', key: 'category_backgrounds/living_room'},
  {name: 'stage', key: 'category_backgrounds/stage'}
]

SPRITE_LAB_ANIMATION_LIST = [
  'category_animals/bear',
  'category_animals/bear_with_fish',
  'category_animals/bee',
  'category_animals/brown_cat',
  'category_animals/brown_dog',
  'category_animals/bunny1_hurt',
  'category_animals/bunny1_jump',
  'category_animals/bunny1_ready',
  'category_animals/bunny2',
  'category_animals/chick',
  'category_animals/corgi',
  'category_animals/cow',
  'category_animals/crab',
  'category_animals/dalmatian',
  'category_animals/elephant',
  'category_animals/elephant2',
  'category_animals/elephant_happy',
  'category_animals/elk',
  'category_animals/fish',
  'category_animals/fish_blue',
  'category_animals/fish_brown',
  'category_animals/fish_green',
  'category_animals/fish_pink',
  'category_animals/fish_silver',
  'category_animals/fly',
  'category_animals/giraffe_tall',
  'category_animals/hippo_gray',
  'category_animals/kangaroo',
  'category_animals/ladybug',
  'category_animals/mouse',
  'category_animals/mouse_gray',
  'category_animals/orange_cat',
  'category_animals/pig',
  'category_animals/pig_pink',
  'category_animals/polar_bear',
  'category_animals/pterodactyl',
  'category_animals/snail',
  'category_animals/turtle',
  'category_animals/tyrannosaurus',
  'category_animals/zebra',
  'category_backgrounds/background_cave',
  'category_backgrounds/background_court',
  'category_backgrounds/background_rainbow',
  'category_backgrounds/background_santa',
  'category_backgrounds/background_desert',
  'category_backgrounds/background_scifi',
  'category_backgrounds/background_space',
  'category_backgrounds/background_grid',
  'category_backgrounds/background_underwater',
  'category_backgrounds/city',
  'category_backgrounds/desert_road',
  'category_backgrounds/background_winter',
  'category_backgrounds/continuous_grass',
  'category_backgrounds/farm_land',
  'category_backgrounds/desk',
  'category_backgrounds/floating_grass',
  'category_backgrounds/front_of_house',
  'category_backgrounds/meadow',
  'category_backgrounds/kitchen',
  'category_backgrounds/pine_trees',
  'category_backgrounds/living_room',
  'category_backgrounds/park_view',
  'category_backgrounds/soccer_field',
  'category_backgrounds/stage',
  'category_backgrounds/sun_and_rainbow',
  'category_backgrounds/subway',
  'category_backgrounds/tree_island',
  'category_backgrounds/tennis_court',
  'category_backgrounds/sunshine_showers',
  'category_backgrounds/underground',
  'category_backgrounds/abstract_08',
  'category_backgrounds/abstract_15',
  'category_backgrounds/abstract_16',
  'category_backgrounds/abstract_21',
  'category_backgrounds/abstract_26',
  'category_backgrounds/abstract_31',
  'category_backgrounds/background_landscape_01',
  'category_backgrounds/background_landscape_02',
  'category_backgrounds/background_landscape_03',
  'category_backgrounds/background_landscape_04',
  'category_backgrounds/background_landscape_05',
  'category_backgrounds/background_landscape_06',
  'category_backgrounds/background_landscape_07',
  'category_backgrounds/background_landscape_08',
  'category_backgrounds/background_landscape_09',
  'category_backgrounds/background_landscape_10',
  'category_backgrounds/background_landscape_11',
  'category_backgrounds/background_landscape_16',
  'category_backgrounds/background_landscape_21',
  'category_backgrounds/background_landscape_26',
  'category_backgrounds/background_landscape_27',
  'category_backgrounds/background_landscape_28',
  'category_backgrounds/background_underwater_02',
  'category_backgrounds/background_underwater_05',
  'category_backgrounds/background_underwater_07',
  'category_backgrounds/background_underwater_11',
  'category_backgrounds/background_underwater_13',
  'category_backgrounds/background_underwater_17',
  'category_backgrounds/gradient_01',
  'category_backgrounds/gradient_02',
  'category_backgrounds/gradient_08',
  'category_backgrounds/gradient_09',
  'category_backgrounds/gradient_11',
  'category_backgrounds/gradient_12',
  'category_backgrounds/gradient_13',
  'category_backgrounds/gradient_14',
  'category_backgrounds/gradient_15',
  'category_backgrounds/gradient_16',
  'category_backgrounds/gradient_17',
  'category_backgrounds/gradient_18',
  'category_backgrounds/gradient_21',
  'category_backgrounds/gradient_22',
  'category_backgrounds/gradient_23',
  'category_backgrounds/gradient_26',
  'category_backgrounds/gradient_30',
  'category_backgrounds/gradient_33',
  'category_backgrounds/sports_baseball',
  'category_backgrounds/sports_basketball_half2',
  'category_backgrounds/sports_billiards',
  'category_backgrounds/sports_football',
  'category_backgrounds/sports_hockey',
  'category_backgrounds/sports_soccer',
  'category_backgrounds/sports_swimming',
  'category_backgrounds/sports_tennis',
  'category_backgrounds/sports_tennis2',
  'category_backgrounds/sports_track',
  'category_backgrounds/sports_volleyball',
  'category_backgrounds/texture_01',
  'category_backgrounds/texture_02',
  'category_backgrounds/texture_03',
  'category_backgrounds/texture_04',
  'category_backgrounds/texture_05',
  'category_backgrounds/texture_06',
  'category_backgrounds/texture_07',
  'category_backgrounds/texture_08',
  'category_backgrounds/texture_11',
  'category_backgrounds/texture_12',
  'category_backgrounds/texture_13',
  'category_backgrounds/texture_14',
  'category_backgrounds/texture_15',
  'category_backgrounds/texture_16',
  'category_backgrounds/texture_17',
  'category_backgrounds/texture_19',
  'category_backgrounds/texture_21',
  'category_backgrounds/texture_23',
  'category_backgrounds/texture_29',
  'category_characters/alienBeige',
  'category_characters/alienBlue',
  'category_characters/alienGreen',
  'category_characters/alienPink',
  'category_characters/alienYellow',
  'category_characters/baby_robot',
  'category_characters/blue_creature',
  'category_characters/bubble',
  'category_characters/crowned_creature',
  'category_characters/floating_alien',
  'category_characters/fly_bot',
  'category_characters/ghost',
  'category_characters/green_monster',
  'category_characters/happy_critter',
  'category_characters/kid_1',
  'category_characters/kid_10',
  'category_characters/kid_11',
  'category_characters/kid_11_side',
  'category_characters/kid_12',
  'category_characters/kid_12_side',
  'category_characters/kid_13',
  'category_characters/kid_14',
  'category_characters/kid_14_side',
  'category_characters/kid_15',
  'category_characters/kid_15_side',
  'category_characters/kid_15_walking',
  'category_characters/kid_16',
  'category_characters/kid_16_walking',
  'category_characters/kid_16_waving',
  'category_characters/kid_17',
  'category_characters/kid_18',
  'category_characters/kid_19',
  'category_characters/kid_19_side',
  'category_characters/kid_1_side',
  'category_characters/kid_2',
  'category_characters/kid_20',
  'category_characters/kid_21',
  'category_characters/kid_22',
  'category_characters/kid_22_side',
  'category_characters/kid_23',
  'category_characters/kid_24',
  'category_characters/kid_25',
  'category_characters/kid_26',
  'category_characters/kid_26_side',
  'category_characters/kid_27',
  'category_characters/kid_27_side',
  'category_characters/kid_28',
  'category_characters/kid_29',
  'category_characters/kid_2_right',
  'category_characters/kid_2_walking',
  'category_characters/kid_3',
  'category_characters/kid_30',
  'category_characters/kid_30_side',
  'category_characters/kid_31',
  'category_characters/kid_32',
  'category_characters/kid_33',
  'category_characters/kid_34',
  'category_characters/kid_34_excited',
  'category_characters/kid_34_side',
  'category_characters/kid_35',
  'category_characters/kid_36',
  'category_characters/kid_36_side',
  'category_characters/kid_37',
  'category_characters/kid_38',
  'category_characters/kid_39',
  'category_characters/kid_39_side',
  'category_characters/kid_4',
  'category_characters/kid_40',
  'category_characters/kid_41',
  'category_characters/kid_42',
  'category_characters/kid_42_side',
  'category_characters/kid_43_sitting',
  'category_characters/kid_44_suit',
  'category_characters/kid_45_suit',
  'category_characters/kid_46',
  'category_characters/kid_46_left',
  'category_characters/kid_46_side',
  'category_characters/kid_4_side',
  'category_characters/kid_6',
  'category_characters/kid_6_sitting',
  'category_characters/kid_7',
  'category_characters/kid_8',
  'category_characters/kid_9',
  'category_characters/kid_at_desk',
  'category_characters/kid_outline',
  'category_characters/kid_outline_side',
  'category_characters/monster_in_case',
  'category_characters/orange_monster',
  'category_characters/pink_monster',
  'category_characters/popsicle_monster',
  'category_characters/purple_monster',
  'category_characters/red_alien',
  'category_characters/spike_bot',
  'category_characters/spring_bot',
  'category_characters/sun',
  'category_characters/sun2',
  'category_characters/wing_bot',
  'category_environment/cloud',
  'category_environment/rock',
  'category_environment/sun',
  'category_food/apple',
  'category_food/bannana',
  'category_food/beet',
  'category_food/bread',
  'category_food/burger',
  'category_food/carrot',
  'category_food/carrot_gold',
  'category_food/carrots',
  'category_food/cherry',
  'category_food/cracked_egg',
  'category_food/cucumber',
  'category_food/cupcake',
  'category_food/eggplant',
  'category_food/fish_cooked',
  'category_food/fries',
  'category_food/grapes',
  'category_food/ice_cream',
  'category_food/juice_box',
  'category_food/lemon',
  'category_food/lime',
  'category_food/mushroom_brown',
  'category_food/mushroom_red',
  'category_food/mushroom_tan',
  'category_food/onion',
  'category_food/orange',
  'category_food/pear',
  'category_food/pepper',
  'category_food/pizza_slice',
  'category_food/radish',
  'category_food/red_apple',
  'category_food/sliced_watermelon',
  'category_food/soda',
  'category_food/stew',
  'category_food/watermelon',
  'category_gameplay/coin_bronze',
  'category_gameplay/coin_gold',
  'category_gameplay/coin_silver',
  'category_gameplay/flatDark41',
  'category_gameplay/flatDark42',
  'category_gameplay/flatDark43',
  'category_gameplay/flat_medal1',
  'category_gameplay/flat_medal2',
  'category_gameplay/flat_medal3',
  'category_gameplay/flat_medal4',
  'category_gameplay/flat_medal5',
  'category_gameplay/flat_medal6',
  'category_gameplay/flat_medal7',
  'category_gameplay/flat_medal8',
  'category_gameplay/flat_medal9',
  'category_gameplay/medalBronze',
  'category_gameplay/medalGold',
  'category_gameplay/medalSilver',
  'category_gameplay/target_red3_outline',
  'category_gameplay/textGameOver',
  'category_gameplay/textGetReady',
  'category_gameplay/ufoBlue',
  'category_gameplay/ufoGreen',
  'category_gameplay/ufoRed',
  'category_gameplay/ufoYellow',
  'category_generic_items/bandage',
  'category_generic_items/beaker',
  'category_generic_items/bell',
  'category_generic_items/blender',
  'category_generic_items/bone',
  'category_generic_items/book',
  'category_generic_items/bowl',
  'category_generic_items/briefcase',
  'category_generic_items/camera',
  'category_generic_items/clip_pen',
  'category_generic_items/clipboard',
  'category_generic_items/coffee',
  'category_generic_items/compass',
  'category_generic_items/computer_monitor',
  'category_generic_items/first_aid',
  'category_generic_items/flask',
  'category_generic_items/flip_phone',
  'category_generic_items/fork',
  'category_generic_items/game_controller',
  'category_generic_items/headphones',
  'category_generic_items/joy_stick',
  'category_generic_items/key',
  'category_generic_items/keys',
  'category_generic_items/laptop',
  'category_generic_items/laptop_facing_away',
  'category_generic_items/large_paint_brush',
  'category_generic_items/microphone',
  'category_generic_items/microscope',
  'category_generic_items/mitt',
  'category_generic_items/mixer',
  'category_generic_items/money',
  'category_generic_items/nail',
  'category_generic_items/open_book',
  'category_generic_items/paint_brush',
  'category_generic_items/paint_brush_blue',
  'category_generic_items/paint_pallette',
  'category_generic_items/pan',
  'category_generic_items/pen',
  'category_generic_items/pencil',
  'category_generic_items/pepper',
  'category_generic_items/pick',
  'category_generic_items/pot',
  'category_generic_items/power_drill',
  'category_generic_items/purse',
  'category_generic_items/roller',
  'category_generic_items/salt',
  'category_generic_items/saw',
  'category_generic_items/screw',
  'category_generic_items/screwdriver',
  'category_generic_items/shovel',
  'category_generic_items/soap',
  'category_generic_items/spatula',
  'category_generic_items/steering_wheel',
  'category_generic_items/suitcase',
  'category_generic_items/tablet',
  'category_generic_items/teapot',
  'category_generic_items/test_tubes',
  'category_generic_items/toothbrush',
  'category_generic_items/trowel',
  'category_generic_items/video_game_controller',
  'category_generic_items/water_glass',
  'category_generic_items/wide_screen_monitor',
  'category_generic_items/wrench',
  'category_generic_items/wrench_simple',
  'category_obstacles/cactus',
  'category_obstacles/ore_coal',
  'category_obstacles/ore_diamond',
  'category_obstacles/ore_emerald',
  'category_obstacles/ore_gold',
  'category_obstacles/ore_iron',
  'category_obstacles/ore_ironAlt',
  'category_obstacles/ore_ruby',
  'category_obstacles/ore_silver',
  'category_obstacles/rock',
  'category_obstacles/wheat',
  'category_tools/beaker',
  'category_tools/blender',
  'category_tools/bowl',
  'category_tools/large_paint_brush',
  'category_tools/microphone',
  'category_tools/microscope',
  'category_tools/mixer',
  'category_tools/nail',
  'category_tools/paint_brush',
  'category_tools/pen',
  'category_tools/pencil',
  'category_tools/pick',
  'category_tools/power_drill',
  'category_tools/roller',
  'category_tools/saw',
  'category_tools/screw',
  'category_tools/screwdriver',
  'category_tools/spatula',
  'category_tools/test_tubes',
  'category_tools/toothbrush',
  'category_tools/trowel',
  'category_tools/wrench',
  'category_tools/wrench_simple',
  'category_vehicles/boat',
  'category_vehicles/car_black',
  'category_vehicles/car_blue',
  'category_vehicles/car_green',
  'category_vehicles/car_red',
  'category_vehicles/car_yellow',
  'category_vehicles/cars',
  'category_vehicles/enemyBlack1',
  'category_vehicles/enemyBlack2',
  'category_vehicles/enemyBlack3',
  'category_vehicles/enemyBlack4',
  'category_vehicles/enemyBlack5',
  'category_vehicles/enemyBlue1',
  'category_vehicles/enemyBlue2',
  'category_vehicles/enemyBlue3',
  'category_vehicles/enemyBlue4',
  'category_vehicles/enemyBlue5',
  'category_vehicles/enemyGreen1',
  'category_vehicles/enemyGreen2',
  'category_vehicles/enemyGreen3',
  'category_vehicles/enemyGreen4',
  'category_vehicles/enemyGreen5',
  'category_vehicles/enemyRed1',
  'category_vehicles/enemyRed2',
  'category_vehicles/enemyRed3',
  'category_vehicles/enemyRed4',
  'category_vehicles/enemyRed5',
  'category_vehicles/jetpack',
  'category_vehicles/minecart',
  'category_vehicles/motorcycle',
  'category_vehicles/planeBlue1',
  'category_vehicles/planeGreen1',
  'category_vehicles/planeRed1',
  'category_vehicles/planeYellow1',
  'category_vehicles/playerShip1_blue',
  'category_vehicles/playerShip1_green',
  'category_vehicles/playerShip1_orange',
  'category_vehicles/playerShip1_red',
  'category_vehicles/playerShip2_blue',
  'category_vehicles/playerShip2_green',
  'category_vehicles/playerShip2_orange',
  'category_vehicles/playerShip2_red',
  'category_vehicles/playerShip3_blue',
  'category_vehicles/playerShip3_green',
  'category_vehicles/playerShip3_orange',
  'category_vehicles/playerShip3_red'
]
