// Public API for @code-dot-org/teacher-dashboard/redux.
//
// Re-exports the Redux slice (reducer + actions + thunks), selectors, types,
// section-order utilities, and demo-student secret helpers.

export {
  default as teacherSectionsReducer,
  // Actions
  beginCreatingSection,
  beginEditingSection,
  cancelEditingSection,
  cancelImportRosterFlow,
  editSectionProperties,
  finishLoadingSectionData,
  removeSection,
  rosterImportFailed,
  selectSection,
  setAuthProviders,
  setCoteacherInvite,
  setCoteacherInviteForPl,
  setCourseOfferings,
  setDemoPresets,
  setDemoPresetsLoaded,
  startDemoSectionCreation,
  finishDemoSectionCreation,
  setPageType,
  setRosterProvider,
  setRosterProviderName,
  setSectionCodeReviewExpiresAt,
  setSections,
  setStudentsForCurrentSection,
  setAvailableParticipantTypes,
  startLoadingSectionData,
  updateSectionAiChatAccessLevel,
  updateSelectedSection,
  sectionHasNewData,
  sectionDoesNotHaveNewData,
  archiveAllSections,
  setSectionOrder,
  setAsyncLoad,
  // Thunks
  toggleSectionHidden,
  finishEditingSection,
  removeSectionOrThrow,
  asyncLoadTeacherHomepageSectionData,
  fetchDemoPresets,
  createDemoSection,
  asyncLoadSectionData,
  asyncLoadCoteacherInvite,
  assignToSection,
  unassignSection,
  beginImportRosterFlow,
  beginGoogleImportRosterFlow,
  importOrUpdateRoster,
  // Constants
  NO_SECTION,
  SELECT_SECTION,
  pageTypes,
  __testInterface__,
  // Types
  DemoSectionCreationError,
} from './teacherSectionsRedux';

export type {TeacherSectionState} from './teacherSectionsRedux';

export {
  USER_EDITABLE_SECTION_PROPS,
  getRoot,
  isRosterDialogOpen,
  rosterProvider,
  rosterProviderName,
  DEMO_SECTION_CODE_PLACEHOLDER,
  sectionCode,
  isDemoSection,
  sectionName,
  ltiSyncResult,
  syncEnabled,
  sectionUnitName,
  selectedSectionSelector,
  sectionProvider,
  sectionProviderName,
  isSectionProviderManaged,
  isSaveInProgress,
  assignedCourseOffering,
  getVisibleSections,
  getSectionRows,
  getAssignmentName,
  sectionFromServerSection,
  studentFromServerStudent,
  serverSectionFromSection,
  newSectionData,
  assignmentNames,
  assignmentPaths,
  isAddingSection,
  sectionsNameAndId,
  sectionsForDropdown,
  sortedSectionsList,
  sortSectionsList,
  hiddenSectionIds,
  hiddenStudentSectionIds,
  hiddenPlSectionIds,
  studentShape,
} from './teacherSectionsReduxSelectors';

export {
  getOrderedSectionIds,
  getFilteredSectionOrderIds,
  saveSectionOrder,
} from './sectionOrderUtils';

export {
  DEMO_SECRET_WORDS,
  DEMO_SECRET_PICTURE_URLS,
  DEMO_SECRET_PICTURE_NAMES,
  demoSecretWordsFor,
  demoSecretPictureUrlFor,
  demoSecretPictureNameFor,
} from './demoStudentSecrets';

export type {
  Section,
  DemoType,
  DemoPresetView,
  DemoPresetUnit,
  DemoPresetCourse,
  ReviewSyllabusQuizOption,
  UserEditableSection,
  OAuthSectionTypeName,
  ServerOAuthSectionTypeName,
  ServerSection,
  ServerDemoPresetView,
  Student,
  ServerStudent,
  CourseOffering,
  CourseVersion,
  SectionInstructor,
  Classroom,
  LtiSectionSyncResult,
  SectionMap,
  AssignmentCourseOffering,
} from './types/teacherSectionTypes';
