/** @file Metadata for stock animation library animations */
export default [
  {
    name: 'asterisk_circle',
    sourceUrl: '/blockly/media/gamelab/library/asterisk_circle.png',
    sourceSize: {x:396, y: 378},
    frameSize: {x:132, y: 126},
    frameCount: 9,
    looping: true,
    frameDelay: 2,
  },
  {
    name: 'asterisk_explode',
    sourceUrl: '/blockly/media/gamelab/library/asterisk_explode.png',
    sourceSize: {x:684, y: 474},
    frameSize: {x:171, y: 158},
    frameCount: 11,
    looping: true,
    frameDelay: 2,
  },
  {
    name: 'asterisk_normal',
    sourceUrl: '/blockly/media/gamelab/library/asterisk_normal.png',
    sourceSize: {x:396, y: 126},
    frameSize: {x:132, y: 126},
    frameCount: 3,
    looping: true,
    frameDelay: 2,
  },
  {
    name: 'asterisk_stretching',
    sourceUrl: '/blockly/media/gamelab/library/asterisk_stretching.png',
    sourceSize: {x:432, y: 432},
    frameSize: {x:144, y: 144},
    frameCount: 8,
    looping: true,
    frameDelay: 2,
  },
  {
    name: 'box',
    sourceUrl: '/blockly/media/gamelab/library/box.png',
    sourceSize: {x:198, y: 118},
    frameSize: {x:66, y: 118},
    frameCount: 3,
    looping: true,
    frameDelay: 2,
  },
  {
    name: 'bubbly',
    sourceUrl: '/blockly/media/gamelab/library/bubbly.png',
    sourceSize: {x:82, y: 520},
    frameSize: {x:82, y: 130},
    frameCount: 4,
    looping: true,
    frameDelay: 4,
  },
  {
    name: 'ghost_standing',
    sourceUrl: '/blockly/media/gamelab/library/ghost_standing.png',
    sourceSize: {x:504, y: 158},
    frameSize: {x:72, y: 158},
    frameCount: 7,
    looping: true,
    frameDelay: 2,
  },
  {
    name: 'platform',
    sourceUrl: '/blockly/media/gamelab/library/platform.png',
    sourceSize: {x:200, y: 219},
    frameSize: {x:200, y: 73},
    frameCount: 3,
    looping: true,
    frameDelay: 2,
  }
];
