name: "Run Marketing UI Tests"
description: "Runs the marketing UI tests"

inputs:
  CONTENTFUL_SPACE_ID:
    description: "Contentful Space ID"
    required: true
  DRAFT_MODE_TOKEN:
    description: "Marketing App Draft Mode Token"
    required: true
  APPLITOOLS_API_KEY:
    description: "Applitools API Key"
    required: true
  APPLICATION_BASE_ADDRESS:
    description: "The base URL for the application. Defaults to http://code.marketing-sites.localhost:3001"
    default: "code.marketing-sites.localhost:3001"
  ENVIRONMENT_TYPE:
    description: "local, pr, test, or production"
    required: true
  GITHUB_ENVIRONMENT_NAME:
    description: "The name of the GitHub environment to use for this action"
    required: false
  BRANCHED_TESTING_ENABLED:
    description: "Whether branched testing is enabled. Defaults to false"
    default: "false"
    required: false
  PR_HEAD_REF:
    description: "The head ref of the pull request."
    required: false

runs:
  using: composite

  steps:
    - name: Install Playwright
      shell: bash
      run: yarn playwright install --with-deps
      working-directory: ./frontend/apps/marketing

    - name: Prepare UI Test Environment
      shell: bash
      working-directory: ./frontend/apps/marketing
      run: |
        echo "APPLITOOLS_API_KEY=${{ inputs.APPLITOOLS_API_KEY }}
        DRAFT_MODE_TOKEN=${{ inputs.DRAFT_MODE_TOKEN }}" >> .env

    - name: UI Tests
      shell: bash
      env:
        STAGE: ${{ inputs.ENVIRONMENT_TYPE }}
        NEXT_PUBLIC_STAGE: ${{ inputs.ENVIRONMENT_TYPE }}
        APPLICATION_BASE_ADDRESS: ${{ inputs.APPLICATION_BASE_ADDRESS }}
        BRANCHED_TESTING_ENABLED: ${{ inputs.BRANCHED_TESTING_ENABLED }}
        PR_HEAD_REF: ${{ inputs.PR_HEAD_REF }}
      run: yarn workspace @code-dot-org/marketing test:ui:ci
      working-directory: ./frontend

    - name: Upload Playwright reports
      if: failure()
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: frontend/apps/marketing/playwright-report
        name: playwright-report

    - name: Run Google Lighthouse Audits
      uses: treosh/lighthouse-ci-action@9917efea514615fb2ff2890f5b8be2d51e703b6e
      env:
        HTTP_PROTOCOL: ${{ inputs.APPLICATION_BASE_ADDRESS == 'code.marketing-sites.localhost:3001' && 'http' || 'https' }}
      with:
        urls: ${{ env.HTTP_PROTOCOL }}://${{ inputs.APPLICATION_BASE_ADDRESS }}/en-US/engineering/all-the-things
        uploadArtifacts: true
        temporaryPublicStorage: true
        configPath: "./frontend/apps/marketing/.lighthouserc.js"
        artifactName: "lighthouse-report-${{ inputs.GITHUB_ENVIRONMENT_NAME || 'local' }}"
