family_name 'csd1'

hideable_lessons true
project_widget_visible true
student_detail_progress_view true
lesson_extras_available true
has_verified_resources true
has_lesson_plan true
is_stable true
tts true
project_sharing true
is_course true

peer_reviews_to_complete 1
curriculum_path 'fake_curriculum_path'
version_year '2020'
pilot_experiment 'fake-pilot-experiment'
editor_experiment 'fake-editor-experiment'
curriculum_umbrella 'CSF'
professional_learning_course 'Exploring Computer Science PD Course'
supported_locales ["de-DE"]
project_widget_types ["gamelab", "weblab"]
teacher_resources [["Lesson Plans", "https://curriculum.code.org/csf-18/coursea/"], ["Teacher Forum", "http://forum.code.org/c/csf"], ["Vocabulary", "https://curriculum.code.org/csf-18/coursea/vocab/"], ["Standard Mappings", "https://curriculum.code.org/csf-18/coursea/standards/"]]
script_announcements [{"notice"=>"This Online PD Resource is no longer available", "details"=>"Click \"Learn More\" to find out about the new Online PD Resources.", "link"=>"https://studio.code.org/s/k5-onlinepd-2019", "type"=>"failure", "visibility"=>"Teacher and student"}]
