from enum import Enum

class NeighborhoodSignalKey(Enum):
  INITIALIZE_PAINTER = "INITIALIZE_PAINTER"
  MOVE = "MOVE"
  PAINT = "PAINT"
  REMOVE_PAINT = "REMOVE_PAINT"
  TAKE_PAINT = "TAKE_PAINT"
  HIDE_PAINTER = "HIDE_PAINTER"
  SHOW_PAINTER = "SHOW_PAINTER"
  TURN_LEFT = "TURN_LEFT"
  HIDE_BUCKETS = "HIDE_BUCKETS"
  SHOW_BUCKETS = "SHOW_BUCKETS"
  IS_ON_BUCKET = "IS_ON_BUCKET"
  IS_ON_PAINT = "IS_ON_PAINT"
  CAN_MOVE = "CAN_MOVE"
