apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.systemResources.secretStore.name }}
  namespace: {{ .Values.systemResources.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.systemResources.secretStore.awsRegion | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.systemResources.secretStore.serviceAccountName }}
