const DISPLAY_NAME_SESSION_KEY = 'displayName';
const USER_AGE_SESSION_KEY = 'userAge';
const IS_PARENT_SESSION_KEY = 'userIsParent';
const PARENT_EMAIL_SESSION_KEY = 'userParentEmail';
const PARENT_EMAIL_OPT_IN_SESSION_KEY = 'userParentEmailOptIn';
const USER_STATE_SESSION_KEY = 'userState';
const USER_GENDER_SESSION_KEY = 'userGender';
const EMAIL_OPT_IN_SESSION_KEY = 'emailOptIn';
const SCHOOL_ID_SESSION_KEY = 'schoolId';
const SCHOOL_ZIP_SESSION_KEY = 'schoolZip';
const SCHOOL_NAME_SESSION_KEY = 'schoolName';

export {
  DISPLAY_NAME_SESSION_KEY,
  USER_AGE_SESSION_KEY,
  IS_PARENT_SESSION_KEY,
  PARENT_EMAIL_SESSION_KEY,
  PARENT_EMAIL_OPT_IN_SESSION_KEY,
  USER_STATE_SESSION_KEY,
  USER_GENDER_SESSION_KEY,
  EMAIL_OPT_IN_SESSION_KEY,
  SCHOOL_ID_SESSION_KEY,
  SCHOOL_ZIP_SESSION_KEY,
  SCHOOL_NAME_SESSION_KEY,
};
