#!/usr/bin/env ruby
# Delete scripts from the database that do not have a .script file

require_relative '../../config/environment'

Script.transaction do # throw this all in a transaction so we roll it back if something unexpected happens
  file_scripts = Dir.glob('config/scripts/**/*.script').sort.flatten.map do |script|
    File.basename(script, '.script')
  end.map(&:downcase)

  orphans = Script.all.select do |script|
    !file_scripts.include?(script.name.downcase)
  end

  puts "deleting scripts: #{orphans.collect(&:name)}"

  puts "and their UserScripts:"
  orphans.map do |script|
    uss = UserScript.where(script_id: script.id)
    puts "#{script.name}: #{uss.count}"
    uss.destroy_all
  end

  orphans.each(&:destroy)
  raise "run '#{$0} confirm' if you actually want this to happen" unless ARGV[0] && ARGV[0] == 'confirm'
end
