#!/usr/bin/env ruby
# Find extra .level files for dsl defined levels
require_relative '../../config/environment'

DSL_TYPES = %w(TextMatch ContractMatch External Match Multi)
DSL_TYPES.map(&:constantize).each do |c|
  c.all.each do |level|
    # these should be dsl levels and should not have .level files
    level_file = LevelLoader.level_file_path(level.name)
    if File.exist? level_file
      puts `ls -l '#{level_file}'`
      # puts "#{level.name}:\n\t#{level_file}\n\t#{level.file_path}"
    end
  end
end
