#!/usr/bin/env ruby
# Find and remove extra .level files for dsl defined levels
require_relative '../../config/environment'

DSL_TYPES = %w(TextMatch ContractMatch External Match Multi).freeze
DSL_TYPES.map(&:constantize).each do |c|
  c.all.each do |level|
    # these should be dsl levels and should not have .level files
    level_file = Policies::LevelFiles.level_file_path(level)
    if File.exist? level_file
      puts `ls -l '#{level_file}'`
      puts `git rm '#{level_file}'`
    end
  end
end
