#!/usr/bin/env ruby
# fix users that have secret_words = "#<SecretWord>" because of my dumb bug

require_relative '../../config/environment'

User.where('secret_words like "#%"').find_each do |user|
  user.generate_secret_words
  user.save(validate: false) # in case there's something wrong with the user
end
