#!/usr/bin/env ruby
# Initialize everyone's secret picture and secret word

require_relative '../../config/environment'

User.find_each do |user|
  user.reset_secret_picture unless user.secret_picture
  user.reset_secret_words unless user.secret_words
end
