#!/usr/bin/env ruby
require_relative '../../config/environment'

# invalidate level_source_images by breaking the md5. Future solutions
# will now create a new LevelSource because it can't find the existing
# one.

# Some bad level_source_images may have been created before this bug
# was fixed:
# https://github.com/code-dot-org/code-dot-org/commit/1db0dfffb2c1a3634d467b67138b31eb3de257b9
# we want to change the urls (eg: http://studio.code.org/sh/47434474/)
# by generating a new level source id (instead of just fixing the
# image) because facebook hangs on to images in the cache for too
# long.

LevelSource.where(level_id: Script.find_by_name('frozen').level_ids).
  where('created_at < ?', '2014-11-20').each do |level_source|
  new_md5 = ("invalid-" + level_source.md5).slice(0..31)
  level_source.update_attribute(:md5, new_md5)
end
