#!/usr/bin/env ruby
# This speeds up conversion but won't get the stage names right

raise 'Sample usage: ruby yml-to-script.rb ../../config/scripts/default/script.yml' unless ARGV[0]

lines = File.open(ARGV[0]).read.split("\n")
prev_game = nil
lines[3..-1].each do |line|
  tokens = line.strip.split "\t"
  game = tokens[0]
  if prev_game != game
    puts
    puts game
    prev_game = game
  end
  puts "skin '#{tokens[3]}'" unless tokens[3].empty?
  puts %Q-concepts '#{tokens[4].split(',').map(&:strip).join("', '")}'- unless tokens[4].nil? || tokens[4].empty?
  puts "level 'blockly:#{game}:#{tokens[2]}'"
end
