apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/dashboard-job-setup-db
patches:
  - path: job-root.patch.yaml
labels:
  - pairs:
      app.kubernetes.io/name: cdo
      app.kubernetes.io/instance: cdo
    includeSelectors: true
    includeTemplates: true
