apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.systemResources.externalSecret.name }}
  namespace: {{ .Values.systemResources.namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.systemResources.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.systemResources.externalSecret.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          kargo.akuity.io/cred-type: generic
  data:
    - secretKey: secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.systemResources.externalSecret.awsSecretName | quote }}
        metadataPolicy: None
