apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - service.yaml
  - pod.yaml
secretGenerator:
  - name: cdo-local-secrets
    behavior: merge
    type: Opaque
    envs:
      - cdo-local-secret-redis.secret.env
