apiVersion: v1
kind: Pod
metadata:
  name: cdo-redis
  labels:
    app.kubernetes.io/component: redis
spec:
  containers:
    - name: redis
      image: redis:7.4
      args:
        - redis-server
        - --requirepass
        - $(REDIS_PASSWORD)
      env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cdo-local-secrets
              key: _redis_password
      ports:
        - containerPort: 6379
