#!/bin/sh
ruby tools/hooks/lint.rb &&
  ruby tools/hooks/scary_changes.rb &&
  ruby tools/hooks/restrict_levelbuilder_changes.rb &&
  ruby tools/hooks/restrict_staging_changes.rb &&
  ruby tools/hooks/restrict_large_files.rb
