---
driver:
  name: dokken
  chef_version: latest
  seccomp: unconfined
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - /var/run/docker.sock:/var/run/docker.sock
  cap_add:
  - SYS_ADMIN
  - NET_ADMIN
  tmpfs:
  - /run
  - /run/lock
transport:
  name: dokken
provisioner:
  name: dokken
verifier:
  name: inspec
platforms:
  - name: ubuntu-14.04
    attributes:
      cdo-pmm:
        server:
          port: 80
          port_forward: null
          network_mode: dokken
          host: pmm_server
    driver:
      image: dokken/ubuntu-14.04
      pid_one_command: /sbin/init
    run_list:
      - recipe[apt]
suites:
  - name: default
    run_list:
      - recipe[pmm_test]
