export enum IframeMessageType {
  IFRAME_READY = 'IFRAME_READY',
  CHANGE_FILE_HREF = 'CHANGE_FILE_HREF',
  CHANGE_FILE_URL_BAR = 'CHANGE_FILE_URL_BAR',
  SET_SOURCE = 'SET_SOURCE',
  FILE_UPDATED = 'FILE_UPDATED',
  SET_ALLOW_SCRIPTS = 'SET_ALLOW_SCRIPTS',
  REFRESH = 'REFRESH',
}

export const DEFAULT_START_HTML_FILE = 'index.html';
