export enum IframeMessageType {
  IFRAME_READY = 'IFRAME_READY',
  CHANGE_FILE_HREF = 'CHANGE_FILE_HREF',
  CHANGE_FILE_URL_BAR = 'CHANGE_FILE_URL_BAR',
  SET_SOURCE = 'SET_SOURCE',
  FILE_UPDATED = 'FILE_UPDATED',
}
