export enum IframeMessageType {
  IFRAME_READY = 'IFRAME_READY',
  CHANGE_FILE_HREF = 'CHANGE_FILE_HREF',
  CHANGE_FILE_URL_BAR = 'CHANGE_FILE_URL_BAR',
  SET_SOURCE = 'SET_SOURCE',
  FILE_UPDATED = 'FILE_UPDATED',
  SET_ALLOW_SCRIPTS = 'SET_ALLOW_SCRIPTS',
  ADD_FILE_TO_NAVIGATION_HISTORY = 'ADD_FILE_TO_NAVIGATION_HISTORY',
  NAVIGATE_TO_FILE = 'NAVIGATE_TO_FILE',
}

export const DEFAULT_START_HTML_FILE = 'index.html';
