apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/minio-setup-s3-job
labels:
  - pairs:
      app.kubernetes.io/name: cdo
      app.kubernetes.io/instance: cdo
    includeSelectors: true
    includeTemplates: true
