AWSTemplateFormatVersion: 2010-09-09

Description: Knowledge Base and data sources for the AI Differentiation chat feature.

Parameters:  
  Environment:
    Type: String
    Description: "Environment being deployed to (ex: production, test)"

Resources:
  AiDiffKnowledgeBaseWithAoss:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: !Sub ai-diff-${Environment}
      Description: "Embedded lesson plans and supporting documents for contextual differentiation chat with AI Teaching assistant"
      # TODO: define this role in code
      RoleArn: !GetAtt AiDiffKnowledgeBaseRole.Arn
      KnowledgeBaseConfiguration:
        Type: "VECTOR"
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: "arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v2:0"
          EmbeddingModelConfiguration:
            BedrockEmbeddingModelConfiguration:
              Dimensions: 1024
      StorageConfiguration:
        Type: "OPENSEARCH_SERVERLESS"
        OpensearchServerlessConfiguration:
          CollectionArn: !GetAtt AiDiffCollection.Arn
          VectorIndexName: "ai-diff-index"
          FieldMapping:
            VectorField: "ai-diff-vector-field"
            TextField: "text"
            MetadataField: "metadata"
  AiDiffDataSource:
    Type: AWS::Bedrock::DataSource
    Properties:
      KnowledgeBaseId: !Ref AiDiffKnowledgeBaseWithAoss
      Name: "AI_Differentiation_data"
      Description: "Lesson Plans and Supporting documents for code.org lessons"
      DataDeletionPolicy: "RETAIN"
      DataSourceConfiguration:
        Type: "S3"
        S3Configuration:
          BucketArn: !GetAtt AiDiffS3Bucket.Arn
          InclusionPrefixes: ["live/"]
  AiDiffS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub cdo-ai-diff-${Environment}
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: "ExpireOldVersions"
            Status: Enabled
            NoncurrentVersionExpirationInDays: 365
  AiDiffCollection:
    Type: 'AWS::OpenSearchServerless::Collection'
    Properties:
      Name: !Sub ai-diff-${Environment}
      Type: VECTORSEARCH
      Description: AI Differentiation search collection
    DependsOn:
      - EncryptionPolicy
  EncryptionPolicy:
    Type: 'AWS::OpenSearchServerless::SecurityPolicy'
    Properties:
      Name: !Sub ai-diff-${Environment}-encryption-policy
      Type: encryption
      Policy: !Sub |
        {
          "AWSOwnedKey": true,
          "Rules": [
            {
              "ResourceType": "collection",
              "Resource": ["collection/ai-diff-${Environment}"]
            }
          ]
        }
  NetworkPolicy:
    Type: 'AWS::OpenSearchServerless::SecurityPolicy'
    Properties:
      Name: !Sub ai-diff-${Environment}-network-policy
      Type: network
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/ai-diff-${Environment}"]
              }
            ],
            "AllowFromPublic": false,
            "SourceServices": ["bedrock.amazonaws.com"]
          }
        ]
  DataPolicy:
    Type: 'AWS::OpenSearchServerless::AccessPolicy'
    Properties:
      Name: !Sub ai-diff-${Environment}-data-policy
      Type: data
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "index",
                "Resource": [
                  "index/ai-diff-${Environment}/*"
                ],
                "Permission": [
                  "aoss:*",
                  "aoss:UpdateIndex",
                  "aoss:DescribeIndex",
                  "aoss:ReadDocument",
                  "aoss:WriteDocument",
                  "aoss:CreateIndex"
                ]
              },
              {
                "ResourceType": "collection",
                "Resource": [
                  "collection/ai-diff-${Environment}"
                ],
                "Permission": [
                  "aoss:*",
                  "aoss:DescribeCollectionItems",
                  "aoss:CreateCollectionItems",
                  "aoss:UpdateCollectionItems"
                ]
              }
            ],
            "Principal": [
              "${AiDiffKnowledgeBaseRole.Arn}",
              "arn:aws:sts::475661607190:assumed-role/GoogleAdmin/*"
            ]
          }
        ]
  AiDiffKnowledgeBaseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "AiDiffKnowledgeBaseRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "bedrock.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "AiDiffKnowledgeBasePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "aoss:APIAccessAll"
                  - "bedrock:InvokeModel"
                Resource:
                  - !GetAtt AiDiffS3Bucket.Arn
                  - !GetAtt AiDiffCollection.Arn
                  - "arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v2:0"