AWSTemplateFormatVersion: 2010-09-09
Description: DNS records and resources supporting events.code.org.

# This domain is intended to be used for event related mini-sites.
# It is hosted in LeadPages, and the DNS records are managed in Route53.

Resources:
  # The NS Records making this authoritative should be manually added.
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: events.code.org

  RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZone
      RecordSets:
        - Name: events.code.org
          Type: CNAME
          TTL: 300
          ResourceRecords:
            - events.code.org.leadpages.net

# Return outputs
Outputs:
  HostedZoneNameServers:
    Description: The Route53 Hosted Zone Name Servers for events.code.org
    Value: !Join [",", !GetAtt HostedZone.NameServers]
