# TeachAI DNS Configuration
# This template is manually deployed to the 'teachai-dns' stack.

AWSTemplateFormatVersion: 2010-09-09

Description: DNS Records for the teachai.org domain.

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: teachai.org.

  RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZone
      RecordSets:
        - Name: teachai.org.
          Type: A
          TTL: '300'
          ResourceRecords:
            - '141.193.213.10'
            - '141.193.213.11'
        # - Name: teachai.org
        #   Type: A
        #   AliasTarget:
        #     DNSName: 'd1zp22d0hxajlk.cloudfront.net'
        #     HostedZoneId: 'Z2FDTNDATAQYW2'
        - Name: www.teachai.org.
          Type: A
          TTL: '300'
          ResourceRecords:
            - '141.193.213.10'
            - '141.193.213.11'
        # - Name: www.teachai.org.
        #   Type: CNAME
        #   TTL: '300'
        #   ResourceRecords:
        #     - 'd1zp22d0hxajlk.cloudfront.net'
        - Name: teachai.org.
          Type: TXT
          TTL: '3600'
          ResourceRecords:
            - '"google-site-verification=TqkM4Ab7lI1uZRCVMbkTdtVkiQ27k0wPu9bX3wtv_eE"'
            - '"v=spf1 include:_spf.google.com ~all"'
        - Name: 44644295.teachai.org
          Type: CNAME
          TTL: '300'
          ResourceRecords:
            - 'google.com'
        - Name: teachai.org.
          Type: MX
          TTL: '3600'
          ResourceRecords:
            - '1 ASPMX.L.GOOGLE.COM'
            - '5 ALT1.ASPMX.L.GOOGLE.COM'
            - '5 ALT2.ASPMX.L.GOOGLE.COM'
            - '10 ALT3.ASPMX.L.GOOGLE.COM'
            - '10 ALT4.ASPMX.L.GOOGLE.COM'
        - Name: _dmarc.teachai.org
          Type: TXT
          TTL: '3600'
          ResourceRecords:
            - '"v=DMARC1; p=none; rua=mailto:dmarc-reports@teachai.org"'
        - Name: google._domainkey.teachai.org
          Type: TXT
          TTL: '300'
          # Long records must be split into multiple strings.
          ResourceRecords:
            - !Join
              - ''
              - - '"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQ"'
                - '"EAl79vlKp3e0zGlT3DoEi1wuV3+XACdXWDBs3UpfbPAtsXzHeQxCMG4YHy36"'
                - '"OXNB9byEKZhnNAJSVDJQlDXJThKcmnSGo7I05psvnJCN0BZQQEvcM6/H0CYh"'
                - '"qCOcKDWnUSaC87/ocK6Tneo2PuhEK9brGhT0ff99//xfbzqRqJhpOVpqO3V2"'
                - '"BOclehslQkXf8ZBdJ80BHO0L+CXGlQw2ng2Vk6SQvQUCd0ulL6EfElEEO2u9"'
                - '"rclhSABIFa1VVjb1x+ELSYiaoIMqpfn7L56X7nxJlBmJ/diJiGRDyR/gC3k4"'
                - '"vozKRerALdEhCW+8W0HDJakVVK9/XoOMH5CM0eyCo/QwIDAQAB"'
        # Cleverstory ACM Validation
        - Name: _1f6bbc7c7df1384d83352880c06e2f97.teachai.org.teachai.org
          Type: CNAME
          TTL: '300'
          ResourceRecords:
            - '_a6304c18677c27c3d4654147a1dcc1d1.dsmfrbdtqy.acm-validations.aws.'
