{{- range .Values.codeai_cluster_config.frontend_security_group_namespaces }}
---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: frontend-security-group
  namespace: {{ . }}
spec:
  podSelector: {}
  securityGroups:
    groupIds:
      - {{ $.Values.codeai_cluster_config.cluster_primary_security_group_id | quote }}
      - {{ $.Values.codeai_cluster_config.frontend_security_group_id | quote }}
{{- end }}
