{{- range $index, $env := .Values.codeai_cluster_config.single_namespace_environment_types }}
{{- if gt $index 0 }}
---
{{- end }}
{{ include "eso-per-envtype.render" (dict
  "environment_type" $env
  "single_namespace_environment_type" true
  "multi_namespace_regexes" nil
  "iam_role_arn" (index $.Values.codeai_cluster_config.eso_iam_role_arns $env)
  "region" $.Values.codeai_cluster_config.cluster_region
) | trim }}
{{- end }}
