export const projects = {
  applab: [{
    currentGallery: "public",
    projectData: {
      channel: "12345",
      name: "Remix: Test Project",
      publishedAt: "2017-12-13T19:00:00.000+00:00",
      publishedToClass: false,
      publishedToPublic: true,
      studentAgeRange: "13+",
      studentName: "Z",
      thumbnailUrl: "/v3/files-public/fake_thumbnail.png",
      type: "applab",
    },
  }],
  artist: [],
  events: [],
  gamelab: [],
  k1: [],
  minecraft: [{
    currentGallery: "public",
    projectData: {
      channel: "67890",
      name: "My Minecart Project",
      publishedAt: "2017-12-08T10:00:00.000+00:00",
      publishedToClass: true,
      publishedToPublic: true,
      studentAgeRange: "13+",
      studentName: "Y",
      thumbnailUrl: "/v3/files-public/fake_thumbnail.png",
      type: "minecraft",
    },
  }],
  playlab: [],
};
