# Note: EC2 driver with IAM Instance Profile required to run integration test successfully, e.g.:
# IAM_PROFILE_NAME=[IAMProfileName] KITCHEN_LOCAL_YAML=../.kitchen.ec2.yml bundle exec kitchen verify
---
driver:
  name: dokken
  chef_version: 17.6.18
  privileged: true
verifier:
  name: inspec
transport:
  name: dokken
provisioner:
  name: dokken
platforms:
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
    run_list:
      - recipe[apt]
suites:
  - name: default
    run_list:
      - recipe[cdo-cloudwatch-agent]
    attributes:
      cdo-cloudwatch-agent:
