#============================================================
# Create a shared GatewayClass for AWS Load Balancer Controller-backed Gateways.
# Individual services should reference this class instead of creating their own.
#============================================================

apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: {{ .Values.gateway.loadBalancerConfig.name }}
  namespace: {{ .Values.gateway.loadBalancerConfig.namespace }}
spec:
  scheme: {{ .Values.gateway.loadBalancerConfig.scheme | quote }}
  listenerConfigurations:
    - protocolPort: "HTTPS:443"
      defaultCertificate: {{ .Values.gateway.loadBalancerConfig.defaultCertificateArn | quote }}
