# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Dashboard::Application.load_tasks

namespace :dashboard do
  task setup_db: ['db:setup_or_migrate'] do
    # Seeding takes a long time, and adhocs don't need full seeding for most use cases.
    # Developers can ssh to the adhoc and run seeding commands there if they need additional seeded data.
    seed_task = rack_env?(:adhoc) ? 'seed:ui_test' : 'seed:all'
    Rake::Task[seed_task].invoke('trace')
  end
end
