import type {MusicTrackDefinition} from '@/audio/MusicController';
import {
  SpriteSpeed,
  Behavior,
  HIDDEN_VALUE,
  RANDOM_VALUE,
} from '@/levels/studio/constants';
import {assetUrl, skinFor} from '@/levels/studio/skins';

/**
 * Music tracks and associated metadata for both hoc2015 and hoc2015x tutorials.
 * Individual levels don't load all of these, only the subset they request.
 */
export const HOC2015_MUSIC_METADATA: MusicTrackDefinition[] = [
  {name: 'song1', volume: 0.5},
  {name: 'song2', volume: 0.5},
  {name: 'song3', volume: 0.5},
  {name: 'song4', volume: 0.4},
  {name: 'song5', volume: 0.4},
  {name: 'song6', volume: 0.5},
  {name: 'song7', volume: 0.4},
  {name: 'song8', volume: 0.4},
  {name: 'song9', volume: 0.4},
  {name: 'song10', volume: 0.5},
  {name: 'song11', volume: 0.45},
  {name: 'song12', volume: 0.4},
  {name: 'song13', volume: 0.4},
  {name: 'song14', volume: 0.5},
  {name: 'song15', volume: 0.55},
];

const skins = {
  hoc2015: skinFor('hoc2015x', skinUrl => ({
    preloadAssets: true,
    sortDrawOrder: true,
    hideIconInClearPuzzle: true,
    defaultBackground: 'main',
    projectileFrames: 10,
    itemFrames: 10,
    instructions2ImageSubstitutions: {
      pufferpig: assetUrl('instructions_pufferpig.png'),
      mynock: assetUrl('instructions_mynock.png'),
      rebelpilot: assetUrl('instructions_rebelpilot.png'),
      stormtrooper: assetUrl('instructions_stormtrooper.png'),
      mousedroid: assetUrl('instructions_mousedroid.png'),
      tauntaun: assetUrl('instructions_tauntaun.png'),
      probot: assetUrl('instructions_probot.png'),
    },
    explosion: skinUrl('vanish.png'),
    explosionFrames: 17,
    animatedGoal: skinUrl('goal_idle.png'),
    goalSpriteWidth: 100,
    goalSpriteHeight: 100,
    animatedGoalFrames: 16,
    timePerGoalAnimationFrame: 100,
    finishCollideDistanceScaling: 0.8,
    goalCollisionRectWidth: 50,
    goalCollisionRectHeight: 75,
    fadeOutGoal: true,
    goalSuccess: undefined,
    goalRenderOffsetX: -25,
    goalRenderOffsetY: -45,
    projectileSpriteWidth: 70,
    projectileSpriteHeight: 70,
    itemCollisionRectWidth: 50,
    itemCollisionRectHeight: 50,
    spriteCollisionRectWidth: 50,
    spriteCollisionRectHeight: 50,
    wallCollisionRectOffsetX: 0,
    wallCollisionRectOffsetY: 24,
    wallCollisionRectWidth: 30,
    wallCollisionRectHeight: 20,
    gridSpriteRenderOffsetX: -30,
    gridSpriteRenderOffsetY: -40,
    preventProjectileLoop: (name: string) => name === '',
    preventItemLoop: (name: string) => name === '',
    winAvatar: undefined,
    failureAvatar: undefined,
    avatarList: ['r2-d2', 'c-3po'],
    avatars: {
      'r2-d2': {
        sprite: skinUrl('avatar_r2-d2.png'),
        walk: skinUrl('walk_r2-d2.png'),
        dropdownThumbnail: skinUrl('avatar_r2-d2_thumb.png'),
        frameCounts: {
          normal: 14,
          turns: 8,
          emotions: 0,
          walk: 14,
        },
        animations: {
          turns: 8,
        },
        animationFrameDuration: 3,
        movementAudio: [
          {
            begin: 'r2-d2_move1_start',
            loop: 'r2-d2_move1_loop',
            end: 'r2-d2_move1_end',
            volume: 2.2,
          },
          {
            begin: 'r2-d2_move2_start',
            loop: 'r2-d2_move2_loop',
            end: 'r2-d2_move2_end',
            volume: 2.2,
          },
          {
            begin: 'r2-d2_move3_start',
            loop: 'r2-d2_move3_loop',
            end: 'r2-d2_move3_end',
            volume: 2.2,
          },
        ],
      },
      'c-3po': {
        sprite: skinUrl('avatar_c-3po.png'),
        walk: skinUrl('walk_c-3po.png'),
        dropdownThumbnail: skinUrl('avatar_c-3po_thumb.png'),
        frameCounts: {
          normal: 16,
          turns: 8,
          emotions: 0,
          walk: 16,
        },
        animations: {
          turns: 8,
        },
        animationFrameDuration: 3,
        movementAudio: [
          {
            loop: 'c-3po_move_loop',
            end: 'c-3po_move_end',
            volume: 0.6,
          },
        ],
      },
    },

    // NOTE: all class names should be unique.  eventhandler naming won't work
    // if we name a projectile class 'left' for example.
    ProjectileClassNames: [],

    ItemClassNames: [
      'pufferpig',
      'stormtrooper',
      'tauntaun',
      'mynock',
      'probot',
      'mousedroid',
      'rebelpilot',
    ],

    AutohandlerTouchItems: {
      whenTouchPufferPig: 'pufferpig',
      whenTouchStormtrooper: 'stormtrooper',
      whenTouchTauntaun: 'tauntaun',
      whenTouchMynock: 'mynock',
      whenTouchProbot: 'probot',
      whenTouchMouseDroid: 'mousedroid',
      whenTouchRebelPilot: 'rebelpilot',
      whenGetPufferPig: 'pufferpig',
      whenGetStormtrooper: 'stormtrooper',
      whenGetTauntaun: 'tauntaun',
      whenGetMynock: 'mynock',
      whenGetProbot: 'probot',
      whenGetMouseDroid: 'mousedroid',
      whenGetRebelPilot: 'rebelpilot',
    },

    AutohandlerGetAllItems: {
      whenGetAllPufferPigs: 'pufferpig',
      whenGetAllStormtroopers: 'stormtrooper',
      whenGetAllTauntauns: 'tauntaun',
      whenGetAllMynocks: 'mynock',
      whenGetAllProbots: 'probot',
      whenGetAllMouseDroids: 'mousedroid',
      whenGetAllRebelPilots: 'rebelpilot',
    },

    specialItemProperties: {
      pufferpig: {
        frames: 12,
        width: 100,
        height: 100,
        scale: 1,
        renderOffset: {x: 0, y: -15},
        activity: Behavior.WANDER,
        speed: SpriteSpeed.VERY_SLOW,
        spritesCounterclockwise: true,
      },
      stormtrooper: {
        frames: 12,
        width: 100,
        height: 100,
        scale: 1.1,
        renderOffset: {x: 0, y: -15},
        activity: Behavior.CHASE,
        speed: SpriteSpeed.VERY_SLOW,
        spritesCounterclockwise: true,
      },
      tauntaun: {
        frames: 15,
        width: 100,
        height: 100,
        scale: 1.6,
        renderOffset: {x: 0, y: 20},
        activity: Behavior.WANDER,
        speed: SpriteSpeed.SLOW,
        spritesCounterclockwise: true,
      },
      mynock: {
        frames: 8,
        width: 100,
        height: 100,
        scale: 0.9,
        renderOffset: {x: 0, y: -20},
        activity: Behavior.WANDER,
        speed: SpriteSpeed.SLOW,
        spritesCounterclockwise: true,
      },
      probot: {
        frames: 12,
        width: 100,
        height: 100,
        scale: 1.2,
        renderOffset: {x: 0, y: -10},
        activity: Behavior.CHASE,
        speed: SpriteSpeed.LITTLE_SLOW,
        spritesCounterclockwise: true,
      },
      mousedroid: {
        frames: 1,
        width: 100,
        height: 100,
        scale: 0.5,
        renderOffset: {x: 0, y: -20},
        activity: Behavior.FLEE,
        speed: SpriteSpeed.LITTLE_SLOW,
        spritesCounterclockwise: true,
      },
      rebelpilot: {
        frames: 13,
        width: 100,
        height: 100,
        scale: 1,
        renderOffset: {x: 0, y: -20},
        activity: Behavior.FLEE,
        speed: SpriteSpeed.SLOW,
        spritesCounterclockwise: true,
      },
    },
    items: {
      pufferpig: skinUrl('walk_pufferpig.png'),
      stormtrooper: skinUrl('walk_stormtrooper.png'),
      tauntaun: skinUrl('walk_tauntaun.png'),
      mynock: skinUrl('walk_mynock.png'),
      probot: skinUrl('walk_probot.png'),
      mousedroid: skinUrl('walk_mousedroid.png'),
      rebelpilot: skinUrl('walk_rebelpilot.png'),
    },
    backgrounds: {
      endor: {
        background: skinUrl('background_endor.jpg'),
        tiles: skinUrl('tiles_endor.png'),
        jumboTiles: skinUrl('jumbotiles_endor.png'),
        jumboTilesAddOffset: -5,
        jumboTilesSize: 60,
        jumboTilesRows: 4,
        jumboTilesCols: 4,
        clouds: [skinUrl('cloud_light.png'), skinUrl('cloud_light2.png')],
      },
      hoth: {
        background: skinUrl('background_hoth.jpg'),
        tiles: skinUrl('tiles_hoth.png'),
        jumboTiles: skinUrl('jumbotiles_hoth.png'),
        jumboTilesAddOffset: -5,
        jumboTilesSize: 60,
        jumboTilesRows: 4,
        jumboTilesCols: 4,
        clouds: [skinUrl('cloud_dark.png'), skinUrl('cloud_dark2.png')],
      },
      starship: {
        background: skinUrl('background_starship.jpg'),
        tiles: skinUrl('tiles_starship.png'),
        jumboTiles: skinUrl('jumbotiles_starship.png'),
        jumboTilesAddOffset: -5,
        jumboTilesSize: 60,
        jumboTilesRows: 4,
        jumboTilesCols: 4,
      },
    },
  })),
  hoc2015x: skinFor('hoc2015x', skinUrl => ({
    preloadAssets: true,
    sortDrawOrder: true,
    gridAlignedMovement: true,
    gridAlignedExtraPauseSteps: 1,
    slowExecutionFactor: 10,
    hideIconInClearPuzzle: true,
    defaultBackground: 'main',
    showGrid: true,
    projectileFrames: 10,
    itemFrames: 10,
    instructions2ImageSubstitutions: {
      bb8: skinUrl('instructions_bb8.png'),
      hazard: skinUrl('instructions_hazard.png'),
      scrapmetal1: skinUrl('goal1.png'),
      scrapmetal2: skinUrl('goal2.png'),
    },
    blankAvatar: skinUrl('blank.png'),
    avatarAllowedScripts: ['starwars', 'starwarsblocks'],
    ProjectileClassNames: [],
    ItemClassNames: ['hazard'],
    AutohandlerTouchItems: {},
    AutohandlerGetAllItems: {},
    specialItemProperties: {
      hazard: {
        frames: 13,
        animationFrameDuration: 6,
        width: 100,
        height: 100,
        scale: 1.3,
        renderOffset: {x: 0, y: -25},
        activity: Behavior.WATCH_ACTOR,
        speed: SpriteSpeed.VERY_SLOW,
        isHazard: true,
      },
    },
    items: {
      goal1: skinUrl('goal1.png'),
      goal2: skinUrl('goal2.png'),
    },
    goalSpriteWidth: 50,
    goalSpriteHeight: 50,
    animatedGoalFrames: 1,
    disableClipRectOnGoals: true,
    goalEffect: 'glow',
    timePerGoalAnimationFrame: 100,
    goalCollisionRectWidth: 50,
    goalCollisionRectHeight: 50,
    fadeOutGoal: true,
    goalSuccess: undefined,
    goalRenderOffsetX: 0,
    goalRenderOffsetY: 0,
    projectileSpriteWidth: 70,
    projectileSpriteHeight: 70,
    itemCollisionRectWidth: 50,
    itemCollisionRectHeight: 50,
    spriteCollisionRectWidth: 50,
    spriteCollisionRectHeight: 50,
    wallCollisionRectOffsetX: 0,
    wallCollisionRectOffsetY: 24,
    wallCollsiionRectWidth: 30,
    wallCollsiionRectHeight: 20,
    gridSpriteRenderOffsetX: -20,
    gridSpriteRenderOffsetY: -40,
    preventProjectileLoop: (name: string) => name === '',
    preventItemLoop: (name: string) => name === '',
    winAvatar: undefined,
    hazard: skinUrl('hazard_idle.png'),
    enlargeWallTiles: {
      minCol: 0,
      maxCol: 3,
      minRow: 3,
      maxRow: 5,
    },
    sounds: ['move1', 'move2', 'move3', 'move4'],
    soundChoices: [],
    soundChoicesK1: [],
    musicMetadata: HOC2015_MUSIC_METADATA.map(metadata => ({
      ...metadata,
      name: skinUrl(metadata.name),
    })),
    playFinalGoalSound: true,
    mapChoices: [],
    backgroundChoices: [],
    backgroundChoicesK1: [],
    spriteChoices: [
      ['to hidden', HIDDEN_VALUE],
      ['to random', RANDOM_VALUE],
      ['to BB-8', '"bb-8"'],
    ],
    setSpritePrefix: 'set droid',
    projectileChoices: [],
    itemChoices: [],
    avatarList: ['bb-8'],
    avatars: {
      'bb-8': {
        sprite: skinUrl('avatar_bb-8.png'),
        walk: skinUrl('walk_bb-8.png'),
        dropdownThumbnail: skinUrl('avatar_bb-8_thumb.png'),
        frameCounts: {
          normal: 21,
          turns: 8,
          emotions: 0,
          walk: 19,
        },
        drawScale: 2,
        animations: {
          turns: 8,
        },
        animationFrameDuration: 3,
        movementAudio: [
          {begin: 'move1', volume: 0.3},
          {begin: 'move2', volume: 0.3},
          {begin: 'move3', volume: 0.3},
          {begin: 'move4', volume: 0.3},
        ],
      },
    },
    backgrounds: {
      main: {
        background: skinUrl('background_background1.jpg'),
        tiles: skinUrl('tiles_background1.png'),
        clouds: [skinUrl('cloud_light.png'), skinUrl('cloud_light2.png')],
      },
    },
  })),
};

export default skins;
