---
transport:
  name: ssh_tgz
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  require_chef_omnibus: 11.18.12
platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
    attributes:
      cdo-apps:
        dashboard:
          port: 8080
        pegasus:
          port: 8081
        i18n:
          languages:
            en: English
suites:
  - name: default
    run_list:
      - recipe[nginx_test]
  - name: https
    run_list:
      - recipe[cdo-varnish]
      - recipe[nginx_test]
