---
transport:
  name: sftp
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  require_chef_omnibus: 16.18.0
platforms:
  - name: ubuntu-18.04
    run_list:
      - recipe[apt]
      - recipe[sudo-user]
    attributes:
      cdo-apps:
        dashboard:
          port: 8080
        pegasus:
          port: 8081
        i18n:
          languages:
            en: English
suites:
  - name: default
    run_list:
      - recipe[nginx_test]
  - name: https
    run_list:
      - recipe[nginx_test]
