source 'https://supermarket.chef.io'

metadata
cookbook 'cdo-ruby', path: '../cdo-ruby'
cookbook 'nginx_test', path: './test/cookbooks/nginx_test'

# The ssl_certificate library provided in the Supermarket is incompatible with
# modern versions of Chef.
# See https://github.com/zuazo/ssl_certificate-cookbook/issues/45
# Instead, we depend on the as-yet-unmerged fix: https://github.com/zuazo/ssl_certificate-cookbook/pull/46
cookbook 'ssl_certificate', github: 'vzDevelopment/ssl_certificate-cookbook', branch: 'add_provider-issue_45'

cookbook 'cdo-varnish', path: '../cdo-varnish'
cookbook 'sudo-user', path: '../sudo-user'
