{{- if .Values.single_namespace_environment_type }}
#==============================================================================
# Per-k8s-namespace SecretStore : aws-secrets-manager-store in kubernetes
#
# This is installed in "one namespace per environment type" situations, namely:
# - staging, levelbuilder, test, and production
#==============================================================================
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager-store
  namespace: {{ .Values.environment_type }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa-{{ .Values.environment_type }}
{{- else }}
#==============================================================================
# ClusterSecretStore : aws-secrets-manager-store-${env_type} in kubernetes
#
# This is installed in "multiple namespace per env type" situations, namely:
# - adhoc, where all adhoc-* namespaces will have access to this ClusterSecretStore
#==============================================================================
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager-store-{{ .Values.environment_type }}
spec:
  conditions:
    - namespaceRegexes:
{{ toYaml .Values.multi_namespace_regexes | indent 8 }}
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa-{{ .Values.environment_type }}
            namespace: external-secrets
{{- end }}

