apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa-{{ .Values.environment_type }}
  namespace: {{ ternary .Values.environment_type "external-secrets" .Values.single_namespace_environment_type }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iam_role_arn | quote }}

