apiVersion: v1
kind: PersistentVolume
metadata:
  name: dot-config-gcloud
  labels:
    app.kubernetes.io/component: dot-config-gcloud
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  hostPath:
    path: /Users/example/.config/gcloud
