apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdo-dot-aws
  labels:
    app.kubernetes.io/component: dot-aws
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  hostPath:
    path: /Users/example/.aws
