apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../development
components:
  - ../../components/dashboard-job-setup-db
labels:
  - pairs:
      app.kubernetes.io/name: cdo
      app.kubernetes.io/instance: cdo
    includeSelectors: true
    includeTemplates: true
