# Note: EC2 driver with IAM Instance Profile required to run integration test successfully, e.g.:
# IAM_PROFILE_NAME=[IAMProfileName] KITCHEN_LOCAL_YAML=../.kitchen.ec2.yml bundle exec kitchen verify
---
transport:
  name: sftp
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0
platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
suites:
  - name: default
    run_list:
      - recipe[cdo-cloudwatch-extra-metrics]
