---
driver:
  name: dokken
  chef_version: 17.6.18
transport:
  name: dokken
provisioner:
  name: dokken
verifier:
  name: inspec
platforms:
  - name: ubuntu-20.04
    driver:
      image: dokken/ubuntu-20.04
      privileged: true
  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04
      privileged: true
  - name: ubuntu-24.04
    driver:
      image: dokken/ubuntu-24.04
      privileged: true
suites:
  - name: default
    run_list:
      - recipe[cdo-tippecanoe]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
