---
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  data_path: test/shared
  require_chef_omnibus: 12.7.2

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
      - recipe[sudo-user]
suites:
  - name: default
    run_list:
      - recipe[cdo-ruby]
