---
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  data_path: test/shared
  require_chef_omnibus: 17.6.18

platforms:
  - name: ubuntu-20.04
    run_list:
      - recipe[apt]
suites:
  - name: default
    run_list:
      - recipe[cdo-ruby]
