#!/bin/sh

# If 'docker' is available, we do it via docker compose
if hash docker 2>/dev/null; then
  docker compose --progress quiet run --rm git-post-merge
else
  # Otherwise, attempt to do it via the normal script
  ../../../tools/hooks/post-merge
fi
