# Docker Compose file for running ui tests.
#
# To run, set the following env variables (values obtainable from Circle):
# PROPERTIES_ENCRYPTION_KEY
# CLOUDFRONT_KEY_PAIR_ID
# CLOUDFRONT_PRIVATE_KEY
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# SAUCE_USERNAME
# SAUCE_ACCESS_KEY
#
# Also set the FIXUID and FIXGID env variables with these commands (or put them in your .bash_profile / .bashrc):
# export FIXUID=$(id -u)
# export FIXGID=$(id -g)
#
# then run:
# docker-compose -f ui-tests-compose.yml up
#
# To clean up:
# docker-compose -f ui-tests-compose.yml down

version: "3"
services:
  site:
    # TODO: switch to codedotorg/cdo-ci or other new image
    image: codedotorg/code-dot-org:1.14
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    volumes:
      - ../:/home/ci/code-dot-org:delegated
      - rbenv:/home/ci/.rbenv
      - mysqldata:/var/lib/mysql
      - yarncache:/home/ci/.cache
      - gcloud_config:/home/ci/.config/gcloud
    env_file:
      - env.list
    depends_on:
      - selenium-chrome
      - ui-tests-redis
    command: /bin/sh -c "docker/ui_tests.sh"
    expose:
      - "3000" # puma web server
    networks:
      cdo_network_test:
        aliases:
          - ui-tests.code.org
          - ui-tests-studio.code.org
          - ui-tests.hourofcode.com
          - ui-tests.csedweek.org

  ui-tests-redis:
    image: redis
    networks:
      - cdo_network_test
    expose:
      - "6379"

  selenium-chrome:
    hostname: selenium-chrome
    image: selenium/standalone-chrome:132.0
    environment:
      SE_VNC_PORT: 5910
      SE_NO_VNC_PORT: 7910
      DISPLAY_NUM: 100
      DISPLAY: ':100.0'
      JAVA_OPTS: -Dwebdriver.chrome.whitelistedIps= -Dwebdriver.chrome.allowedIps=
    shm_size: '2gb'
    networks:
      - cdo_network_test
    expose:
      - "5910" # The selenium direct VNC port
      - "4444" # The selenium router port
      - "7910" # The selenium NoVNC service port

volumes:
  mysqldata:
  rbenv:
  yarncache:
  gcloud_config:

networks:
  cdo_network_test:
    driver: bridge
