// Where the builder is what a block's code will call, and where it is not.
//
// `define actor` declares `const actor = new ActorBuilder(...)`; an event
// handler generated by a `world_on_*` block rebinds that name to the live Actor
// instance. A block calling a builder-only method (`useTraits`, `useEffect`)
// placed in a handler therefore emits a call the live instance cannot answer.
// `inBuilderContext` is what the editor warning reads.

import type {Block} from 'blockly';
import {describe, expect, it} from 'vitest';

import {inBuilderContext} from '../actorContext';

/** Where `use effect` is valid: an actor template body. */
const EFFECT_ROOTS = ['world_actor'];
/**
 * Where `use trait` is valid: a template body, or a trait's own `requires`
 * inside `define trait` — which is parsed statically, never generated.
 */
const TRAIT_ROOTS = ['world_actor', 'world_rule_trait'];

/**
 * A block with a parent chain, as `getParent()` walks it.
 *
 * Innermost first: `chain('world_use_effect', 'world_actor')` is a use-effect
 * block whose parent is the actor definition. Each block captures its own
 * parent in a const — closing over the loop variable instead would make every
 * block report the last one as its parent, and the walk would never terminate.
 */
function chain(...types: string[]): Block {
  let parent: Block | null = null;
  for (const type of [...types].reverse()) {
    const above = parent;
    parent = {type, getParent: () => above} as unknown as Block;
  }
  return parent as Block;
}

describe('inBuilderContext', () => {
  it('accepts a block chained under `define actor`', () => {
    const block = chain('world_use_effect', 'world_actor');
    expect(inBuilderContext(block, EFFECT_ROOTS)).toBe(true);
  });

  it('accepts a block nested deeper inside the definition body', () => {
    const block = chain('world_use_effect', 'controls_if', 'world_actor');
    expect(inBuilderContext(block, EFFECT_ROOTS)).toBe(true);
  });

  it('rejects a floating block with no parent at all', () => {
    expect(inBuilderContext(chain('world_use_effect'), EFFECT_ROOTS)).toBe(
      false,
    );
  });

  it('rejects a block inside an event handler', () => {
    // The case this exists for: a handler rebinds `actor` to the live instance.
    const block = chain('world_use_effect', 'world_on_startsFalling');
    expect(inBuilderContext(block, EFFECT_ROOTS)).toBe(false);
  });

  it('rejects a handler nested inside an actor definition file', () => {
    // Events are their own roots, but a walk that only looked for `world_actor`
    // would accept this — the nearest binder is what decides, so the search
    // stops at the handler.
    const block = chain(
      'world_use_effect',
      'world_on_startsFalling',
      'world_actor',
    );
    expect(inBuilderContext(block, EFFECT_ROOTS)).toBe(false);
  });

  it('rejects a block in a scene or world root', () => {
    expect(
      inBuilderContext(chain('world_use_effect', 'world_scene'), EFFECT_ROOTS),
    ).toBe(false);
    expect(
      inBuilderContext(chain('world_use_effect', 'world_world'), EFFECT_ROOTS),
    ).toBe(false);
  });
});

describe('inBuilderContext, for `use trait`', () => {
  it('accepts a trait chained under `define actor`', () => {
    const block = chain('world_use_trait', 'world_actor');
    expect(inBuilderContext(block, TRAIT_ROOTS)).toBe(true);
  });

  it("accepts a trait inside `define trait`, declaring that trait's requires", () => {
    // The second home, and the reason `use trait` gets its own root list. There
    // the block is read into `RuleMeta` rather than generated, so no builder
    // method is called at all — warning about it would flag a correct program.
    const block = chain('world_use_trait', 'world_rule_trait', 'world_rule');
    expect(inBuilderContext(block, TRAIT_ROOTS)).toBe(true);
  });

  it('still rejects a trait inside an event handler', () => {
    // `useTraits` exists only on the builder; the live Actor has no such
    // method, so this is the "actor.useTraits is not a function" case.
    const block = chain('world_use_trait', 'world_on_startsFalling');
    expect(inBuilderContext(block, TRAIT_ROOTS)).toBe(false);
  });

  it('does not accept `define trait` for a block that only allows the actor root', () => {
    // The two lists really are different: a `use effect` inside `define trait`
    // would have no builder to call.
    const block = chain('world_use_effect', 'world_rule_trait');
    expect(inBuilderContext(block, EFFECT_ROOTS)).toBe(false);
  });
});
