// Where `actor` means the builder, and where it does not.
//
// `define actor` declares `const actor = new ActorBuilder(...)`; an event
// handler generated by a `world_on_*` block rebinds that name to the live Actor
// instance. A template block (`use effect`) placed in a handler therefore emits
// a call to a method the live instance does not have. `inActorDefinition` is
// what the editor warning reads.

import type {Block} from 'blockly';
import {describe, expect, it} from 'vitest';

import {inActorDefinition} from '../actorContext';

/**
 * A block with a parent chain, as `getParent()` walks it.
 *
 * Innermost first: `chain('world_use_effect', 'world_actor')` is a use-effect
 * block whose parent is the actor definition. Each block captures its own
 * parent in a const — closing over the loop variable instead would make every
 * block report the last one as its parent, and the walk would never terminate.
 */
function chain(...types: string[]): Block {
  let parent: Block | null = null;
  for (const type of [...types].reverse()) {
    const above = parent;
    parent = {type, getParent: () => above} as unknown as Block;
  }
  return parent as Block;
}

describe('inActorDefinition', () => {
  it('accepts a block chained under `define actor`', () => {
    expect(inActorDefinition(chain('world_use_effect', 'world_actor'))).toBe(
      true,
    );
  });

  it('accepts a block nested deeper inside the definition body', () => {
    expect(
      inActorDefinition(
        chain('world_use_effect', 'controls_if', 'world_actor'),
      ),
    ).toBe(true);
  });

  it('rejects a floating block with no parent at all', () => {
    expect(inActorDefinition(chain('world_use_effect'))).toBe(false);
  });

  it('rejects a block inside an event handler', () => {
    // The case this exists for: a handler rebinds `actor` to the live instance.
    expect(
      inActorDefinition(chain('world_use_effect', 'world_on_startsFalling')),
    ).toBe(false);
  });

  it('rejects a handler nested inside an actor definition file', () => {
    // Events are their own roots, but a walk that only looked for `world_actor`
    // would accept this — the nearest binder is what decides, so the search
    // stops at the handler.
    expect(
      inActorDefinition(
        chain('world_use_effect', 'world_on_startsFalling', 'world_actor'),
      ),
    ).toBe(false);
  });

  it('rejects a block in a scene or world root', () => {
    expect(inActorDefinition(chain('world_use_effect', 'world_scene'))).toBe(
      false,
    );
    expect(inActorDefinition(chain('world_use_effect', 'world_world'))).toBe(
      false,
    );
  });
});
