apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dex-argocd-secret-reader
  namespace: argocd
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
