apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.dexSecretStore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.dexSecretStore.awsRegion | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.dexSecretStore.serviceAccountName }}
