import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guide: [{type: 'autogenerated', dirName: 'guide'}],
  developers: [{type: 'autogenerated', dirName: 'developers'}],
};

export default sidebars;
