#!/bin/bash

set -e

command -v aws >/dev/null 2>&1 || {
  echo '"aws" command line tool must be installed' > /dev/stderr
  exit 1
}

if [ -z "$AWS_SECRET_ACCESS_KEY" -o -z "$AWS_ACCESS_KEY_ID" ]; then
  echo 'AWS environment is not defined. Use cdo-env for secrets' > /dev/stderr
  exit 1
fi

remote='git@github.com:code-dot-org/blockly.git'

echo 'Performing full build...'
./script/full-build

echo 'Incrementing package version...'
perl -i ./script/bump-version.pl package.json

version=$(grep '"version":' < package.json | cut -d'"' -f4)
tag="v$version"
echo $version > ./build/VERSION

echo 'Pushing tagged version...'
git commit package.json -m "Bump version to $version"
git tag $tag -m "version $version"
git push $remote master
git push $remote $tag

echo 'Packaging...'
tgz="blockly-mooc-${tag}.tgz"
mkdir -p ./dist
(cd ./build && tar -zcvf ../dist/$tgz ./package)

echo "Distributing $tgz and VERSION file to S3..."
export AWS_DEFAULT_REGION='us-east-1'
aws s3 cp --acl 'public-read' ./dist/$tgz s3://cdo-dist/blockly-mooc/$tgz
aws s3 cp --acl 'public-read' ./build/VERSION s3://cdo-dist/blockly-mooc/VERSION
