import {commands as mlCommands} from '@cdo/apps/lib/util/mlApi';

// Sprite Lab's predict block is value-returning: code generated by Blockly
// looks like `varName = getPrediction(inputs)`. Returning a value (rather
// than firing a callback) lets the assignment land in the same interpreter
// tick — the JS-Interpreter would otherwise queue an interpreted callback
// for the next tick, which arrives after the next statement has already
// executed.
//
// The model is read from the project's imported model — see
// SettingsCog → Manage AI Models. The lab's preload phase warms mlApi's
// cache so this call is synchronous.
function parseTestValues(testValues) {
  if (typeof testValues !== 'string') {
    return testValues;
  }
  try {
    return JSON.parse(testValues);
  } catch (e) {
    return undefined;
  }
}

export const commands = {
  getPrediction(testValues) {
    const parsed = parseTestValues(testValues);
    if (parsed === undefined) {
      return 'Error: invalid input format';
    }
    return mlCommands.getPrediction({testValues: parsed});
  },
};
