apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager-store-kargo-shared-resources
  namespace: kargo-shared-resources
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.clusterRegion | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa-kargo-shared-resources
