apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa-kargo-shared-resources
  namespace: kargo-shared-resources
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iamRoleArn | quote }}
