#============================================================
# Publish cluster facts for later Helm / GitOps consumers.
#============================================================
#
# These values originate in cluster, but cluster-infra owns the consumer-facing
# handoff file so later phases do not need raw remote-state outputs for this
# cluster-shape metadata.

# update+commit+push apps/infra/codeai-cluster-config.values.yaml to GitHub repo k8s-gitops
# this is the form that will be used by ArgoCD apps.
#
# TODO: eventually, this should probably become a PR instead?
resource "github_repository_file" "codeai_cluster_config_values" {
  provider            = github.kargo_k8s_gitops
  repository          = "k8s-gitops"
  branch              = "main"
  file                = "apps/infra/codeai-cluster-config.values.yaml"
  commit_message      = "codeai-cluster-config.tf: update codeai-cluster-config.values.yaml"
  overwrite_on_create = true

  content = join("\n", [
    "# Generated by OpenTofu during `tofu apply` of code-dot-org/k8s/tofu/codeai-k8s/cluster-infra/codeai-cluster-config.tf.",
    "# Do not edit by hand.",
    "\n",
    "# General codeai_cluster_config values, for use by charts that still consume them directly.",
    yamlencode({
      codeai_cluster_config = {
        cluster_name                       = local.cluster_name
        cluster_region                     = local.cluster_region
        cluster_subdomain                  = local.cluster_subdomain
        cluster_oidc_issuer_url            = local.cluster_oidc_issuer_url
        iam_arn_prefix                     = "arn:${data.aws_partition.current.partition}:iam::${data.aws_caller_identity.current.account_id}"
        oidc_provider_arn                  = local.oidc_provider_arn
        parent_domain_zone_id              = data.aws_route53_zone.parent_domain.zone_id
        single_namespace_environment_types = sort(tolist(toset(local.single_namespace_environment_types)))
        frontend_security_group_namespaces = sort(tolist(toset(local.cluster_outs.frontend_security_group_namespaces)))
        cluster_primary_security_group_id  = local.cluster_outs.cluster_primary_security_group_id
        frontend_security_group_id         = local.cluster_outs.frontend_security_group_id
      }
    }),
  ])
}
