inherit_from: ../.rubocop.yml

AllCops:
  # Chef embeds its own version of Ruby which is used to execute these
  # cookbooks, so we want to make sure we're validating against that version
  TargetRubyVersion: 2.6
