source "https://supermarket.chef.io"

#metadata

cookbook 'apt', '~> 2.6.0'
cookbook 'build-essential', '~> 2.1.3'
cookbook 'chef-client', '~> 4.2.0'
cookbook 'ntp', '~> 1.8.6'

`bundle exec knife cookbook list -z 2>/dev/null`.each_line do |path|
  path = path.split(/\s/).first
  cookbook path, path: path
end
