# Workaround for berkshelf/berkshelf-api#112
Encoding.default_external = Encoding::UTF_8

source "https://supermarket.chef.io"
cookbook 'apt'
cookbook 'ark'
cookbook 'chef-client'
cookbook 'ntp'
cookbook 'seven_zip'
cookbook 'chef_client_updater', '>= 3.3.2' # 3.3.2 fixed https://github.com/chef-cookbooks/chef_client_updater/pull/93

# required for cdo-nginx. See that cookbook's Berksfile for details.
cookbook 'ssl_certificate', github: 'code-dot-org/ssl_certificate-cookbook', branch: 'add_provider-issue_45'

# List all local cookbooks using local-mode Chef.
require 'chef/local_mode'
Chef::Config.local_mode = true
Chef::Config.chef_repo_path = Chef::Config.find_chef_repo_path(__dir__)
Chef::LocalMode.with_server_connectivity do
  require 'chef/server_api'
  cookbooks = Chef::ServerAPI.new(Chef::Config[:chef_server_url]).get('/cookbooks')
  cookbooks.keys.each do |path|
    cookbook path, path: path
  end
end
