# Workaround for berkshelf/berkshelf-api#112
Encoding.default_external = Encoding::UTF_8

source "https://supermarket.chef.io"
cookbook 'apt'
cookbook 'ark'
cookbook 'build-essential'
cookbook 'chef-client'
cookbook 'ntp'
cookbook 'seven_zip'
cookbook 'chef_client_updater'

# List all local cookbooks using local-mode Chef.
require 'chef/local_mode'
Chef::Config.local_mode = true
Chef::Config.chef_repo_path = Chef::Config.find_chef_repo_path(__dir__)
Chef::LocalMode.with_server_connectivity do
  require 'chef/server_api'
  cookbooks = Chef::ServerAPI.new(Chef::Config[:chef_server_url]).get('/cookbooks')
  cookbooks.keys.each do |path|
    cookbook path, path: path
  end
end
