source 'https://rubygems.org'

gem 'chef'
# Use solve 2.0 to remove gecode dependency (cf. berkshelf/berkshelf#1475)
gem 'berkshelf', github: 'berkshelf/berkshelf', ref: 'a05e392'

# Test-kitchen fork includes several helpful PRs not merged in the official repo:
# 564 (multiple step converge)
gem 'test-kitchen', github: 'wjordan/test-kitchen', branch: 'cdo'
gem 'kitchen-docker'
gem 'kitchen-ec2', github: 'wjordan/kitchen-ec2', branch: 'cdo'
gem 'kitchen-sync'
