source 'https://rubygems.org'
ruby '>= 2.6', '< 2.8'

gem 'berkshelf'
gem 'chef', '16.18.0'
gem 'chefspec'
gem 'kitchen-inspec'

gem 'test-kitchen'

gem 'kitchen-docker'
gem 'kitchen-dokken'

gem 'kitchen-ec2'

# Provides `sftp` transport to test-kitchen for faster cookbook upload.
gem 'kitchen-sync'

gem 'json', '>= 2.3.0' # 2.3.0 resolved some Ruby 2.7 deprecation warnings
