source 'https://rubygems.org'
ruby '~> 3.0'

gem 'berkshelf'
gem 'chef', '17.6.18'
gem 'chefspec'
gem 'kitchen-inspec'

gem 'test-kitchen'

gem 'kitchen-docker'
gem 'kitchen-dokken'

gem 'kitchen-ec2'

# Provides `sftp` transport to test-kitchen for faster cookbook upload.
gem 'kitchen-sync'
