#!/usr/bin/env ruby

# A script for creating/updating our CloudFormation stacks for
# staging, test, and production. Currently these stacks describe only
# our SQS queues but in the future we can describe other dependencies
# as well.

%w{staging test production}.each do |environment|
  puts `aws cloudformation create-stack --stack-name #{environment} --template-body file://cloud_formation.json --parameters --parameters ParameterKey=Environment,ParameterValue=#{environment}`
end
