#!/usr/bin/env ruby
# A script for setting up DNS entries for a new adhoc instance.
require_relative '../deployment'
require 'cdo/rake_utils'

hostname = ARGV[0] || raise('Usage: setup_dns [hostname]')
name = ENV['NAME'] ||
  rack_env?(:adhoc) ?
    "adhoc-#{RakeUtils.git_branch}" :
    raise("adhoc environment or ENV['NAME'] required")
domain = ENV['DOMAIN'] || 'cdn-code.org'

require 'aws-sdk'
route53 = Aws::Route53::Client.new
zone_id = route53.list_hosted_zones_by_name(
  dns_name: domain,
  max_items: 1
).hosted_zones.first.id.split('/').last

subdomains = ['-studio', '']

route53.change_resource_record_sets(
  hosted_zone_id: zone_id,
  change_batch: {
    changes: subdomains.map do |subdomain|
      fqdn = "#{name}#{subdomain}.#{domain}"
      {
        action: 'UPSERT',
        resource_record_set: {
          name: fqdn,
          type: 'CNAME',
          ttl: '30',
          resource_records: [{ value: hostname }]
        }
      }
    end
  }
)

puts "Updated the following DNS entries to CNAME #{hostname}"
subdomains.each do |subdomain|
  fqdn = "#{name}#{subdomain}.#{domain}"
  puts "https://#{fqdn}"
end
