#!/usr/bin/env ruby
require_relative '../deployment'
require 'cdo/only_one'

def main()
  Dir.chdir('/home/ubuntu/solr-4.8.1/example') do
    system 'java', '-jar', 'start.jar'
  end
end

main() if only_one_running?(__FILE__)

