require 'rake/testtask'

desc 'Run tests for lib directory'
task :test do
  puts 'starting test task'
  Rake::TestTask.new do |t|
    t.warning = false
    t.test_files = FileList["test/**/test_*.rb"]
  end
end

task default: :test
