apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa-kargo-shared-resources
  namespace: {{ .Values.sharedResources.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.sharedResources.iamRoleArn | quote }}
