---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  image: ubuntu-upstart:14.04
  run_command: /sbin/init
transport:
  name: sftp
  connection_timeout: 10
  connection_retries: 5
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.7.2
  client_rb:
    node_name: test-cdo-newrelic
platforms:
  - name: ubuntu-14.04
    attributes:
      cdo-newrelic:
        license-key: <%=ENV['LICENSE_KEY']%>
        api-key: <%=ENV['API_KEY']%>
        enabled_alert_policy_id: 374172
        disabled_alert_policy_id: 374173
suites:
  - name: default
    run_list:
      - recipe[cdo-newrelic]
  - name: stop
    run_list:
      - recipe[cdo-newrelic]
      - recipe[cdo-newrelic::unload]
