apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.dexGoogleServiceAccount.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.dexSecretStore.name }}
  target:
    name: {{ .Values.dexGoogleServiceAccount.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
  data:
    - secretKey: {{ .Values.dexGoogleServiceAccount.fileName }}
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.dexGoogleServiceAccount.awsSecretName | quote }}
        metadataPolicy: None
