apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dexConfigSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  config.yaml: |
{{ tpl .Values.dexConfigSecret.configYaml . | indent 4 }}
