apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.dexGoogleClientSecret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.dexSecretStore.name }}
  target:
    name: {{ .Values.dexGoogleClientSecret.name }}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.dexGoogleClientSecret.awsSecretName | quote }}
