apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-client-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: argocd-secret-store
  target:
    name: oidc-client-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
  data:
    - secretKey: ARGOCD_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-secret
        metadataPolicy: None
        property: dex.argocd.clientSecret
