RAILS_ENV: development
healthChecks:
  enabled: true
services:
  redis:
    enabled: true
  mysql:
    enabled: true
  minio:
    enabled: true
localDev:
  mounts:
    mountDotAWS: true
    mountDotConfigGcloud: true
user:
  allowSudo: true
