RAILS_ENV: development
dashboard_workers: 0
healthChecks:
  # Disable this if you want pods to start even if they fail an HTTP health check
  # can be useful for inspecting what's going wrong.
  enabled: true
services:
  redis:
    enabled: true
    # skaffold development profile will auto-generate, see cdo-local-secrets:
    # password:
  mysql:
    enabled: true
    # skaffold development profile will auto-generate, see cdo-local-secrets:
    # password:
  minio:
    enabled: true
    # skaffold development profile will auto-generate, see cdo-local-secrets:
    # password: 

user:
  allowSudo: true
