#!/usr/bin/env ruby
require_relative '../../../deployment'
require 'cdo/rack/rackup'
require 'cdo/only_one'

def main()
  Rack.with_rackup(pegasus_dir, port:8079) do |params|
    system 'rake', '--trace', '--rakefile', pegasus_dir('sites/virtual/collate_pdfs.rake'), "base_url=http://code.org/"
    exit $?.exitstatus
  end
end

main() if only_one_running?(__FILE__)
