require_relative '../deployment.rb'
require 'cdo/erb'

def i18n_dir(*paths)
  deploy_dir('i18n', *paths)
end

DEPENDENCIES = [
  deploy_dir('Rakefile'),
  deploy_dir('deployment.rb'),
  deploy_dir('locals.yml'),
  secrets_dir('config.yml'),
].select {|i| File.file?(i)}

ERB_TASKS = [
  'code.org/crowdin.yaml',
  'hourofcode.com/crowdin.yaml',
  'curriculum/crowdin.yaml',
].map do |filename|
  i18n_dir(filename).tap do |path|
    file path => [i18n_dir("#{filename}.erb")] + DEPENDENCIES do |t|
      puts "erb #{path}"
      erb_file_to_file t.prerequisites[0], t.name, task: t
    end
  end
end

task default: ERB_TASKS

task :clean do
  ERB_TASKS.select {|i| File.file?(i)}.each {|i| rm(i)}
end
