// Metric event names
export enum MetricEvent {
  AI_TUTOR_CHAT_SAVE_FAIL = 'AI_TUTOR_CHAT_SAVE_FAIL',
  AI_TUTOR_CHAT_FETCH_FAIL_FOR_SECTION = 'AI_TUTOR_CHAT_FETCH_FAIL_FOR_SECTION',
  AI_TUTOR_CHAT_FETCH_FAIL_FOR_STUDENT = 'AI_TUTOR_CHAT_FETCH_FAIL_FOR_STUDENT',
  GOOGLE_BLOCKLY_GET_CODE_ERROR = 'BLOCKLY_GET_CODE_ERROR',
  CDO_BLOCKLY_GET_CODE_ERROR = 'CDO_BLOCKLY_GET_CODE_ERROR',
}
