name: MySQL installer
description: 'Install a mysql instance for the tests to run'
jobs:

runs:
  using: "composite"
  steps:
    - name: Start MySQL
      run: sudo /etc/init.d/mysql start
      shell: bash
    - name: Set mysql root password
      run: echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';" | sudo mysql -uroot -proot
      shell: bash
