apiVersion: v2
name: argocd-wrapper
description: Local wrapper chart for Argo CD
type: application
version: 0.1.0

dependencies:
  - name: argo-cd
    alias: argocd
    repository: https://argoproj.github.io/argo-helm
    version: 9.4.11
