apiVersion: v2
name: standard-envtypes
description: Standard environment-type ESO resources for codeai-k8s
type: application
version: 0.1.0

dependencies:
  - name: eso-per-envtype
    repository: file://../eso-per-envtype
    version: 0.1.0
