codeai_cluster_config:
  single_namespace_environment_types: []
  cluster_region: us-east-1
  eso_iam_role_arns: {}
  frontend_security_group_namespaces: []
  cluster_primary_security_group_id: ""
  frontend_security_group_id: ""

adhoc:
  enabled: true
  environment_type: adhoc
  multi_namespace_regexes:
    - "^adhoc-.*"
