---
transport:
  name: sftp
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0
  environments_path: test/environments
  client_rb:
    node_name: test_varnish
    environment: integration

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
    attributes:
      cdo-apps:
        dashboard:
          port: 8080
        pegasus:
          port: 8081
        i18n:
          languages:
            en: English
            fr: French
suites:
  - name: default
    run_list:
      - recipe[varnish_test]
  - name: cloudfront
    run_list:
      - recipe[varnish_test]
      - recipe[varnish_test::ngrok]
    attributes:
      varnish_test:
        authtoken: <%= ENV['NGROK_TOKEN'] %>
