# #Clever API
#
#The Clever API
#
# The version of the OpenAPI document: 3.1.0
#
# Generated by: https://openapi-generator.tech
# Generator version: 7.17.0
#

require 'date'
require 'time'

module Clever
  class Attachment < ApiModelBase
    attr_accessor :description, :file_external_id, :size, :thumbnail_url, :title, :type, :url

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :description => :description,
        :file_external_id => :file_external_id,
        :size => :size,
        :thumbnail_url => :thumbnail_url,
        :title => :title,
        :type => :type,
        :url => :url
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :description => :String,
        :file_external_id => :String,
        :size => :Float,
        :thumbnail_url => :String,
        :title => :String,
        :type => :String,
        :url => :String
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
                :description,
                :file_external_id,
                :thumbnail_url,
                :title,
                :url
              ]
)
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      unless attributes.is_a?(Hash)
        fail ArgumentError, "The input argument (attributes) must be a hash in `Clever::Attachment` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) do |(k, v), h|
        unless acceptable_attribute_map.key?(k.to_sym)
          fail ArgumentError, "`#{k}` is not a valid attribute in `Clever::Attachment`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      end

      if attributes.key?(:description)
        self.description = attributes[:description]
      end

      if attributes.key?(:file_external_id)
        self.file_external_id = attributes[:file_external_id]
      end

      if attributes.key?(:size)
        self.size = attributes[:size]
      end

      if attributes.key?(:thumbnail_url)
        self.thumbnail_url = attributes[:thumbnail_url]
      end

      if attributes.key?(:title)
        self.title = attributes[:title]
      end

      if attributes.key?(:type)
        self.type = attributes[:type]
      end

      if attributes.key?(:url)
        self.url = attributes[:url]
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if equal?(other)
      self.class == other.class &&
        description == other.description &&
        file_external_id == other.file_external_id &&
        size == other.size &&
        thumbnail_url == other.thumbnail_url &&
        title == other.title &&
        type == other.type &&
        url == other.url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [description, file_external_id, size, thumbnail_url, title, type, url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash[key.to_s] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash[key.to_s] = attributes[attribute_map[key]].map {|v| _deserialize($1, v)}
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash[key.to_s] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
