# In development, this allows us to re-use our aws-google login from our local machine.
{{- if .Values.development.mounts.mountDotConfigGcloud }}
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:   
  name: {{ include "cdo.fullname" (merge (dict "component" "dot-config-gcloud") .) }}
  labels:
    {{ include "cdo.labels" (merge (dict "component" "dot-config-gcloud") .) | nindent 4 }}
spec:
  resources:
    requests:
      storage: 5Mi  
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  selector:
    matchLabels:
      {{ include "cdo.selectorLabels" (merge (dict "component" "dot-config-gcloud") .) | nindent 6 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "cdo.fullname" (merge (dict "component" "dot-config-gcloud") .) }}
  labels:
    {{ include "cdo.labels" (merge (dict "component" "dot-config-gcloud") .) | nindent 4 }}
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.development.mounts.hostPaths.home }}/.config/gcloud
  # claimRef:
  #   name: dot-config-gcloud
  #   namespace: {{ .Release.Namespace }}
{{- end }}