// Applab theme values.

const CLASSIC_LABEL_PADDING = '2px';
const NEW_THEME_LABEL_PADDING = '2px 15px';

export const CLASSIC_TEXT_INPUT_PADDING = '5px';
const NEW_THEME_TEXT_INPUT_PADDING = '5px 15px';

export const CLASSIC_DROPDOWN_PADDING = '0 30px 0 10px';
const NEW_THEME_DROPDOWN_PADDING = '0 30px 0 15px';

export const CLASSIC_TEXT_AREA_PADDING = '5px';
const NEW_THEME_TEXT_AREA_PADDING = '5px 15px';

const STANDARD_FONT_SIZE_THEME_VALUES = {
  default: 13,
  orange: 13,
  citrus: 13,
  ketchupAndMustard: 13,
  lemonade: 13,
  forest: 13,
  watermelon: 13,
  area51: 13,
  polar: 13,
  glowInTheDark: 13,
  bubblegum: 13,
  millennial: 13,
  robot: 13,
  classic: 14
};

const TEXT_INPUT_BORDER_COLOR_THEME_VALUES = {
  type: 'color',
  default: '#4D575F',
  orange: '#FFFFFF',
  citrus: '#69883D',
  ketchupAndMustard: '#FFFFFF',
  lemonade: '#193A55',
  forest: '#000000',
  watermelon: '#578B2E',
  area51: '#D8FFA7',
  polar: '#FFFFFF',
  glowInTheDark: '#FFFFFF',
  bubblegum: '#000000',
  millennial: '#FFFFFF',
  robot: '#353C42',
  classic: 'rgb(153, 153, 153)'
};

const themeValues = {
  screen: {
    backgroundColor: {
      type: 'color',
      default: '#FFFFFF',
      orange: '#FFA400',
      citrus: '#96C257',
      ketchupAndMustard: '#EB5757',
      lemonade: '#FFE049',
      forest: '#23782B',
      watermelon: '#C5E255',
      area51: '#362F49',
      polar: '#AEE2F4',
      glowInTheDark: '#7D6CA6',
      bubblegum: '#FFC3E6',
      millennial: '#FEDBD0',
      robot: '#D8E0E3',
      classic: '#FFFFFF'
    }
  },
  label: {
    textColor: {
      type: 'color',
      default: '#4D575F',
      orange: '#FFFFFF',
      citrus: '#F7EC60',
      ketchupAndMustard: '#FFFFFF',
      lemonade: '#5BB7E7',
      forest: '#004624',
      watermelon: '#E2F0AA',
      area51: '#D8FFA7',
      polar: '#EFFAFF',
      glowInTheDark: '#D9FFD9',
      bubblegum: '#000000',
      millennial: '#442C2E',
      robot: '#F5F5F6',
      classic: '#333333'
    },
    backgroundColor: {
      type: 'color',
      default: 'rgba(0, 0, 0, 0)',
      orange: '#4D3100',
      citrus: '#69883D',
      ketchupAndMustard: '#A53D3D',
      lemonade: 'rgba(0, 0, 0, 0)',
      forest: 'rgba(0, 0, 0, 0)',
      watermelon: '#578B2E',
      area51: '#221D30',
      polar: '#0094CA',
      glowInTheDark: '#635982',
      bubblegum: '#FFD4ED',
      millennial: '#FEEAE6',
      robot: '#80A7B9',
      classic: 'rgba(0, 0, 0, 0)'
    },
    borderColor: TEXT_INPUT_BORDER_COLOR_THEME_VALUES,
    borderRadius: {
      default: 0,
      orange: 0,
      citrus: 2,
      ketchupAndMustard: 10,
      lemonade: 0,
      forest: 2,
      watermelon: 0,
      area51: 10,
      polar: 2,
      glowInTheDark: 0,
      bubblegum: 10,
      millennial: 4,
      robot: 0,
      classic: 0
    },
    borderWidth: {
      default: 0,
      orange: 0,
      citrus: 0,
      ketchupAndMustard: 0,
      lemonade: 0,
      forest: 0,
      watermelon: 0,
      area51: 0,
      polar: 0,
      glowInTheDark: 0,
      bubblegum: 0,
      millennial: 0,
      robot: 0,
      classic: 0
    },
    fontFamily: {
      default: 'Arial Black',
      orange: 'Arial',
      citrus: 'Georgia',
      ketchupAndMustard: 'Georgia',
      lemonade: 'Arial Black',
      forest: 'Verdana',
      watermelon: 'Georgia',
      area51: 'Trebuchet',
      polar: 'Verdana',
      glowInTheDark: 'Tahoma',
      bubblegum: 'Georgia',
      millennial: 'Arial',
      robot: 'Tahoma',
      classic: 'Arial'
    },
    fontSize: STANDARD_FONT_SIZE_THEME_VALUES,
    padding: {
      default: NEW_THEME_LABEL_PADDING,
      orange: NEW_THEME_LABEL_PADDING,
      citrus: NEW_THEME_LABEL_PADDING,
      ketchupAndMustard: NEW_THEME_LABEL_PADDING,
      lemonade: NEW_THEME_LABEL_PADDING,
      forest: NEW_THEME_LABEL_PADDING,
      watermelon: NEW_THEME_LABEL_PADDING,
      area51: NEW_THEME_LABEL_PADDING,
      polar: NEW_THEME_LABEL_PADDING,
      glowInTheDark: NEW_THEME_LABEL_PADDING,
      bubblegum: NEW_THEME_LABEL_PADDING,
      millennial: NEW_THEME_LABEL_PADDING,
      robot: NEW_THEME_LABEL_PADDING,
      classic: CLASSIC_LABEL_PADDING
    }
  },
  textInput: {
    textColor: {
      type: 'color',
      default: '#4D575F',
      orange: '#FFFFFF',
      citrus: '#000000',
      ketchupAndMustard: '#FFFFFF',
      lemonade: '#00A8FF',
      forest: '#FFFFFF',
      watermelon: '#151F00',
      area51: '#D8FFA7',
      polar: '#442C2E',
      glowInTheDark: '#D9FFD9',
      bubblegum: '#000000',
      millennial: '#442C2E',
      robot: '#353C42',
      classic: '#000000'
    },
    backgroundColor: {
      type: 'color',
      default: '#F2F2F2',
      orange: '#B37300',
      citrus: '#FFFFFF',
      ketchupAndMustard: '#A53D3D',
      lemonade: '#FFFFFF',
      forest: '#004624',
      watermelon: '#E2F0AA',
      area51: '#221D30',
      polar: '#ACCFDE',
      glowInTheDark: '#4D575F',
      bubblegum: '#FFD4ED',
      millennial: '#FEDBD0',
      robot: '#FFFFFF',
      classic: '#FFFFFF'
    },
    borderColor: TEXT_INPUT_BORDER_COLOR_THEME_VALUES,
    borderRadius: {
      default: 4,
      orange: 0,
      citrus: 4,
      ketchupAndMustard: 5,
      lemonade: 4,
      forest: 4,
      watermelon: 0,
      area51: 10,
      polar: 4,
      glowInTheDark: 0,
      bubblegum: 4,
      millennial: 4,
      robot: 0,
      classic: 0
    },
    borderWidth: {
      default: 1,
      orange: 1,
      citrus: 1,
      ketchupAndMustard: 1,
      lemonade: 1,
      forest: 1,
      watermelon: 2,
      area51: 1,
      polar: 1,
      glowInTheDark: 1,
      bubblegum: 1,
      millennial: 2,
      robot: 1,
      classic: 1
    },
    fontFamily: {
      default: 'Arial',
      orange: 'Arial',
      citrus: 'Palatino',
      ketchupAndMustard: 'Tahoma',
      lemonade: 'Arial',
      forest: 'Arial',
      watermelon: 'Georgia',
      area51: 'Trebuchet',
      polar: 'Verdana',
      glowInTheDark: 'Tahoma',
      bubblegum: 'Trebuchet',
      millennial: 'Arial',
      robot: 'Tahoma',
      classic: 'Arial'
    },
    fontSize: STANDARD_FONT_SIZE_THEME_VALUES,
    padding: {
      default: NEW_THEME_TEXT_INPUT_PADDING,
      orange: NEW_THEME_TEXT_INPUT_PADDING,
      citrus: NEW_THEME_TEXT_INPUT_PADDING,
      ketchupAndMustard: NEW_THEME_TEXT_INPUT_PADDING,
      lemonade: NEW_THEME_TEXT_INPUT_PADDING,
      forest: NEW_THEME_TEXT_INPUT_PADDING,
      watermelon: NEW_THEME_TEXT_INPUT_PADDING,
      area51: NEW_THEME_TEXT_INPUT_PADDING,
      polar: NEW_THEME_TEXT_INPUT_PADDING,
      glowInTheDark: NEW_THEME_TEXT_INPUT_PADDING,
      bubblegum: NEW_THEME_TEXT_INPUT_PADDING,
      millennial: NEW_THEME_TEXT_INPUT_PADDING,
      robot: NEW_THEME_TEXT_INPUT_PADDING,
      classic: CLASSIC_TEXT_INPUT_PADDING
    }
  },
  dropdown: {
    backgroundColor: {
      type: 'color',
      default: '#FFFFFF',
      orange: '#FFFFFF',
      citrus: '#F7EC60',
      ketchupAndMustard: '#F9DD54',
      lemonade: '#5BB7E7',
      forest: '#A46C15',
      watermelon: '#FF8660',
      area51: '#362F49',
      polar: '#EFFAFF',
      glowInTheDark: '#D9FFD9',
      bubblegum: '#FF7CD0',
      millennial: '#FFFFFF',
      robot: '#B2D9EB',
      classic: '#1ABC9C'
    },
    textColor: {
      type: 'color',
      default: '#4D575F',
      orange: '#000000',
      citrus: '#000000',
      ketchupAndMustard: '#193A55',
      lemonade: '#FFFFFF',
      forest: '#FFFFFF',
      watermelon: '#151F00',
      area51: '#D8FFA7',
      polar: '#0094CA',
      glowInTheDark: '#000000',
      bubblegum: '#FFFFFF',
      millennial: '#442C2E',
      robot: '#353C42',
      classic: '#FFFFFF'
    },
    borderColor: {
      type: 'color',
      default: '#000000',
      orange: '#000000',
      citrus: '#69883D',
      ketchupAndMustard: '#193A55',
      lemonade: '#ACCFDE',
      forest: '#482F08',
      watermelon: '#578B2E',
      area51: '#B394FF',
      polar: '#ACCFDE',
      glowInTheDark: '#5EFF5E',
      bubblegum: '#FFFFFF',
      millennial: '#442C2E',
      robot: '#80A7B9',
      classic: '#000000'
    },
    borderRadius: {
      default: 4,
      orange: 0,
      citrus: 2,
      ketchupAndMustard: 5,
      lemonade: 6,
      forest: 6,
      watermelon: 20,
      area51: 10,
      polar: 20,
      glowInTheDark: 10,
      bubblegum: 20,
      millennial: 20,
      robot: 0,
      classic: 0
    },
    borderWidth: {
      default: 1,
      orange: 2,
      citrus: 2,
      ketchupAndMustard: 0,
      lemonade: 0,
      forest: 2,
      watermelon: 4,
      area51: 2,
      polar: 2,
      glowInTheDark: 2,
      bubblegum: 2,
      millennial: 0,
      robot: 2,
      classic: 0
    },
    fontFamily: {
      default: 'Arial',
      orange: 'Verdana',
      citrus: 'Georgia',
      ketchupAndMustard: 'Georgia',
      lemonade: 'Arial',
      forest: 'Verdana',
      watermelon: 'Georgia',
      area51: 'Arial Black',
      polar: 'Verdana',
      glowInTheDark: 'Tahoma',
      bubblegum: 'Georgia',
      millennial: 'Verdana',
      robot: 'Arial Black',
      classic: 'Arial'
    },
    fontSize: STANDARD_FONT_SIZE_THEME_VALUES,
    padding: {
      default: NEW_THEME_DROPDOWN_PADDING,
      orange: NEW_THEME_DROPDOWN_PADDING,
      citrus: NEW_THEME_DROPDOWN_PADDING,
      ketchupAndMustard: NEW_THEME_DROPDOWN_PADDING,
      lemonade: NEW_THEME_DROPDOWN_PADDING,
      forest: NEW_THEME_DROPDOWN_PADDING,
      watermelon: NEW_THEME_DROPDOWN_PADDING,
      area51: NEW_THEME_DROPDOWN_PADDING,
      polar: NEW_THEME_DROPDOWN_PADDING,
      glowInTheDark: NEW_THEME_DROPDOWN_PADDING,
      bubblegum: NEW_THEME_DROPDOWN_PADDING,
      millennial: NEW_THEME_DROPDOWN_PADDING,
      robot: NEW_THEME_DROPDOWN_PADDING,
      classic: CLASSIC_DROPDOWN_PADDING
    }
  },
  button: {
    backgroundColor: {
      type: 'color',
      default: '#FFA400',
      orange: '#4BC6D0',
      citrus: '#F7EC60',
      ketchupAndMustard: '#F9DD54',
      lemonade: '#5BB7E7',
      forest: '#A46C15',
      watermelon: '#FF8660',
      area51: '#362F49',
      polar: '#EFFAFF',
      glowInTheDark: '#D9FFD9',
      bubblegum: '#FF7CD0',
      millennial: '#442C2E',
      robot: '#B2D9EB',
      classic: '#1ABC9C'
    },
    textColor: {
      type: 'color',
      default: '#FFFFFF',
      orange: '#FFFFFF',
      citrus: '#000000',
      ketchupAndMustard: '#193A55',
      lemonade: '#FFFFFF',
      forest: '#FFFFFF',
      watermelon: '#151F00',
      area51: '#D8FFA7',
      polar: '#0094CA',
      glowInTheDark: '#000000',
      bubblegum: '#FFFFFF',
      millennial: '#FFFFFF',
      robot: '#353C42',
      classic: '#FFFFFF'
    },
    borderColor: {
      type: 'color',
      default: '#4D575F',
      orange: '#FFFFFF',
      citrus: '#69883D',
      ketchupAndMustard: '#193A55',
      lemonade: '#ACCFDE',
      forest: '#482F08',
      watermelon: '#578B2E',
      area51: '#B394FF',
      polar: '#ACCFDE',
      glowInTheDark: '#5EFF5E',
      bubblegum: '#FFFFFF',
      millennial: '#FFFFFF',
      robot: '#80A7B9',
      classic: '#000000'
    },
    borderRadius: {
      default: 4,
      orange: 0,
      citrus: 2,
      ketchupAndMustard: 5,
      lemonade: 6,
      forest: 6,
      watermelon: 20,
      area51: 10,
      polar: 20,
      glowInTheDark: 10,
      bubblegum: 20,
      millennial: 20,
      robot: 0,
      classic: 0
    },
    borderWidth: {
      default: 1,
      orange: 2,
      citrus: 2,
      ketchupAndMustard: 0,
      lemonade: 0,
      forest: 2,
      watermelon: 4,
      area51: 2,
      polar: 2,
      glowInTheDark: 2,
      bubblegum: 2,
      millennial: 0,
      robot: 2,
      classic: 0
    },
    fontFamily: {
      default: 'Arial Black',
      orange: 'Verdana',
      citrus: 'Georgia',
      ketchupAndMustard: 'Georgia',
      lemonade: 'Arial',
      forest: 'Verdana',
      watermelon: 'Georgia',
      area51: 'Arial Black',
      polar: 'Verdana',
      glowInTheDark: 'Tahoma',
      bubblegum: 'Georgia',
      millennial: 'Verdana',
      robot: 'Arial Black',
      classic: 'Arial'
    },
    fontSize: {
      default: 15,
      orange: 15,
      citrus: 15,
      ketchupAndMustard: 15,
      lemonade: 15,
      forest: 15,
      watermelon: 15,
      area51: 15,
      polar: 15,
      glowInTheDark: 15,
      bubblegum: 15,
      millennial: 15,
      robot: 15,
      classic: 14
    }
  },
  textArea: {
    backgroundColor: {
      type: 'color',
      default: '#F2F2F2',
      orange: '#4D3100',
      citrus: '#FFFFFF',
      ketchupAndMustard: '#FFFFFF',
      lemonade: '#FFFFFF',
      forest: '#FFD18A',
      watermelon: '#E2F0AA',
      area51: '#221D30',
      polar: '#0094CA',
      glowInTheDark: '#262B2F',
      bubblegum: '#FFFFFF',
      millennial: '#FEEAE6',
      robot: '#F5F5F6',
      classic: '#FFFFFF'
    },
    textColor: {
      type: 'color',
      default: '#4D575F',
      orange: '#FFFFFF',
      citrus: '#000000',
      ketchupAndMustard: '#193A55',
      lemonade: '#00A8FF',
      forest: '#482F08',
      watermelon: '#151F00',
      area51: '#C4ABFF',
      polar: '#EFFAFF',
      glowInTheDark: '#D9FFD9',
      bubblegum: '#000000',
      millennial: '#442C2E',
      robot: '#353C42',
      classic: '#000000'
    },
    borderColor: {
      type: 'color',
      default: '#FFFFFF',
      orange: '#FFFFFF',
      citrus: '#69883D',
      ketchupAndMustard: '#193A55',
      lemonade: '#193A55',
      forest: '#000000',
      watermelon: '#578B2E',
      area51: '#C4ABFF',
      polar: '#FFFFFF',
      glowInTheDark: '#FFFFFF',
      bubblegum: '#000000',
      millennial: '#FFFFFF',
      robot: '#80A7B9',
      classic: 'rgb(153, 153, 153)'
    },
    borderRadius: {
      default: 2,
      orange: 2,
      citrus: 4,
      ketchupAndMustard: 5,
      lemonade: 6,
      forest: 5,
      watermelon: 20,
      area51: 20,
      polar: 8,
      glowInTheDark: 0,
      bubblegum: 8,
      millennial: 8,
      robot: 0,
      classic: 0
    },
    borderWidth: {
      default: 1,
      orange: 0,
      citrus: 0,
      ketchupAndMustard: 2,
      lemonade: 0,
      forest: 0,
      watermelon: 0,
      area51: 0,
      polar: 2,
      glowInTheDark: 0,
      bubblegum: 0,
      millennial: 0,
      robot: 1,
      classic: 1
    },
    fontFamily: {
      default: 'Arial',
      orange: 'Arial',
      citrus: 'Palatino',
      ketchupAndMustard: 'Tahoma',
      lemonade: 'Arial',
      forest: 'Arial',
      watermelon: 'Georgia',
      area51: 'Trebuchet',
      polar: 'Arial',
      glowInTheDark: 'Tahoma',
      bubblegum: 'Trebuchet',
      millennial: 'Arial',
      robot: 'Tahoma',
      classic: 'Arial'
    },
    fontSize: STANDARD_FONT_SIZE_THEME_VALUES,
    padding: {
      default: NEW_THEME_TEXT_AREA_PADDING,
      orange: NEW_THEME_TEXT_AREA_PADDING,
      citrus: NEW_THEME_TEXT_AREA_PADDING,
      ketchupAndMustard: NEW_THEME_TEXT_AREA_PADDING,
      lemonade: NEW_THEME_TEXT_AREA_PADDING,
      forest: NEW_THEME_TEXT_AREA_PADDING,
      watermelon: NEW_THEME_TEXT_AREA_PADDING,
      area51: NEW_THEME_TEXT_AREA_PADDING,
      polar: NEW_THEME_TEXT_AREA_PADDING,
      glowInTheDark: NEW_THEME_TEXT_AREA_PADDING,
      bubblegum: NEW_THEME_TEXT_AREA_PADDING,
      millennial: NEW_THEME_TEXT_AREA_PADDING,
      robot: NEW_THEME_TEXT_AREA_PADDING,
      classic: CLASSIC_TEXT_AREA_PADDING
    }
  }
};

export default themeValues;
