apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
  - image: toy
    custom:
      buildCommand: k8s/bin/docker-buildx.sh -f k8s/toy/docker/toy.dockerfile --build-arg TOY_BASE="$TOY_BASE"
      dependencies:
        dockerfile:
          path: k8s/toy/docker/toy.dockerfile
    requires:
    - image: toy-base
      alias: TOY_BASE
  - image: toy-base
    custom:
      buildCommand: echo $PWD && k8s/bin/docker-buildx.sh -f k8s/toy/docker/toy-base.dockerfile
      dependencies:
        dockerfile:
          path: k8s/toy/docker/toy-base.dockerfile
deploy:
  helm:
    releases:
      - name: toy
        chartPath: ./k8s/toy/helm
        setValueTemplates:
          image: "{{.IMAGE_FULLY_QUALIFIED_toy}}"
        valuesFiles:
          - k8s/toy/helm/toy.values.yaml

profiles:
- name: run-job
  patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates/job
        value:
          enabled: true
          name: sleep
          args: ["sleep 600"]
