---
transport:
  name: ssh_tgz
driver:
  name: docker
  use_sudo: false
  volume: <%= File.absolute_path(File.join(__dir__, '..', '..')) %>:/home/kitchen/adhoc
provisioner:
  name: chef_zero
  require_chef_omnibus: 11.18.12
  environments_path: test/environments
  client_rb:
    node_name: test_cdo-apps
    environment: adhoc
platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
    attributes:
      cdo-apps:
        dashboard:
          port: 8080
        pegasus:
          port: 8081
      cdo-repository:
        branch: cdo-apps-integration
suites:
  - name: default
    run_list:
      - recipe[cdo-mysql::server]
      - recipe[cdo-apps]
