source 'https://supermarket.chef.io'

metadata
%w(
  repository
  secrets
  postfix
  varnish
  nginx
  github-access
  mysql
  ruby
).each do |dep|
  cookbook "cdo-#{dep}", path: "../cdo-#{dep}"
end
