name: CI Pipeline

on:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MYSQL_ROOT_PASSWORD: root

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Only run this workflow for the user 'pablo-code-dot-org'
    if: github.actor == 'pablo-code-dot-org'

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Environment
        run: |
          docker build -t my-ci-image .

      - name: Run Unit Tests
        run: |
          docker run my-ci-image /bin/bash -c "source docker/unit_test.sh"

      - name: Run UI Tests
        run: |
          docker run my-ci-image /bin/bash -c "source docker/ui_tests.sh"
