module EmailPreferenceConstants
  SOURCE_TYPES = %i(
    ACCOUNT_SIGN_UP
    ACCOUNT_TYPE_CHANGE
    ACCOUNT_EMAIL_ADD
    ACCOUNT_EMAIL_CHANGE
    FORM_HOUR_OF_CODE
    FORM_VOLUNTEER
    FORM_ACCESS_REPORT
    FORM_REGIONAL_PARTNER
  ).freeze
end
