apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: argocd-dex-client-secret
  namespace: {{ .Release.Namespace }}
spec:
  length: 32
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
