'use strict';
const env = require('env.json');

// This variable is set via Ruby code in cloud_formation_stack.yml.erb and passed in when the function is built.
// It should contain the environment-specific domain of the marketing site Cloudfront distribution
const marketingDomain = env.marketingDomain

const marketingPaths = {
  // Add key-value pairs for each path that should be served by the CMS
  // e.g. '/videos': true,
  '/en-US/engineering/all-the-things': true,
  // P-0-1
  "/about/supporters/amazon": true,
  '/computer-science-advanced-placement-data': true,
  "/promote/ap": true,
  "/about/brand-usage": true,
  "/accessibility": true,
  "/commitment": true,
  "/about/annual-report": true,
  "/about/unifying": true,
  "/about/unifying-approach": true,
  "/naipi": true,
  "/curriculum/computer-vision": true,
  "/lms/canvas": true,
  "/lms/schoology": true,
  "/educate/regional-partner": true,
  "/educate/regional-partner/index": true,
  "/educate/resources/posters": true,
  "/lms": true,
  "/beyond/mentors-and-community": true,
  "/beyond/extracurricular": true,
  "/privacy/archive": true,
  "/about/news": true,
  "/about/values": true,
  "/beyond/scholarships": true,
  "/beyond/internships": true,
  "/maker": true,
  "/beyond/extended-learning": true,
  "/educate/district/partners": true,
  "/about/accessibility": true,
  "/about/code-org-free-curriculum-commitment": true,
  "/native-american-and-indigenous-peoples-initiative": true,
  "/integration-with-canvas": true,
  "/integration-with-schoology": true,
  "/professional-learning/regional-partner-program": true,
  "/resources/classroom-posters": true,
  "/learning-management-systems": true,
  "/students/mentorships": true,
  "/students/extracurricular-opportunities": true,
  "/students/scholarships": true,
  "/students/internships-and-apprenticeships": true,
  "/curriculum/maker": true,
  "/students/online-courses": true,
  "/districts/partners": true,
  "/en-US/about/supporters/amazon": true,
  '/en-US/computer-science-advanced-placement-data': true,
  "/en-US/promote/ap": true,
  "/en-US/about/brand-usage": true,
  "/en-US/accessibility": true,
  "/en-US/commitment": true,
  "/en-US/about/annual-report": true,
  "/en-US/about/unifying": true,
  "/en-US/about/unifying-approach": true,
  "/en-US/naipi": true,
  "/en-US/curriculum/computer-vision": true,
  "/en-US/lms/canvas": true,
  "/en-US/lms/schoology": true,
  "/en-US/educate/regional-partner": true,
  "/en-US/educate/regional-partner/index": true,
  "/en-US/educate/resources/posters": true,
  "/en-US/lms": true,
  "/en-US/beyond/mentors-and-community": true,
  "/en-US/beyond/extracurricular": true,
  "/en-US/privacy/archive": true,
  "/en-US/about/news": true,
  "/en-US/about/values": true,
  "/en-US/beyond/scholarships": true,
  "/en-US/beyond/internships": true,
  "/en-US/maker": true,
  "/en-US/beyond/extended-learning": true,
  "/en-US/educate/district/partners": true,
  "/en-US/about/accessibility": true,
  "/en-US/about/code-org-free-curriculum-commitment": true,
  "/en-US/native-american-and-indigenous-peoples-initiative": true,
  "/en-US/integration-with-canvas": true,
  "/en-US/integration-with-schoology": true,
  "/en-US/professional-learning/regional-partner-program": true,
  "/en-US/resources/classroom-posters": true,
  "/en-US/learning-management-systems": true,
  "/en-US/students/mentorships": true,
  "/en-US/students/extracurricular-opportunities": true,
  "/en-US/students/scholarships": true,
  "/en-US/students/internships-and-apprenticeships": true,
  "/en-US/curriculum/maker": true,
  "/en-US/students/online-courses": true,
  "/en-US/districts/partners": true,
  // P-0-2
  "/athome": true,
  "/educate/resources/videos": true,
  "/curriculum/csd": true,
  "/careers-with-cs": true,
  "/careers-with-cs/index": true,
  "/curriculum/middle-school": true,
  "/ai/teaching-assistant": true,
  "/about/careers": true,
  "/curriculum/coding-with-ai": true,
  "/curriculum/game-design": true,
  "/curriculum/how-ai-works": true,
  "/diversity": true,
  "/curriculum/generative-ai": true,
  "/curriculum/csp": true,
  "/ai/pl/101": true,
  "/educate/weblab": true,
  "/parents": true,
  "/resources/videos": true,
  "/curriculum/computer-science-discoveries": true,
  "/students/careers-in-computer-science": true,
  "/artificial-intelligence/teaching-assistant": true,
  "/curriculum/coding-with-artificial-intelligence": true,
  "/curriculum/how-artificial-intelligence-works": true,
  "/about/diversity": true,
  "/curriculum/exploring-generative-artificial-intelligence": true,
  "/curriculum/computer-science-principles": true,
  "/professional-learning/artificial-intelligence-101": true,
  "/tools/web-lab": true,
  "/en-US/athome": true,
  "/en-US/educate/resources/videos": true,
  "/en-US/curriculum/csd": true,
  "/en-US/careers-with-cs": true,
  "/en-US/careers-with-cs/index": true,
  "/en-US/curriculum/middle-school": true,
  "/en-US/ai/teaching-assistant": true,
  "/en-US/about/careers": true,
  "/en-US/curriculum/coding-with-ai": true,
  "/en-US/curriculum/game-design": true,
  "/en-US/curriculum/how-ai-works": true,
  "/en-US/diversity": true,
  "/en-US/curriculum/generative-ai": true,
  "/en-US/curriculum/csp": true,
  "/en-US/ai/pl/101": true,
  "/en-US/educate/weblab": true,
  "/en-US/parents": true,
  "/en-US/resources/videos": true,
  "/en-US/curriculum/computer-science-discoveries": true,
  "/en-US/students/careers-in-computer-science": true,
  "/en-US/artificial-intelligence/teaching-assistant": true,
  "/en-US/curriculum/coding-with-artificial-intelligence": true,
  "/en-US/curriculum/how-artificial-intelligence-works": true,
  "/en-US/about/diversity": true,
  "/en-US/curriculum/exploring-generative-artificial-intelligence": true,
  "/en-US/curriculum/computer-science-principles": true,
  "/en-US/professional-learning/artificial-intelligence-101": true,
  "/en-US/tools/web-lab": true,
  "/privacy/dpa/il": true,
  "/donate/policy": true,
  "/educate/it": true,
  "/districts": true,
  "/privacy/data-privacy-addendum-illinois": true,
  "/about/it-requirements": true,
  "/terms-of-service": true,
  "/privacy/dpa/mt": true,
  "/privacy/data-privacy-addendum-montana": true,
  "/privacy/dpa/ny": true,
  "/privacy/data-privacy-addendum-new-york": true,
  "/privacy/dpa": true,
  "/privacy/data-privacy-addendum": true,
  "/professional-learning/elementary": true,
  "/professional-learning/middle-high": true,
  "/en-US/privacy/dpa/il": true,
  "/en-US/donate/policy": true,
  "/en-US/educate/it": true,
  "/en-US/districts": true,
  "/en-US/privacy/data-privacy-addendum-illinois": true,
  "/en-US/about/it-requirements": true,
  "/en-US/terms-of-service": true,
  "/en-US/privacy/dpa/mt": true,
  "/en-US/privacy/data-privacy-addendum-montana": true,
  "/en-US/privacy/dpa/ny": true,
  "/en-US/privacy/data-privacy-addendum-new-york": true,
  "/en-US/privacy/dpa": true,
  "/en-US/privacy/data-privacy-addendum": true,
  "/en-US/professional-learning/elementary": true,
  "/en-US/professional-learning/middle-high": true,
  // P-0-3
  "/student/middle-high": true,
  "/student/elementary": true,
  "/about/hear-from-us": true,
  "/students": true,
  "/curriculum/elementary-school": true,
  "/about": true,
  "/educate/gamelab": true,
  "/tools/applab": true,
  "/promote": true,
  "/curriculum/csf": true,
  "/educate/spritelab": true,
  "/about/supporters": true,
  "/tos": true,
  "/privacy": true,
  "/en-US/student/middle-high": true,
  "/en-US/student/elementary": true,
  "/en-US/about/hear-from-us": true,
  "/en-US/students": true,
  "/en-US/curriculum/elementary-school": true,
  "/en-US/about": true,
  "/en-US/educate/gamelab": true,
  "/en-US/tools/applab": true,
  "/en-US/promote": true,
  "/en-US/curriculum/csf": true,
  "/en-US/educate/spritelab": true,
  "/en-US/about/supporters": true,
  "/en-US/tos": true,
  "/en-US/privacy": true,
  // May 30
  "/tools": true,
  "/tools/musiclab": true,
  "/professional-learning": true,
  "/professional-learning/self-paced": true,
  "/curriculum/csa": true,
  "/curriculum/high-school": true,
  "/ai": true,
  "/administrators": true,
  "/teach": true,
  "/curriculum/cs-ai-foundations": true,
  "/curriculum/csc": true,
  "/students/middle-and-high-school": true,
  "/students/elementary": true,
  "/about/hear-from-code": true,
  "/tools/game-lab": true,
  "/tools/app-lab": true,
  "/promote-computer-science": true,
  "/curriculum/computer-science-fundamentals": true,
  "/tools/sprite-lab": true,
  "/tools/music-lab": true,
  "/professional-learning/self-paced-courses": true,
  "/curriculum/computer-science-a": true,
  "/artificial-intelligence": true,
  "/teachers": true,
  "/curriculum/artificial-intelligence-foundations": true,
  "/tools/python-lab": true,
  "/curriculum/computer-science-connections": true,
  "/en-US/tools": true,
  "/en-US/tools/musiclab": true,
  "/en-US/professional-learning": true,
  "/en-US/professional-learning/self-paced": true,
  "/en-US/curriculum/csa": true,
  "/en-US/curriculum/high-school": true,
  "/en-US/ai": true,
  "/en-US/administrators": true,
  "/en-US/teach": true,
  "/en-US/curriculum/cs-ai-foundations": true,
  "/en-US/curriculum/csc": true,
  "/en-US/students/middle-and-high-school": true,
  "/en-US/students/elementary": true,
  "/en-US/about/hear-from-code": true,
  "/en-US/tools/game-lab": true,
  "/en-US/tools/app-lab": true,
  "/en-US/promote-computer-science": true,
  "/en-US/curriculum/computer-science-fundamentals": true,
  "/en-US/tools/sprite-lab": true,
  "/en-US/tools/music-lab": true,
  "/en-US/professional-learning/self-paced-courses": true,
  "/en-US/curriculum/computer-science-a": true,
  "/en-US/artificial-intelligence": true,
  "/en-US/teachers": true,
  "/en-US/curriculum/artificial-intelligence-foundations": true,
  "/en-US/tools/python-lab": true,
  "/en-US/curriculum/computer-science-connections": true,
  // Farsi Redirects
  "/global/fa/csf": true,
  "/global/fa": true,
  "/global/fa/hourofcode": true,
  "/global/fa/videos": true,
  "/global/fa/about": true,
  "/global/fa/teacher": true,
  "/google6b89cac223982bf9": true,
  "/farsi": true,
  // Post Launch 1
  "/afe": true,
  "/music": true,
  "/helloworld": true,
  "/minecraft": true,
  "/beyond": true,
  "/afe/start-codeorg": true,
  "/afe/success": true,
  "/careers-with-cs/k5": true,
  "/csjourneys/cs-in-college": true,
  "/csjourneys/csadventures": true,
  "/csjourneys/engage-parents": true,
  "/csjourneys/index": true,
  "/csjourneys/nextsteps": true,
  "/csjourneys/pastchats": true,
  "/curriculum/3rd-party": true,
  "/help": true,
  "/maker/circuitplayground": true,
  "/maker/microbit": true,
  "/maker/pick-a-device": true,
  "/promote/thanks": true,
  "/pluralsight": true,
  "/project-ideas": true,
  "/quotes": true,
  "/youngwomen": true,
  "/afe/india": true,
  "/girls": true,
  "/translate": true,
  "/hour-of-code/music": true,
  "/hour-of-code/helloworld": true,
  "/hour-of-code/minecraft": true,
  "/incubator": true,
  "/resources/amazon-future-engineer": true,
  "/starwars": true,
  "/hour-of-code/starwars": true,
  "/engineering/all-the-things": true,
  "/hourofcode": true,
  "/hour-of-code": true,
  "/csjourneys": true,
  "/dance": true,
  "/hour-of-code/dance": true,
  // Post Launch 2
  "/donate": true,
  "/poetry": true,
  "/transformersone": true,
  "/hour-of-code/poetry": true,
  "/hour-of-code/transformersone": true,
  "/districts/program/coaches-network": true,
  // Home Page
  "/": true,
  // Post Launch 3
  "/api/health_check": true,
  "/about/partners": true,
  "/privacy/cookies": true,
  "/about/team": true,
  "/about/leadership": true,
  // CSAIF
  "/csaif": true,
  // Post Launch 4
  "/your-school": true,
  "/yourschool": true,
  "/yourschool/thankyou": true,
  "/about/team-pets": true,
  "/sitemap.xml": true,
  "/hour-of-ai": true,
  "/hourofai": true,
  "/curriculum/blockchain": true,
  "/blockchain": true,
  "/curriculum/music": true,
  "/security": true,
  "/about/geocode_test": true,
  "/teacher-dashboard": true,
  "/minecraft*": true,
  "/learn": true,
  "/oceans ": true,
  "/professional-learning/contact-regional-partner": true,
  "/rp-contact-form-alt": true,
  "/international/apply": true,
  "/professional-learning/international-partners": true,
  "/professional-learning/international": true,
  "/hourofcode/overview": true,
  "/hourofcode/mc": true,
  "/about/InformationSecurityPolicy.pdf": true,
  "/promote*": true,
  "/curriculum*": true,
  "/about/it": true,
  "/events": true,
  "/events/conferences": true,
  "/professional-learning/regional-partner-program/resources": true,
  "/index": true,
  "/educate": true,
  "/international/about.es-mx": true,
  "/student": true,
  "/educate/regional-partner/612": true,
  "/educate/regional-partner/general": true,
  "/educate/regional-partner/k5": true,
  "/educate/weblab-test": true,
  // Post Launch 5
  "/Apply": true,
  "/Dance": true,
  "/Minecraft": true,
  "/about/2014": true,
  "/about/2015": true,
  "/about/2016": true,
  "/about/2017": true,
  "/about/2018": true,
  "/about/2019": true,
  "/about/2020": true,
  "/about/2021": true,
  "/about/2022": true,
  "/about/2023": true,
  "/about/donation-policy": true,
  "/about/donors": true,
  "/about/education-leadership-council": true,
  "/about/evaluation/costs": true,
  "/about/evaluation/hourofcode": true,
  "/about/evaluation/learning": true,
  "/about/evaluation/outcomes": true,
  "/about/evaluation/partners": true,
  "/about/evaluation/pd": true,
  "/about/evaluation/proficiency": true,
  "/about/evaluation/proficiency2016": true,
  "/about/evaluation/summary": true,
  "/about/evaluation": true,
  "/about/jobs": true,
  "/action/make-cs-count": true,
  "/advocacy": true,
  "/advocacy/state-facts": true,
  "/advocacy/state-of-cs/2023_state_of_cs.pdf": true,
  "/ai/how-ai-works": true,
  "/ai-ta": true,
  "/ai101": true,
  "/aivideos": true,
  "/artificial-intelligence#ai-videos": true,
  "/alternative-classrooms": true,
  "/ap": true,
  "/applab": true,
  "/apply": true,
  "/athletes": true,
  "/bingo": true,
  "/blackhistorymonth": true,
  "/bounce": true,
  "/break": true,
  "/careers": true,
  "/certificate": true,
  "/certificates/blank": true,
  "/certificates": true,
  "/circuitplayground": true,
  "/codebytes": true,
  "/hour-of-code/": true,
  "/community": true,
  "/contact": true,
  "/cookies": true,
  "/cps": true,
  "/csa": true,
  "/csc": true,
  "/csd-pre-survey": true,
  "/csd": true,
  "/csf": true,
  "/csjourneys/myjourneychats": true,
  "/csp/pd": true,
  "/csp-pre-survey": true,
  "/csp": true,
  "/curriculum/unplugged": true,
  "/curriculum/values": true,
  "/dataportal": true,
  "/district-partner": true,
  "/district": true,
  "/donate/amazon": true,
  "/donate/crypto": true,
  "/dpa-il": true,
  "/dpa-mt": true,
  "/dpa-ny": true,
  "/dpa": true,
  "/educate/allhourofcode": true,
  "/educate/applab": true,
  "/educate/community": true,
  "/educate/csa": true,
  "/educate/csc": true,
  "/educate/csd": true,
  "/educate/csf": true,
  "/educate/csp/unit1": true,
  "/educate/csp/unit2": true,
  "/educate/csp/unit3": true,
  "/educate/csp/unit4": true,
  "/educate/csp/unit5": true,
  "/educate/csp/unit6": true,
  "/educate/csp/widgets": true,
  "/educate/csp": true,
  "/educate/curriculum/3rd-party/apcsa": true,
  "/educate/curriculum/3rd-party": true,
  "/educate/curriculum/apcsa": true,
  "/educate/curriculum/cs-fundamentals-international": true,
  "/educate/curriculum/csf-transition-guide": true,
  "/educate/curriculum/csf": true,
  "/educate/curriculum/elementary-school": true,
  "/educate/curriculum/express-course": true,
  "/educate/curriculum/high-school": true,
  "/educate/curriculum/middle-school": true,
  "/educate/curriculum/values": true,
  "/educate/curriculum": true,
  "/educate/district/agreement": true,
  "/educate/district/interest-form": true,
  "/educate/district/k5-partnership": true,
  "/educate/district/qualify": true,
  "/educate/district/terms": true,
  "/educate/facilitator-landing/CSA": true,
  "/educate/facilitator-landing/CSD": true,
  "/educate/facilitator-landing/CSF": true,
  "/educate/facilitator-landing/CSP": true,
  "/educate/partner/district-partners": true,
  "/educate/pd": true,
  "/educate/professional-development-online": true,
  "/educate/professional-development-philosophy": true,
  "/educate/professional-development": true,
  "/educate/professional-learning/about-partners": true,
  "/educate/professional-learning/contact-regional-partner": true,
  "/educate/professional-learning/cs-fundamentals-facilitator": true,
  "/educate/professional-learning/cs-fundamentals-resources": true,
  "/educate/professional-learning/facilitator": true,
  "/educate/professional-learning/middle-high": true,
  "/educate/professional-learning/professional-development-deep-dive": true,
  "/educate/professional-learning/program-information": true,
  "/educate/professional-learning/values": true,
  "/educate/professional-learning-partner": true,
  "/educate/professional-learning": true,
  "/educate/regional-partner/partners": true,
  "/educate/regional-partner/playbook": true,
  "/educate/resources": true,
  "/emailprivacy": true,
  "/envivo": true,
  "/ethical-ai-panel": true,
  "/express": true,
  "/faq": true,
  "/flappy": true,
  "/flappybird": true,
  "/frequency": true,
  "/frozen": true,
  "/gamelab": true,
  "/girlscouts/BuildingaFoundation/DemoVideo": true,
  "/girlscouts/BuildingaFoundation/NeverGiveUpVideo": true,
  "/girlscouts/BuildingaFoundation/OverviewVideo": true,
  "/girlscouts/ComputationalThinking/ActivityVideo": true,
  "/girlscouts/ComputationalThinking/DemoVideo": true,
  "/girlscouts/ComputationalThinking/OverviewVideo": true,
  "/girlscouts/ComputationalThinkingwithMonsters/ActivityVideo": true,
  "/girlscouts/FunctionalSuncatchers/ActivityVideo": true,
  "/girlscouts/FunctionalSuncatchers/DemoVideo": true,
  "/girlscouts/FunctionalSuncatchers/OverviewVideo": true,
  "/girlscouts/GraphPaperProgramming/ActivityVideo": true,
  "/girlscouts/GraphPaperProgramming/DemoVideo": true,
  "/girlscouts/GraphPaperProgramming/OverviewVideo": true,
  "/girlscouts/HappyMaps/ActivityVideo": true,
  "/girlscouts/HappyMaps/OverviewVideo": true,
  "/girlscouts/MadGlibs/ActivityVideo": true,
  "/girlscouts/MadGlibs/OverviewVideo": true,
  "/girlscouts/MoveItMoveIt/ActivityVideo": true,
  "/girlscouts/MoveItMoveIt/OverviewVideo": true,
  "/girlscouts/PlantaSeed/ActivityVideo": true,
  "/girlscouts/PlantaSeed/OverviewVideo": true,
  "/girlscouts/RelayPaperProgramming/ActivityVideo": true,
  "/girlscouts/RelayPaperProgramming/OverviewVideo": true,
  "/girlscouts/TangramAlgorithms/ActivityVideo": true,
  "/girlscouts/TangramAlgorithms/OverviewVideo": true,
  "/globalpd": true,
  "/highschool": true,
  "/hourofcode/artist": true,
  "/hourofcode/flappy": true,
  "/hourofcode/frozen": true,
  "/hourofcode/hour-of-code": true,
  "/hourofcode/hourofcode": true,
  "/hourofcode/infinity": true,
  "/hourofcode/minecraft": true,
  "/hourofcode/playlab": true,
  "/hourofcode/star-wars": true,
  "/hourofcode/starwars": true,
  "/hourofcode/unplugged-conditionals-with-cards": true,
  "/hourofcode2022": true,
  "/international/about": true,
  "/international": true,
  "/internetsimulator": true,
  "/join": true,
  "/k5": true,
  "/learn/beyond": true,
  "/learn/codecademy": true,
  "/learn/codehs": true,
  "/learn/khan-academy": true,
  "/learn/legacy": true,
  "/learn/local": true,
  "/learn/robotics": true,
  "/learn/scratch": true,
  "/learn2": true,
  "/lesson_plans": true,
  "/maker/csf-microbit": true,
  "/maker/setup": true,
  "/matching-gifts": true,
  "/mc": true,
  "/mobile": true,
  "/musiclab": true,
  "/netsim": true,
  "/ocean": true,
  "/oceans": true,
  "/odometer": true,
  "/online-pl": true,
  "/outbreak": true,
  "/partners": true,
  "/pd": true,
  "/pixelation": true,
  "/playlab": true,
  "/prereader": true,
  "/privacy/apr2016": true,
  "/privacy/apr2018": true,
  "/privacy/dec2014": true,
  "/privacy/dec2022": true,
  "/privacy/jul2021": true,
  "/privacy/jun2023": true,
  "/privacy/mar2021": true,
  "/privacy/may2018": true,
  "/privacy/nov2021": true,
  "/privacy/oct2022": true,
  "/privacy/sept2020": true,
  "/privacy/student-privacy-csd": true,
  "/privacy/student-privacy-csp": true,
  "/privacy/student-privacy": true,
  "/privacy-dec2022": true,
  "/privacy-jul2021": true,
  "/privacy-jun2023": true,
  "/privacy-letter": true,
  "/privacy-mar2021": true,
  "/privacy-may2018": true,
  "/privacy-nov2021": true,
  "/privacy-oct2022": true,
  "/privacy-sep2020": true,
  "/privacy_letter": true,
  "/professional-development-deep-dive": true,
  "/professional-development-workshops": true,
  "/professional-learning/facilitator": true,
  "/professional-learning/values": true,
  "/promote/diversitydata": true,
  "/promote/morestats": true,
  "/publickey": true,
  "/pwc": true,
  "/questions": true,
  "/report_abuse": true,
  "/schools/new": true,
  "/schools": true,
  "/sharecertificate": true,
  "/shop": true,
  "/sports": true,
  "/spritelab": true,
  "/star-wars-announcement": true,
  "/star": true,
  "/startrek": true,
  "/starwars-download": true,
  "/statistics": true,
  "/stats": true,
  "/student/beyondk12": true,
  "/student/hsgrads": true,
  "/student/university": true,
  "/studio": true,
  "/support": true,
  "/textcompression": true,
  "/verified": true,
  "/videos": true,
  "/vigenere": true,
  "/weblab": true,
  "/widgets": true,
  "/yourschool/accessreport": true,
  "/global": true,
  "/events/information-sessions": true,
  // Course 1-4 Lesson Plans
  "/curriculum/course1/1/Teacher": true,
  "/curriculum/course1/2/Teacher": true,
  "/curriculum/course1/3/Teacher": true,
  "/curriculum/course1/4/Teacher": true,
  "/curriculum/course1/5/Teacher": true,
  "/curriculum/course1/6/Teacher": true,
  "/curriculum/course1/7/Teacher": true,
  "/curriculum/course1/8/Teacher": true,
  "/curriculum/course1/9/Teacher": true,
  "/curriculum/course1/10/Teacher": true,
  "/curriculum/course1/11/Teacher": true,
  "/curriculum/course1/12/Teacher": true,
  "/curriculum/course1/13/Teacher": true,
  "/curriculum/course1/14/Teacher": true,
  "/curriculum/course1/15/Teacher": true,
  "/curriculum/course1/16/Teacher": true,
  "/curriculum/course1/17/Teacher": true,
  "/curriculum/course1/18/Teacher": true,
  "/curriculum/course2/1/Teacher": true,
  "/curriculum/course2/2/Teacher": true,
  "/curriculum/course2/3/Teacher": true,
  "/curriculum/course2/4/Teacher": true,
  "/curriculum/course2/5/Teacher": true,
  "/curriculum/course2/6/Teacher": true,
  "/curriculum/course2/7/Teacher": true,
  "/curriculum/course2/8/Teacher": true,
  "/curriculum/course2/9/Teacher": true,
  "/curriculum/course2/10/Teacher": true,
  "/curriculum/course2/11/Teacher": true,
  "/curriculum/course2/12/Teacher": true,
  "/curriculum/course2/13/Teacher": true,
  "/curriculum/course2/14/Teacher": true,
  "/curriculum/course2/15/Teacher": true,
  "/curriculum/course2/16/Teacher": true,
  "/curriculum/course2/17/Teacher": true,
  "/curriculum/course2/18/Teacher": true,
  "/curriculum/course2/19/Teacher": true,
  "/curriculum/course3/1/Teacher": true,
  "/curriculum/course3/2/Teacher": true,
  "/curriculum/course3/3/Teacher": true,
  "/curriculum/course3/4/Teacher": true,
  "/curriculum/course3/5/Teacher": true,
  "/curriculum/course3/6/Teacher": true,
  "/curriculum/course3/7/Teacher": true,
  "/curriculum/course3/8/Teacher": true,
  "/curriculum/course3/9/Teacher": true,
  "/curriculum/course3/10/Teacher": true,
  "/curriculum/course3/11/Teacher": true,
  "/curriculum/course3/12/Teacher": true,
  "/curriculum/course3/13/Teacher": true,
  "/curriculum/course3/14/Teacher": true,
  "/curriculum/course3/15/Teacher": true,
  "/curriculum/course3/16/Teacher": true,
  "/curriculum/course3/17/Teacher": true,
  "/curriculum/course3/18/Teacher": true,
  "/curriculum/course3/19/Teacher": true,
  "/curriculum/course3/20/Teacher": true,
  "/curriculum/course3/21/Teacher": true,
  "/curriculum/course4/1/Teacher": true,
  "/curriculum/course4/2/Teacher": true,
  "/curriculum/course4/3/Teacher": true,
  "/curriculum/course4/4/Teacher": true,
  "/curriculum/course4/5/Teacher": true,
  "/curriculum/course4/6/Teacher": true,
  "/curriculum/course4/7/Teacher": true,
  "/curriculum/course4/9/Teacher": true,
  "/curriculum/course4/8/Teacher": true,
  "/curriculum/course4/10/Teacher": true,
  "/curriculum/course4/11/Teacher": true,
  "/curriculum/course4/12/Teacher": true,
  "/curriculum/course4/13/Teacher": true,
  "/curriculum/course4/14/Teacher": true,
  "/curriculum/course4/15/Teacher": true,
  "/curriculum/course4/16/Teacher": true,
  "/curriculum/course4/17/Teacher": true,
  "/curriculum/course4/18/Teacher": true,
  "/curriculum/course4/19/Teacher": true,
  "/curriculum/course4/20/Teacher": true,
  "/curriculum/course4/21/Teacher": true,
  "/curriculum/course4/22/Teacher": true,
  // Promote paths
  "/promote/al": true,
  "/promote/ak": true,
  "/promote/az": true,
  "/promote/ar": true,
  "/promote/ca": true,
  "/promote/co": true,
  "/promote/ct": true,
  "/promote/de": true,
  "/promote/fl": true,
  "/promote/ga": true,
  "/promote/hi": true,
  "/promote/id": true,
  "/promote/il": true,
  "/promote/in": true,
  "/promote/ia": true,
  "/promote/ks": true,
  "/promote/ky": true,
  "/promote/la": true,
  "/promote/me": true,
  "/promote/md": true,
  "/promote/ma": true,
  "/promote/mi": true,
  "/promote/mn": true,
  "/promote/ms": true,
  "/promote/mo": true,
  "/promote/mt": true,
  "/promote/ne": true,
  "/promote/nv": true,
  "/promote/nh": true,
  "/promote/nj": true,
  "/promote/nm": true,
  "/promote/ny": true,
  "/promote/nc": true,
  "/promote/nd": true,
  "/promote/oh": true,
  "/promote/ok": true,
  "/promote/or": true,
  "/promote/pa": true,
  "/promote/ri": true,
  "/promote/sc": true,
  "/promote/sd": true,
  "/promote/tn": true,
  "/promote/tx": true,
  "/promote/ut": true,
  "/promote/vt": true,
  "/promote/va": true,
  "/promote/wa": true,
  "/promote/wv": true,
  "/promote/wi": true,
  "/promote/wy": true,
  "/back-to-school-kit": true,
  "/global/partners": true,
  "/global/india": true,
  "/back-to-school-for-district": true,
  "/india": true,
  "/global/cuantrix": true,
}

const pathPatterns = [
  /^\/_next\/static\//, // Next.js static assets
  /^\/forms\//,         // /forms/*
  /^\/schools\//,       // /schools/*
  /^\/applab\/docs\//,  // /applab/docs/*
  /^\/educate\//,       // /educate/*
];

const SUPPORTED_LOCALES = new Set([
  'en-US',
  'es',
  'ar',
  'cs',
  'de',
  'es-ES',
  'es-LA',
  'fa',
  'fr',
  'hi',
  'id',
  'it',
  'ja',
  'ko',
  'kn',
  'mr',
  'pl',
  'pt-BR',
  'sk',
  'ta',
  'te',
  'th',
  'tr',
  'uk',
  'vi',
  'zh-CN',
  'zh-TW',
  'sq',
  'tl',
  'he',
]);

// Remove the localized portion of paths, if there is a localized portion.
// For example:
// 1. /en-US/engineering/all-the-things becomes /engineering/all-the-things
// 2. /engineering/all-the-things remains unchanged
function extractPaths(uri) {
  const parts = uri.split('/').filter(Boolean); // Remove empty segments
  const localeRegex = /^[a-z]{2}(-[A-Z]{2})?$/;

  if (parts.length && localeRegex.test(parts[0]) && SUPPORTED_LOCALES.has(parts[0])) {
    // Has locale, return everything after locale
    return '/' + parts.slice(1).join('/');
  }

  // No locale, return as-is
  return uri;
}

module.exports.handler = (event, context, callback) => {
  try {
    const request = event?.Records?.[0]?.cf?.request;
    const uri = request?.uri;
    const normalizedURI = extractPaths(uri);

    // Set CMS origin if the requested path matches
    if (marketingPaths[normalizedURI] || (uri && pathPatterns.some(pattern => pattern.test(uri)))) {
      request.origin = {
        custom: {
          domainName: marketingDomain,
          port: 443,
          protocol: 'https',
          path: '',
          sslProtocols: ['TLSv1.2'],
          readTimeout: 30,
          keepaliveTimeout: 5,
          customHeaders: {},
        },
      };
  
      // Update the Host header to match the new origin
      request.headers['host'] = [{ key: 'Host', value: marketingDomain }];
    }
  
    callback(null, request);
  } catch (error) {
    console.error('Marketing router lambda error:', error);

    // If an error occurs, don't block. Pass through the request.
    callback(null, request);
  }
};
