export const testSection = {
  id: 11,
  courseId: 29,
  courseOfferingId: 2,
  courseVersionId: 3,
  unitId: null,
  name: 'my_section',
  loginType: 'word',
  grades: ['3'],
  providerManaged: false,
  lessonExtras: false,
  ttsAutoplayEnabled: false,
  pairingAllowed: true,
  studentCount: 10,
  code: 'PMTKVH',
  participantType: 'student',
};
export const noStudentsSection = {
  id: 11,
  courseId: 29,
  courseOfferingId: 2,
  courseVersionId: 3,
  unitId: null,
  name: 'my_section',
  loginType: 'word',
  grades: ['3'],
  providerManaged: false,
  lessonExtras: false,
  ttsAutoplayEnabled: false,
  pairingAllowed: true,
  studentCount: 0,
  code: 'PMTKVH',
  participantType: 'student',
};

export const courseOfferings = {
  1: {
    id: 1,
    display_name: 'Course A',
    is_featured: false,
    participant_audience: 'student',
    course_versions: {
      1: {
        id: 1,
        key: '2017',
        version_year: '2017',
        content_root_id: 1,
        name: 'Course A',
        path: '/courses/coursea-2017',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: false,
        locale_codes: ['fa-AF', 'cs-CZ', 'de-DE', 'en-US'],
        locales: ['العربية', 'Čeština', 'Deutsch', 'English'],
        units: {
          1: {
            id: 1,
            name: 'Course A',
            path: '/courses/coursea-2017/units/1',
            lesson_extras_available: true,
            position: null,
          },
        },
      },
      2: {
        id: 2,
        key: '2018',
        version_year: '2018',
        content_root_id: 2,
        name: 'Course A',
        path: '/courses/coursea-2018',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: true,
        locale_codes: ['en-US', 'it-IT', 'sk-SK'],
        locales: ['English', 'Italiano', 'Slovenčina'],
        units: {
          2: {
            id: 2,
            name: 'Course A (2018)',
            path: '/courses/coursea-2018/units/1',
            lesson_extras_available: true,
            position: null,
          },
        },
      },
    },
  },
  2: {
    id: 2,
    display_name: 'Computer Science Discoveries',
    is_featured: false,
    participant_audience: 'student',
    course_versions: {
      3: {
        id: 3,
        key: '2017',
        version_year: "'17-'18",
        content_root_id: 52,
        name: 'CS Discoveries 2017',
        path: '/courses/csd-2017',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: false,
        locale_codes: [],
        locales: [],
        units: {
          3: {
            id: 3,
            name: 'Unit 1',
            path: '/courses/csd-2017/units/1',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: 1,
          },
          4: {
            id: 4,
            name: 'Unit 2',
            path: '/courses/csd-2017/units/2',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: 2,
          },
        },
      },
      4: {
        id: 4,
        key: '2018',
        version_year: "'18-'19",
        content_root_id: 51,
        name: 'CS Discoveries 2018',
        path: '/courses/csd-2018',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: true,
        locale_codes: [],
        locales: [],
        units: {
          5: {
            id: 5,
            name: 'Unit 1',
            path: '/courses/csd-2018/units/1',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: 1,
          },
          6: {
            id: 6,
            name: 'Unit 2',
            path: '/courses/csd-2018/units/2',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: 2,
          },
        },
      },
    },
  },
  3: {
    id: 3,
    display_name: 'Computer Science A',
    is_featured: false,
    participant_audience: 'student',
    course_versions: {
      5: {
        id: 5,
        key: '2022',
        version_year: '2022',
        content_root_id: 50,
        name: 'CS A',
        path: '/courses/csa-2022',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: true,
        locale_codes: [],
        locales: [],
        units: {
          7: {
            id: 7,
            name: 'Unit 1',
            path: '/courses/csa-2022/units/1',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: 1,
          },
          8: {
            id: 8,
            name: 'Unit 2',
            path: '/courses/csa-2022/units/2',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: 2,
          },
        },
      },
    },
  },
  4: {
    id: 4,
    display_name: 'Flappy',
    is_featured: false,
    participant_audience: 'student',
    course_versions: {
      6: {
        id: 6,
        key: 'unversioned',
        version_year: 'unversioned',
        content_root_id: 9,
        name: 'Flappy',
        path: '/courses/flappy',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: false,
        locale_codes: [],
        locales: [],
        units: {
          9: {
            id: 9,
            name: 'Flappy',
            path: '/courses/flappy/units/1',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: null,
          },
        },
      },
    },
  },
  5: {
    id: 5,
    display_name: 'Hello World',
    is_featured: true,
    participant_audience: 'student',
    course_versions: {
      7: {
        id: 7,
        key: 'unversioned',
        version_year: 'unversioned',
        content_root_id: 10,
        name: 'Hello World',
        path: '/courses/hello-world',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: true,
        locale_codes: [],
        locales: [],
        units: {
          10: {
            id: 10,
            name: 'Hello World',
            path: '/courses/hello-world/units/1',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: null,
          },
        },
      },
    },
  },
  6: {
    id: 6,
    display_name: 'Poem Art',
    is_featured: true,
    participant_audience: 'student',
    course_versions: {
      8: {
        id: 8,
        key: 'unversioned',
        version_year: 'unversioned',
        content_root_id: 11,
        name: 'Poem Art',
        path: '/courses/poem-art',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: true,
        locale_codes: [],
        locales: [],
        units: {
          11: {
            id: 11,
            name: 'Poem Art',
            path: '/courses/poem-art/units/1',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: null,
          },
        },
      },
    },
  },
  7: {
    id: 7,
    display_name: 'Artist',
    is_featured: false,
    participant_audience: 'student',
    course_versions: {
      9: {
        id: 9,
        key: 'unversioned',
        version_year: 'unversioned',
        content_root_id: 12,
        name: 'Artist',
        path: '/courses/artist',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: true,
        locale_codes: [],
        locales: [],
        units: {
          12: {
            id: 12,
            name: 'Artist',
            path: '/courses/artist/units/1',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: null,
          },
        },
      },
    },
  },
  8: {
    id: 8,
    display_name: 'Self Paced PL CSP',
    is_featured: false,
    participant_audience: 'teacher',
    course_versions: {
      10: {
        id: 10,
        key: '2021',
        version_year: '2021',
        content_root_id: 53,
        name: 'Self Paced PL CSP 2021',
        path: '/courses/self-paced-pl-csp-2021',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: true,
        locale_codes: [],
        locales: [],
        units: {
          13: {
            id: 13,
            name: 'Unit 1',
            path: '/courses/self-paced-pl-csp-2021/units/1',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: 1,
          },
          14: {
            id: 14,
            name: 'Unit 2',
            path: '/courses/self-paced-pl-csp-2021/units/2',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: 2,
          },
        },
      },
    },
  },
  9: {
    id: 9,
    display_name: 'Virtual PL CSP',
    is_featured: false,
    participant_audience: 'teacher',
    course_versions: {
      11: {
        id: 11,
        key: '2020',
        version_year: '2020',
        content_root_id: 15,
        name: 'Virtual PL CSP 2020',
        path: '/courses/vpl-csp-2020',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: true,
        locale_codes: [],
        locales: [],
        units: {
          15: {
            id: 15,
            name: 'Virtual PL CSP 2020',
            path: '/courses/vpl-csp-2020/units/1',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: null,
          },
        },
      },
      12: {
        id: 12,
        key: '2021',
        version_year: '2021',
        content_root_id: 16,
        name: 'Virtual PL CSP 2021',
        path: '/courses/vpl-csp-2021',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: true,
        locale_codes: [],
        locales: [],
        units: {
          16: {
            id: 16,
            name: 'Virtual PL CSP 2021',
            path: '/courses/vpl-csp-2021/units/1',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: null,
          },
        },
      },
    },
  },
  10: {
    id: 10,
    display_name: 'Single Unit Course',
    is_featured: false,
    participant_audience: 'student',
    course_versions: {
      13: {
        id: 13,
        key: '2025',
        version_year: '2025',
        content_root_id: 17,
        name: 'Single Unit Course 2025',
        path: '/courses/single-unit-course-2025',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: false,
        locale_codes: [],
        locales: [],
        units: {
          17: {
            id: 17,
            name: 'Single Unit 2025',
            path: '/courses/single-unit-course-2025/units/1',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: null,
          },
        },
      },
      14: {
        id: 14,
        key: '2026',
        version_year: '2026',
        content_root_id: 18,
        name: 'Single Unit Course 2026',
        path: '/courses/single-unit-course-2026',
        type: 'UnitGroup',
        is_stable: true,
        is_recommended: false,
        locale_codes: [],
        locales: [],
        units: {
          17: {
            id: 17,
            name: 'Single Unit 2026',
            path: '/courses/single-unit-course-2025/units/1',
            lesson_extras_available: false,
            text_to_speech_enabled: false,
            position: null,
          },
        },
      },
    },
  },
};

export const fakeCoursesWithProgress = [
  {
    id: 1,
    display_name: 'Course A',
    units: [
      {
        id: 2,
        course_id: 4,
        version_year: '2018',
        key: 'coursea-2018',
        name: 'Course A (2018)',
        position: 1,
      },
      {
        id: 1,
        course_id: 1,
        version_year: '2017',
        key: 'coursea-2017',
        name: 'Course A (2017)',
        position: 1,
      },
    ],
  },
  {
    id: 2,
    display_name: 'CS Discoveries 2018',
    units: [
      {
        id: 5,
        course_id: 2,
        version_year: null,
        key: 'csd1-2018',
        name: 'Unit 1',
        position: 1,
      },
      {
        id: 6,
        course_id: 2,
        version_year: null,
        key: 'csd2-2018',
        name: 'Unit 2',
        position: 2,
      },
    ],
  },
  {
    id: 3,
    display_name: 'Flappy',
    units: [
      {
        id: 9,
        course_id: 3,
        version_year: 'unversioned',
        key: 'flappy',
        name: 'Flappy',
        position: null,
        description: 'Make a flappy game!',
      },
    ],
  },
];
