apiVersion: v1
kind: ConfigMap
metadata:
  name: cdo-locals.yml
data:
  active_job_queue_adapter: ":delayed_job"
  active_job_backend_n_workers_to_start: "1"
  active_job_backend_rolling_restart_in_n_batches: "1"
  contentful_api_key: ""
  contentful_cs_for_all_access_token: ""
  javabuilder_key_password: ""
  javabuilder_private_key: ""
  openai_student_learning_api_key: ""
  puma_control_server_token: ""
  recaptcha_secret_key: ""
  recaptcha_site_key: ""
