apiVersion: v1
kind: ConfigMap
metadata:
  name: cdo-locals.yml
data:
  active_job_queue_adapter: ":delayed_job"
  active_job_backend_n_workers_to_start: "1"
  active_job_backend_rolling_restart_in_n_batches: "1"
