name: Rake installer
jobs:
description: 'Node installer'
runs:
  using: "composite"
  steps:
    # Infer node version from .nvmrc, courtesy of https://github.com/actions/setup-node/issues/32#issuecomment-539794249
    - name: Read .nvmrc
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      id: nvm
      shell: bash
    - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
