title 'Afterschool 1'
description_short "Short course designed for informal learning"
description "Afterschool 1 is designed to for informal classrooms where students vary in age and assessment is not required. This course focuses on learning through entertainment, with varying options for implementation, all in 10 sessions or less. Use alone or with Afterschool Unplugged. Recommended for grades 3-8."
description_audience "Ages 7-13"
hidden 'false'