title 'Computer Science in Algebra PD'
description "Teach Algebra through Functional Programming"

stage 'Introduction to PD'
level 'PDAlg Intro'

stage 'Evaluation Blocks'
level 'Calc Circles of Eval 1'
level 'Calc Circles of Eval 2'
level 'Calc Circles of Eval 3'
level 'Calc Circles of Eval 5'
level 'Calc Circles of Eval 6'
level 'Calc Circles of Eval 7'
level 'Calc Circles of Eval 8'
level 'Calc Circles of Eval 9'
level 'Calc Circles of Eval Free Play'
