lesson 'Happy Maps'
level 'UnplugHappyMaps'

lesson 'Move it, Move it'
level 'MoveIt'

lesson 'Real-life Algorithms: Plant a Seed'
level 'PlantASeed'

lesson 'Graph Paper Programming'
level 'GraphPaperProgramming'

lesson 'Building a Foundation'
level 'BuildingAFoundation'

lesson 'Getting Loopy'
level 'GettingLoopy'

lesson 'The Big Event'
level 'BigEvent'

lesson 'Binary Bracelets'
level 'BinaryBracelets'

lesson 'Songwriting'
level 'SongwritingParameters'
