hidden false
teacher_resources [["lessonPlans", "https://docs.google.com/document/d/1wBceXwfyyJKqjKmSQaT_DlyLXlLG3qd3Qm_yL0mNgi8/edit?usp=sharing"]]

lesson_group 'lesson group', display_name: 'Contagion-Guided-Practice'
lesson 'how things spread gp', display_name: 'How Things Spread Guided Practice'
level 'contagion_teachers', progression: 'Lesson 2: Bridging Activity'
level 'contagion_teachers2', progression: 'Lesson 4: Collecting Data'

