published_state 'beta'

lesson 'craft17 stage', display_name: 'craft17 stage', has_lesson_plan: false
level 'MC_HOC_2017_01_RETRY'
level 'MC_HOC_2017_02_Cole'
level 'MC_HOC_2017_03_Cole'
level 'MC_HOC_2017_04_Cole'
level 'MC_HOC_2017_04POINT5_RYAN'
level 'MC_HOC_2017_05_Cole'
level 'MC_HOC_2017_06_Cole'
level 'Function intro Ryan'
level 'MC_HOC_2017_07_Cole'
level 'MC_HOC_2017_10_RETRY'
level 'MC_HOC_2017_Ali'
level 'MC_HOC_2017_FP20x20'

