published_state 'beta'

lesson 'craft17 stage', display_name: 'craft17 stage', has_lesson_plan: false
level 'MC_HOC_2017_01_Kiki'
level 'MC_HOC_2017_02_Kiki'
level 'MC_HOC_2017_03_Kiki'
level 'MC_HOC_2017_04_Kiki'
level 'MC_HOC_2017_05_Kiki'
level 'MC_HOC_2017_06_Kiki'
level 'MC_HOC_2017_07a_Kiki'
level 'MC_HOC_2017_07_Kiki'
level 'MC_HOC_2017_08_Kiki'
level 'MC_HOC_2017_09_Kiki'
level 'MC_HOC_2017_10_Kiki'
level 'MC_HOC_2017_11_Kiki'

