login_required true

stage 'What is a Computer? - sample progression'
level 'csd digital unplugged WIAC'
level 'csd digital unplugged WIAC L1'
level 'csd digital unplugged WIAC L2'
level 'CSD digital Unplugged WIAC video'
level 'csd digital unplugged WIAC L3'
level 'CSD digital unplugged WIAC Qs'

stage 'Problem Solving Process - sample activities'
level 'csd digital unplugged PSP word search'
level 'csd digital unplugged PSP seating'
