login_required true
hideable_lessons true
student_detail_progress_view true

lesson 'Computers and Problem Solving', display_name: 'Computers and Problem Solving', has_lesson_plan: false
level 'CSD U1 Test define a computer'
level 'CSD U1 Test PSP match'
level 'CSD U1 IOSP match'
level 'CSD U1 Test define problem'
level 'CSD U1 Test storage FR'
level 'CSD U1 Test Feedback FR'
level 'CSD U1 Test Collaborate FR'
level 'CSD U1 Test Iteration FR'
level 'CSD U1 Test', assessment: true

lesson 'Web Development', display_name: 'Web Development', has_lesson_plan: false
level 'CSD U2 Test HTML Usage'
level 'CSD U2 Test ContentStructureStyle'
level 'CSD U2 Test Classes'
level 'CSD U2 Test Debug'
level 'CSD U2 Test code stylesheet'
level 'CSD U2 Test code styles'
level 'CSD U2 Test Copyright'
level 'CSD U2 Test Bug FR'
level 'CSD U2 Test Copyright FR'
level 'CSD U2 Test DigCit FR'
level 'CSD Web Development Post-Project Test', assessment: true

lesson 'Interactive Animations and Games', display_name: 'Interactive Animations and Games', has_lesson_plan: false
level 'CSD U3 Test clean code'
level 'CSD U3 Test functions'
level 'CSD U3 Test variables'
level 'CSD U3 Test planning'
level 'CSD U3 Test debugging'
level 'CSD U3 Test comment'
level 'CSD U3 Test debug FR'
level 'CSD U3 Test parameter FR'
level 'CSD U3 Test collaboration FR'
level 'CSD Interactive Animations and Games Post-Project Test', assessment: true

