login_required true
hideable_stages true
student_detail_progress_view true

stage 'Computers and Problem Solving'
level 'CSD U1 Test define a computer'
level 'CSD U1 Test PSP match'
level 'CSD U1 IOSP match'
level 'CSD U1 Test define problem'
level 'CSD U1 Test storage FR'
level 'CSD U1 Test Feedback FR'
level 'CSD U1 Test Collaborate FR'
level 'CSD U1 Test Iteration FR'
level 'CSD U1 Test'

stage 'Web Development'
level 'CSD U2 Test HTML Usage'
level 'CSD U2 Test ContentStructureStyle'
