login_required true

lesson 'What is a Computer?', display_name: 'What is a Computer?'
level 'csd digital unplugged WIAC'
level 'csd digital unplugged WIAC L1'
level 'csd digital unplugged WIAC L2'
level 'CSD digital Unplugged WIAC video'
level 'csd digital unplugged WIAC L3'
level 'CSD digital unplugged WIAC Qs'

lesson 'Problem Solving Process', display_name: 'Problem Solving Process'
level 'csd digital unplugged PSP word search'
level 'csd digital unplugged PSP seating'

