login_required true
hideable_stages true
student_detail_progress_view true

lesson_group 'end_of_course_project', display_name: 'End of Course Project'
stage 'Snowflakes', flex_category: 'end_of_course_project'
level 'harvey_snowflake_artist1', named: true
level 'harvey_snowflake_artist2', named: true
level 'expresslink', named: true

lesson_group 'content', display_name: 'Content'
stage 'Binary'
level 'harvey_pixelation', named: true
