published_state 'beta'

lesson 'Sample Stage', display_name: 'Sample Stage', has_lesson_plan: false
level 'storyline1'
level 'storyline2'
level 'storyline3'
level 'sample1'
level 'storyline4'
level 'sample2'
level 'sample3'
level 'sample3assessment', assessment: true
level 'sample4'
level 'sample5'
level 'sample6'
level 'sample7assessment', assessment: true
level 'sample8'
level 'storyline5'
level 'sample9a'
level 'sample10a'

