title 'Secret Sample'
description_short "This is a secret...shhhhh"
description "Test of new educational philosophy"
description_audience "Ages 8-18"

stage 'Sample Stage'
level 'newCSFsample'
level 'sample1'
level 'sample2'
level 'sample3'
assessment 'sample3assessment'
level 'sample4'
level 'sample5'
level 'sample6'
assessment 'sample7assessment'
level 'sample8'
level 'sample9a'
level 'sample10a'
level 'kikiTesta'