login_required true
has_verified_resources true
family_name 'csp-mid-survey'
version_year 'unversioned'
published_state 'preview'
is_course true

lesson_group 'cspSurvey', display_name: 'Survey'
lesson 'CSP Mid-year survey', display_name: 'CSP Student Mid-year Survey', has_lesson_plan: false
level 'csp-post-survey-2017-levelgroup_2018', progression: 'CS Principles Mid-year Survey', assessment: true

