title 'CS Principles Pre-Survey'
hideable_stages true

stage 'Anonymous student pre-survey', 
lockable: false
assessment 'CSP pre-assessment survey'

stage 'Unit 1 Chapter 1 Assessment', lockable:true
variants
assessment 'CSP Unit 1 Ch1 Cumulative Assessment MC Group v2',active:true
assessment 'CSP Unit 1 Ch1 Cumulative Assessment MC Group',active:false
endvariants

stage 'NEW Unit 1 Chapter 1 Assessment', lockable:true
assessment 'CSP Unit 2 Ch2 Cumulative Assessment MC'