professional_learning_course 'TEST- CSP online teacher support'
title 'test space for csp online support'
description_short 'This is a sample course for testing csp online pd'
description 'This is a test space for online pd. Enrollment in this course does nothing.'
login_required 'true'

stage 'Unit 1 Overview',
  flex_category: 'required'
named_level 'Introduction to Unit 1'
named_level 'Unit 1 Teaching Philosophy and Commentary'
named_level 'Teaching with the Internet Simulator'
named_level 'Practice Performance Tasks in Unit 1'

stage 'Lessons 2 - 3: Binary Messages',
  flex_category: 'content'
named_level 'Binary as an Encoding Scheme'
named_level 'Understanding Communication Protocols'
named_level 'Lesson 1.2 Overview'
named_level 'Lesson 1.3 Overview'
named_level 'Internet Simulator: Sending Binary Messages'
named_level 'The Internet: Wires, Cables, and Wifi'

stage 'Lessons 4 - 6: Encoding and Sending Numbers',
  flex_category: 'content'
named_level 'Lesson 1.4 Overview'
named_level 'Why Teach Number Systems?'
named_level 'Lesson 1.5 Overview'
named_level 'Lesson 1.6 Overview'
named_level 'Sending Numbers: The Big Picture'
named_level 'Internet Simulator: Sending Numbers'
named_level 'Reflection: Create your Own Number System'

stage 'Lesson 7: Encoding and Sending Text',
  flex_category: 'content'
named_level 'Lesson 1.7 Overview'
named_level 'What is ASCII?'
named_level 'Task: ASCII Representation of your Name'
named_level 'What is HTML?'
named_level 'Internet Simulator: Sending Text'

stage 'Lesson 9: Internet Addressing',
  flex_category: 'content'
named_level 'Lesson 1.9 Overview'
named_level 'Addressing in the Game of Battleship '
named_level 'Task: Develop a Battleship Protocol'
named_level 'Internet Simulator: Broadcast'
named_level 'The Internet: IP Addresses & DNS' 

stage 'Lessons 10 - 11: Redundancy and Packets',
  flex_category: 'content'
named_level 'Lesson 1.10 Overview'
named_level 'Internet Simulator: Routers'
named_level 'Lesson 1.11 Overview'
named_level 'Internet Simulator: Packets'
named_level 'The Internet: Packets, Routing, and Reliability'


stage 'Lessons 12 - 13: Abstraction on the Internet',
  flex_category: 'content'
named_level 'Lesson 1.12 Overview'
named_level 'Internet Simulator: DNS' 
named_level 'The Internet: IP Addresses & DNS' 
named_level 'Lesson 1.13 Overview'
named_level 'The Internet: HTTP and HTML'

stage 'Group Work and Peer Learning',
  flex_category: 'practice'
 named_level 'Overview: Group Work and Peer Learning'
 named_level 'Collaborative Learning and Group Work: description and strategies'
 named_level 'The Official Peer Instruction Blog'
 named_level 'the Journal of Peer Learning '

stage 'Balancing Teachers and Tools',
  flex_category: 'practice'
 named_level  'Overview: Balancing Teachers and Tools'

stage 'Discovery Learning',
  flex_category: 'practice'
 named_level 'Overview: Discovery Learning'
 named_level 'Discovery learning definition and history'
 named_level 'Discovery learning techniques'

stage 'Measuring Student Learning',
  flex_category: 'practice'
 named_level  'Overview: Capturing Student Learning'
 named_level 'What is the difference between formative and summative assessment?'
 named_level 'Classroom Assessment Techniques'