professional_learning_course 'All The PLC Things'
login_required 'true'
peer_reviews_to_complete 4

stage 'Unit 1 Overview',
  flex_category: 'required'
named_level 'What\’s inside and how is it organized?'
named_level 'Data Tools in Unit 2 Chapter 2' 

stage 'Lessons 1 - 2: Bytes, File Sizes, and Text Compression',
  flex_category: 'content'
named_level '2.1 and 2.2 Lesson Connections'
named_level 'Overview of File Sizes and Metrics'
named_level'Introduction to Lossless Compression and the Text Compression Widget'
named_level 'How to: Text Compression Widget'
named_level 'Widget: Text Compression'

stage 'Lessons 3 - 4 : Encoding Images',
  flex_category: 'content'
named_level '2.3 and 2.4 Lesson Connections'
named_level 'Widget: Black and White Pixelation'
named_level 'Binary, Hex, and Images'
named_level 'Widget: Color Pixelation'

stage 'Lesson 5 - 6: Compression Formats and Developing your own Encoding Scheme',
  flex_category: 'content'
named_level '2.5 and 2.6 Lesson Connections'
named_level 'Introduction to Lossy Compression'
named_level 'Lossy vs. Lossless Compression'

stage 'Lessons 7 - 10: Interpreting Visual Data',
  flex_category: 'content'
named_level '2.7 -  10 Lesson Connections'
named_level 'How to: Setup your Class Data Tracker'
named_level 'How to: Use Google Trends'
named_level 'Data Visualizations 101'


stage 'Lessons 11 - 15: Communicating with Visualizations', 
  flex_category: 'content'
named_level '2.11 - 15 Lesson Connections'
named_level 'How to: Make Charts from your Data'
named_level 'Selecting an Appropriate Visualization for your Data'



stage 'Group Work and Peer Learning',
  flex_category: 'practice'
 named_level 'Overview: Group Work and Peer Learning'
 named_level 'Collaborative Learning and Group Work: description and strategies'
 named_level 'The Official Peer Instruction Blog'
 named_level 'the Journal of Peer Learning '
 named_level 'Teaching Practice Plan: Group Work and Peer Learning'

stage 'Balancing Teachers and Tools',
  flex_category: 'practice'
 named_level  'Overview: Balancing Teachers and Tools'
 named_level 'Classroom Management Tips for School Computer Labs'
 named_level 'Considerations for the 1-to-1 Classroom'
 named_level 'Teaching Practice Plan: Balancing Teacher and Tools'

stage 'Discovery Learning',
  flex_category: 'practice'
 named_level 'Overview: Discovery Learning'
 named_level 'Discovery learning definition and history'
 named_level 'Discovery learning techniques'
 named_level 'Teaching Practice Plan: Discovery Learning'

stage 'Measuring Student Learning',
  flex_category: 'practice'
 named_level  'Overview: Capturing Student Learning'
 named_level 'What is the difference between formative and summative assessment?'
 named_level 'Designing Assessment Questions'
 named_level 'Classroom Assessment Techniques'
 named_level 'Teaching Practice Plan: Assessing Student Learning'