login_required true
curriculum_umbrella 'CSP'

lesson_group 'csp3_1', display_name: 'Chapter 1: Programming Languages and Algorithms'
lesson 'CSP3A: Using Simple Commands', display_name: 'CSP3A: Using Simple Commands'
level 'subgoal v2 U3L04 Student Lesson Introduction'
level 'subgoal U3L2 Using Simple Commands'
level 'subgoal U3 L4 introducing subgoal labels'
level 'subgoalU3L2_TurtleSquare_right'

