login_required true

lesson 'NOTE: Deprecated. Teacher cannot see results. CSP Culminating Assessment', display_name: 'NOTE: Deprecated. Teacher cannot see results. CSP Culminating Assessment', has_lesson_plan: false
level 'CSP_Final_instructions'
level 'CSP Culminating Assessment', assessment: true

lesson 'RQB Questions test', display_name: 'RQB Questions test', has_lesson_plan: false
level 'RQB test levelgroup', assessment: true

