login_required true

lesson 'NOTE: Deprecated. Teacher cannot see results. CSP Culminating Assessment', display_name: 'translation missing: en-US.data.script.name.cspassessment.lessons.NOTE: Deprecated. Teacher cannot see results. CSP Culminating Assessment.name'
level 'CSP_Final_instructions'
level 'CSP Culminating Assessment', assessment: true

lesson 'RQB Questions test', display_name: 'RQB Questions test'
level 'RQB test levelgroup', assessment: true

