login_required true
has_lesson_plan true

lesson 'Explore PT Prep', display_name: 'Explore PT Prep'
level 'U5 - Explore PT Prep - Student Introduction'

lesson 'Explore PT', display_name: 'Explore PT'
level 'U5 - Explore PT - Student Introduction'

lesson 'Create PT Prep', display_name: 'Create PT Prep'
level 'U5 - Create PT Prep - Student Introduction'

lesson 'Create PT', display_name: 'Create PT'
level 'U5 - Create PT - Student Introduction'

