lesson 'Basic Circuits', display_name: 'Basic Circuits'
level 'duino battery led'
level 'duino button led'

lesson 'Blinky Lights', display_name: 'Blinky Lights'
level 'duino multi leds'
level 'duino pov'

lesson 'Making Music', display_name: 'Making Music'
level 'duino music'
level 'duino auduino'

lesson 'JunkBot', display_name: 'JunkBot'
level 'duino junkbot build'
level 'duino junkbot software'

