professional_learning_course 'FIT Weekend In Person'
peer_reviews_to_complete 2
login_required true
student_detail_progress_view true
published_state 'beta'

lesson_group 'required', display_name: 'Overview'
lesson 'Deeper Learning Overview', display_name: 'Deeper Learning Overview', has_lesson_plan: false
level 'Deeper Learning Overview', progression: 'Background'
level 'csd deeper learning timeline 2018-2019', progression: 'Deadlines and Payment'
level 'dlp supports - csd', progression: 'Resource Recommendations'
level 'peer review recommendations 18-19', progression: 'Guidelines For Peer Review'

lesson_group 'content', display_name: 'Content'
lesson 'Complete Practice Question', display_name: 'Complete Practice Question', has_lesson_plan: false
level 'fit-dlp-example'
level 'fit-dlp-example-2'

