professional_learning_course 'FIT Weekend In Person'
peer_reviews_to_complete 2
login_required true
student_detail_progress_view true

stage 'Deeper Learning Overview', flex_category: 'required'
level 'Deeper Learning Overview', progression: 'Background'
level 'csd deeper learning timeline 2018-2019', progression: 'Deadlines and Payment'
level 'dlp supports - csd', progression: 'Resource Recommendations'
level 'peer review recommendations 18-19', progression: 'Guidelines For Peer Review'

stage 'Complete Practice Question'
level 'fit-dlp-example'
level 'fit-dlp-example-2'
