hidden false
published_state 'preview'

lesson 'Minecraft Hour of Code', display_name: 'Minecraft Hour of Code', has_lesson_plan: false
level 'MC_HOC_2017_01_RETRY'
level 'MC_HOC_2017_02_Cole'
level 'MC_HOC_2017_03_Cole'
level 'MC_HOC_2017_04_Cole'
level 'MC_HOC_2017_04POINT5_RYAN'
level 'MC_HOC_2017_05_Cole'
level 'MC_HOC_2017_06_Cole'
level 'Function intro Ryan'
level 'MC_HOC_2017_07_Cole'
level 'MC_HOC_2017_10_RETRY'
level 'MC_HOC_2017_Ali'
level 'MC_HOC_2017_FP20x20'

