family_name 'hoc-encryption'
version_year 'unversioned'
published_state 'preview'
is_course true

lesson 'Simple Encryption', display_name: 'Simple Encryption', has_lesson_plan: false
level 'Crack a Caesar Cipher', named: true
level 'Terminology Recap', named: true
level 'New Challenge Introduction', named: true
level 'Crack Random Substitution', named: true
level 'Technique: Frequency Analysis', named: true
level 'Video - Encryption and Public Keys', named: true

