hideable_lessons true
student_detail_progress_view true
teacher_resources [["lessonPlans", "https://curriculum.code.org/csd-20/"], ["teacherForum", "https://forum.code.org/"], ["curriculumGuide", "https://docs.google.com/document/d/1-O6o5yQ4I1dk0n4Qzh86quXGBtzDDtyJ3Skr6RpcpO4/preview"], ["professionalLearning", "https://studio.code.org/my-professional-learning"]]

lesson 'Module 1'
level 'OPL - CSD-PL AYWS1 Debugging Intro', progression: 'Module 1 Overview'
level 'VPL - CSD - Module 1 Summer Review Overview', progression: 'Summer Workshop Review'
level 'VPL-CSD 2020 Summer Review', progression: 'Summer Workshop Review'
level 'VPL - CSD - Variables Overview', progression: 'New Content'
level 'VPL-Introduction to Variables - Part 1_2020', progression: 'New Content'
level 'VPL-CSD U3 Variables Predict Where XY_2020', progression: 'New Content'
level 'VPL - CSD - Variable Resources', progression: 'New Content'
level 'VPL-CSD U3 Variables naming rules v2_2018_2020', progression: 'New Content'
level 'VPL - CSD - Random Numbers Overview', progression: 'New Content'
level 'VPL-CSD U3 Random random ellipse2_2018_2020', progression: 'New Content'
level 'VPL - CSD Module 1 New Content Reflection', progression: 'New Content'
level 'VPL- CSD - Module 1 Debugging OverviewOPD-K5 Pair_copy', progression: 'Debugging'
level 'VPL - CSD Module 1 Debugging Reflection 1', progression: 'Debugging'
level 'VPL-CSD Games variables practice_2020', progression: 'Debugging'
level 'VPL - CSD Module 1 Debugging Reflection 2', progression: 'Debugging'
level 'VPL - CSD - Module 1 Wrap Up', progression: 'Module 1 Asynchronous Wrap Up'

lesson 'Module 2'
level 'VirtualPLOverview'
level 'VPL - CSD Module Variable Video with Reflection'

lesson 'Module 3'
level 'VirtualPLOverview'

lesson 'Module 4'
level 'VirtualPLOverview'

lesson 'Module 5'
level 'VirtualPLOverview'

lesson 'Module 6'
level 'VirtualPLOverview'

lesson 'Module 7'
level 'VirtualPLOverview'

lesson 'Module 8'
level 'VirtualPLOverview'

