hideable_lessons true

lesson 'Virtual Professional Learning Overview'
level 'CSD-U3-fill_2019-Jess'
level 'VirtualPLOverview'

lesson 'Module 1'
level 'OPL - CSD-PL AYWS1 Debugging Intro'
level 'Jess - CSD U2 HTML Adding Paragraphs_2019'

lesson 'Course Resources'
level 'OPD-CSD lesson plans'

lesson 'Debugging'
level 'OPL - CSD-PL AYWS1 Debugging Intro'
level 'OPL - CSD Web Debugging'
level 'OPL - CSD-PL Debugging Instructions'
level 'OPL - CSD U3 drawing practice 1'
level 'OPL - CSD U3 drawing practice 3'
level 'OPL - CSD U3 Variable names debug'
level 'OPL - CSD U3 Sprites debug'
level 'OPL - CSD - Debugging'

