id '7'
family_name 'jigsaw'
version_year 'unversioned'
published_state 'preview'
is_course true

lesson 'Jigsaw', display_name: 'Jigsaw', has_lesson_plan: false
level 'blockly:Jigsaw:1'
level 'blockly:Jigsaw:2'
level 'blockly:Jigsaw:3'
level 'blockly:Jigsaw:4'
level 'blockly:Jigsaw:5'
level 'blockly:Jigsaw:6'
level 'blockly:Jigsaw:7'
level 'blockly:Jigsaw:8'
level 'blockly:Jigsaw:9'
level 'blockly:Jigsaw:10'
level 'blockly:Jigsaw:11'
level 'blockly:Jigsaw:12'

