published_state 'beta'

lesson 'Using Behaviors', display_name: 'Using Behaviors', has_lesson_plan: false
level 'GLJr_Behavior_1'
level 'GLJr_Behavior_2'
level 'GLJr_Behavior_5'
level 'GLJr_Behavior_6'
level 'GLJr_Behavior_7'
level 'GLJr_Behavior_8'
level 'GLJr_Behavior_9'

lesson 'Using Forever Loops', display_name: 'Using Forever Loops', has_lesson_plan: false
level 'GLJr_Forever_1'
level 'GLJr_Forever_2'
level 'GLJr_Forever_5'
level 'GLJr_Forever_6'
level 'GLJr_Forever_7'
level 'GLJr_Forever_8'
level 'GLJr_Forever_9'

lesson 'Virtual Pet - Behaviors', display_name: 'Virtual Pet - Behaviors', has_lesson_plan: false
level 'behaviors pet test'
level 'behaviors pet test 2'
level 'behaviors pet test 3'

lesson 'Virtual Pet - Forever', display_name: 'Virtual Pet - Forever', has_lesson_plan: false
level 'loop pet test'
level 'loop pet test 2'
level 'loop pet test 3'
level 'loop pet test 4'

lesson 'Fish Tank', display_name: 'Fish Tank', has_lesson_plan: false
level 'Fish Tank 1'
level 'Fish Tank 2'
level 'Fish Tank 3'
level 'Fish Tank 4'
level 'Fish Tank 5'
level 'Fish Tank 6'
level 'Fish Tank 7'

lesson 'Alien Dance Party - Input', display_name: 'Alien Dance Party - Input', has_lesson_plan: false
level 'Dance Party 1'
level 'Dance Party 2'
level 'Dance Party 3'
level 'Dance Party 4'
level 'Dance Party 5'
level 'Dance Party 6'
level 'Dance Party 7'
level 'Dance Party Freeplay'

lesson 'Virtual Pet - Interactions', display_name: 'Virtual Pet - Interactions', has_lesson_plan: false
level 'Virtual Pet 1'
level 'Virtual Pet 2'
level 'Virtual Pet 3'
level 'Virtual Pet 4'
level 'Virtual Pet 5'
level 'Virtual Pet 6'
level 'Virtual Pet Freeplay'

