published_state 'beta'

lesson 'Module 1', display_name: 'Module 1', has_lesson_plan: false
level 'CSP-PL AYWS1 Workshop Overview', progression: 'Module 1 Overview (~5 minutes)'
level 'CSP Module 1 Unit 3 Context', progression: 'Wrapping up Unit 3 (~20 minutes)'
level 'CSP - Unit 4 tasks overview', progression: 'Unit 4 Overview (~30 minutes)'
level 'CSP-PL - U4 L12 Practice PT 1', progression: 'Unit 4 Overview (~30 minutes)'
level 'CSP-PL U4 L12 Practice PT 2', progression: 'Unit 4 Overview (~30 minutes)'
level 'CSP Module 1 Unit 4 Reflection', progression: 'Unit 4 Overview (~30 minutes)'
level 'CSP Module 1 EIPM Reflection', progression: 'Introducing EIPM (~25 minutes)'
level 'CSP Module 1 EIPM goes virtual', progression: 'Introducing EIPM (~25 minutes)'
level 'CSP - Module 1 Wrap Up', progression: 'Module 1 Asynchronous wrap-up (~10 minutes)'

lesson 'Module 2', display_name: 'Module 2', has_lesson_plan: false
level 'CSP-PL AYWS2 Workshop Overview', progression: 'Module 2 Overview (~5 minutes)'
level 'CSP - Variables Practice overview', progression: 'Variables Practice (~35 minutes)'
level 'CSP-PL - U4 L03 Variables numbers practice 1', progression: 'Variables Practice (~35 minutes)'
level 'CSP - PL - U4 L03 Variables numbers practice 4', progression: 'Variables Practice (~35 minutes)'
level 'CSP - PL - U4 L03 Variables operator practice 1', progression: 'Variables Practice (~35 minutes)'
level 'CSP - PL - U4 L03 Variables operator practice 3', progression: 'Variables Practice (~35 minutes)'
level 'CSP - PL - U4 L03 Variables operator practice 2', progression: 'Variables Practice (~35 minutes)'
level 'CSP - PL - U4 L03 Variables operator practice 5', progression: 'Variables Practice (~35 minutes)'
level 'CSP - PL8 - U4 L03 Variables operator practice 6', progression: 'Variables Practice (~35 minutes)'
level 'CSP - PL9 - U4 L03 Variable Scope: Local vs. Global', progression: 'Variables Practice (~35 minutes)'
level 'CSP - PL - Practice Reflection', progression: 'Variables Practice (~35 minutes)'
level 'CSP - Variables Make overview', progression: 'Variables Make (~30 minutes)'
level 'CSP - PL U4 L04 Variables Make Project_2020', progression: 'Variables Make (~30 minutes)'
level 'CSP - PL - U4 L04 Variables Make Project Submit_2020', progression: 'Variables Make (~30 minutes)'
level 'CSP - PL - Make Reflection', progression: 'Variables Make (~30 minutes)'
level 'CSP-PL - Unit 4 Wrap-up', progression: 'Collaborative and Independent Work (~10 minutes)'
level 'CSP - PL - Collaboration Reflection', progression: 'Collaborative and Independent Work (~10 minutes)'
level 'CSP - Module 2 Wrap Up', progression: 'Module 2 Asynchronous wrap-up (~10 minutes)'

lesson 'Module 3', display_name: 'Module 3', has_lesson_plan: false
level 'CSP-PL AYWS3 Workshop Overview', progression: 'Module 3 Overview (~5 minutes)'
level 'CSP - Understanding the context for the Model Lesson overview', progression: 'Understanding the Context for Lists (~55 minutes)'
level 'CSP - Synch3 - Reflection 1', progression: 'Understanding the Context for Lists (~55 minutes)'
level 'CSP - Synch3 - Reflection 2', progression: 'Understanding the Context for Lists (~55 minutes)'
level 'CSP - Asynch3 - Intro to CI', progression: 'Broadening, labeling, and recognizing CS skills in the classroom (~20 minutes)'
level 'CSP - Asynch3 - Broadening the def', progression: 'Broadening, labeling, and recognizing CS skills in the classroom (~20 minutes)'
level 'CSP - Asynch3 - Feedback in CI', progression: 'Broadening, labeling, and recognizing CS skills in the classroom (~20 minutes)'
level 'CSP - Asynch3 - Practice feedback', progression: 'Broadening, labeling, and recognizing CS skills in the classroom (~20 minutes)'
level 'CSP - Module 3 Wrap Up', progression: 'Module 3 Asynchronous wrap-up (~10 minutes)'

lesson 'Module 4', display_name: 'Module 4', has_lesson_plan: false
level 'CSP-PL AYWA4 Workshop Overview', progression: 'Module 4 Overview (~5 minutes)'
level 'CSP - Understanding the content of the Lists EIPM sequence', progression: 'Content of the Lists EIPM sequence (~25 minutes)'
level 'CSP - Lists EIPM reflection', progression: 'The Lists EIPM sequence (~25 minutes)'
level 'CSP AYW4 - Mental Models in Unit 5', progression: 'Mental models in Unit 5 (~35 minutes)'
level 'CSP - Asynch4 - Intro to Traversals', progression: 'Traversals and datasets (~15 minutes)'
level 'CSP - Asynch 4 - U5 Traversals Investigate Mile Tracker Modify', progression: 'Traversals and datasets (~15 minutes)'
level 'CSP - Asynch4 - U5L10 Traversals Investigate', progression: 'Traversals and datasets (~15 minutes)'
level 'CSP - Asynch4 -U5 Traversals Investigate Dog Finder Modify', progression: 'Traversals and datasets (~15 minutes)'
level 'CSP AYW4 - Reflection on datasets', progression: 'Traversals and datasets (~15 minutes)'
level 'CSP - Module 4 Wrap Up', progression: 'Module 4 Asynchronous wrap-up (~10 minutes)'

lesson 'Module 5', display_name: 'Module 5', has_lesson_plan: false
level 'CSP-PL Module 5 - Workshop Overview', progression: 'Module 5 overview (~5 minutes)'
level 'CSP-PL M5 - Intro to Unit 7', progression: 'Understanding Unit 7 (~5 minutes)'
level 'CSP-PL M5 - Param Explore', progression: 'Digging into the "Parameters and Return Explore" lesson (~25 minutes)'
level 'CSP-PL M5 - Param Prac 1', progression: 'Digging into the "Parameters and Return Practice" lesson (~30 minutes)'
level 'PL U7 Param Return Practice Part 1', progression: 'Digging into the "Parameters and Return Practice" lesson (~30 minutes)'
level 'PL U7 Param Return Practice Part 2', progression: 'Digging into the "Parameters and Return Practice" lesson (~30 minutes)'
level 'PL U7 Param Return Practice Part 4', progression: 'Digging into the "Parameters and Return Practice" lesson (~30 minutes)'
level 'PL U7 Param Return Practice Part 3', progression: 'Digging into the "Parameters and Return Practice" lesson (~30 minutes)'
level 'PL U7 Param Return Practice Part 5', progression: 'Digging into the "Parameters and Return Practice" lesson (~30 minutes)'
level 'PL U7 Param Investigate Calculator App', progression: 'Digging into the "Parameters and Return Practice" lesson (~30 minutes)'
level 'PL U7 Param Practice App 2', progression: 'Digging into the "Parameters and Return Practice" lesson (~30 minutes)'
level 'CSP-PL M5 - Param Prac 10', progression: 'Digging into the "Parameters and Return Practice" lesson (~30 minutes)'
level 'CSP-PL M5 - Inclusive Classrooms', progression: 'Creating inclusive classrooms (~15 minutes)'
level 'CSP - Module 5 Wrap Up', progression: 'Module 5 Asynchronous wrap-up (~10 minutes)'

lesson 'Module 6', display_name: 'Module 6', has_lesson_plan: false
level 'CSP-PL Module 6 - Workshop Overview', progression: 'Module 6 overview (~5 minutes)'
level 'CSP-PL M6 - Create PT Reqs', progression: 'Requirements of the Create Performance Task (~20 minutes)'
level 'CSP-PL M6 - Survival Guide', progression: 'Digging into the Create PT Survival Guide (~40 minutes)'
level 'CSP-PL M6 - Role of teacher', progression: 'Role of the teacher during the Create PT (~15 minutes)'
level 'CSP - Module 6 Wrap Up', progression: 'Module 6 Asynchronous Wrap-Up (~10 minutes)'

lesson 'Module 7', display_name: 'Module 7', has_lesson_plan: false
level 'CSP-PL Module 7 - Workshop Overview', progression: 'Module 7 overview (~5 minutes)'
level 'CSP-PL M7 - Unit 9 Overview', progression: 'Overview of Unit 9 - Data (~10 minutes)'
level 'CSP-PL M7 - Google Trends', progression: 'Using the Google Trends tool (~20 minutes)'
level 'CSP-PL M7 - Data Viz 1', progression: 'Using the Data Visualizer tool (~45 minutes)'
level 'CSP-PL M7 - Data Viz 2', progression: 'Using the Data Visualizer tool (~45 minutes)'
level 'CSP-PL M7 - Data Viz 3', progression: 'Using the Data Visualizer tool (~45 minutes)'
level 'CSP-PL M7 - Data Viz 4', progression: 'Using the Data Visualizer tool (~45 minutes)'
level 'CSP - Module 7 Wrap Up', progression: 'Module 7 asynchronous wrap-up (~10 minutes)'

lesson 'Module 8', display_name: 'Module 8', has_lesson_plan: false
level 'CSP-PL Module 8 - Workshop Overview', progression: 'Module 8 overview (~5 minutes)'
level 'CSP-PL M8 - Community 1', progression: 'Connecting to the CS community (~15 minutes)'
level 'CSP-PL M8 - Community 2', progression: 'Connecting to the CS community (~15 minutes)'
level 'CSP-PL M8 - MC Exam 1', progression: 'Preparing students for the AP multiple choice exam (~60 minutes)'
level 'CSP-PL M8 - Exam 2', progression: 'Preparing students for the AP multiple choice exam (~60 minutes)'
level 'CSP-PL M8 - Exam 3', progression: 'Preparing students for the AP multiple choice exam (~60 minutes)'
level 'CSP - Module 8 Wrap Up', progression: 'Module 8 asynchronous wrap-up (~10 minutes)'

lesson 'CS Principles: Functions', display_name: 'CS Principles: Functions', has_lesson_plan: false
level 'CS Principles: Functions', progression: 'CS Principles: Functions'

lesson 'CS Principles: Variables Practice - Choice Test', display_name: 'Variables Practice - Choice Test', has_lesson_plan: false
level 'CSP U4L3 SFLP 20-21', progression: 'Lesson Overview'
level 'U4 L03 Variables numbers practice 1', progression: 'Assigning Numbers and Strings'
level 'U4 L03 Variables numbers practice 4', progression: 'Assigning Numbers and Strings'
level 'U4 L03 Variables operator practice 1', progression: 'Variables and Operators'
level 'U4 L03 Variables operator practice 3', progression: 'Variables and Operators'
level 'U4 L03 Variables operator practice 2', progression: 'Variables and Operators'
level 'U4 L03 Variables operator practice 5', progression: 'Variables and Operators'
level 'U4 L03 Variables operator practice 6', progression: 'Variables and Operators'
level 'U4 L03 Variable Scope: Local vs. Global', progression: 'Debugging Scope Issues'
level 'U4 L03 Scope Issue', progression: 'Debugging Scope Issues'
level 'U4 L03 Variables operator practice 4', progression: 'Putting it Together'
level 'csp-choice-test', progression: 'Putting It Together'
level 'U4L3 CFU Variables Psuedocode', progression: 'Check For Understanding: AP Practice', assessment: true
level 'U4L3 CFU Variables Randomness Psuedocode', progression: 'Check for Understanding: AP Practice', assessment: true

