family_name 'playlab'
version_year 'unversioned'
published_state 'preview'
is_course true

lesson 'Play Lab', display_name: 'Play Lab', has_lesson_plan: false
level 'blockly:Studio:playlab_1'
level 'blockly:Studio:playlab_2'
level 'blockly:Studio:playlab_3'
level 'blockly:Studio:playlab_4'
level 'blockly:Studio:playlab_5'
level 'blockly:Studio:playlab_6'
level 'blockly:Studio:playlab_7'
level 'blockly:Studio:playlab_8'
level 'blockly:Studio:playlab_9'
level 'blockly:Studio:playlab_10'

