lesson 'Debugging: Unspotted Bugs', display_name: 'Debugging: Unspotted Bugs'
level 'courseB_video_Unspotted_2019'

lesson 'Persistence & Frustration: Stevie and the Big Project', display_name: 'Persistence & Frustration: Stevie and the Big Project'
level 'courseA_video_Stevie_2019'

lesson 'Real-life Algorithms: Plant a Seed', display_name: 'Real-life Algorithms: Plant a Seed'
level 'PlantASeed_2019'

