lesson 'Debugging: Unspotted Bugs', display_name: 'Debugging: Unspotted Bugs', has_lesson_plan: false
level 'courseB_video_Unspotted_2019'

lesson 'Persistence & Frustration: Stevie and the Big Project', display_name: 'Persistence & Frustration: Stevie and the Big Project', has_lesson_plan: false
level 'courseA_video_Stevie_2019'

lesson 'Real-life Algorithms: Plant a Seed', display_name: 'Real-life Algorithms: Plant a Seed', has_lesson_plan: false, unplugged: true
level 'PlantASeed_2019'

