professional_learning_course 'CS in Science Support'
login_required true

stage 'Welcome!'
level 'sciPD3OLP32 intro'
level 'sciPD2 timeline'
level 'PD check your progress'
level 'sciPD3 mods2'

stage 'Revisiting Complex Adaptive Systems'
level 'sciPD33 refresh'
level 'sciPD33 refresh2'

stage 'Thinking About Implementation'
level 'sciPD3 implement1'
level 'sciPD3 implement2'

stage 'Wrap-Up'
level 'sciPD3 thanks'
level 'sciPD3 end'
