title 'Special Levels'
description "Something special for those who know it exists. These puzzles might not be around long, so enjoy them while you can!"
description_short "Something special for those who know it exists. These puzzles might not be around long, so enjoy them while you can!"
description_audience "Ages 10-18"

stage 'Halloween 2015'
level 'October15 ghost 1'
level 'October15 stars 1'
level 'October15 JoL 1'