title 'Special Levels - Spring 2016!'
description "Something special for those who know it exists. These puzzles might not be around long, so enjoy them while you can!"
description_short "Something special for those who know it exists. These puzzles might not be around long, so enjoy them while you can!"
description_audience "Ages 10-18"

stage 'Spring 2016'
level 'love_spring_1'
level 'love_spring_2'
level 'love_spring_3'