title 'UI Tests'
description "Script for test. Careful, don't change level ordering."
hidden 'true'

stage 'All the Tests'
skin 'applab'
level 'ApplabUITest'
skin 'birds'
concepts 'sequence'
level 'blockly:MazeEC:3_1'
skin 'artist'
level 'blockly:ArtistEC:ec_1_10'
skin 'studio'
level 'blockly:StudioEC:ec_sandbox'
stage 'Free Response'
level 'U1L6 Free Response Assessment' # free response text match
stage 'Multi'
level 'U1L6 Assessment multiple choice' # multi
