---
driver:
  name: dokken
  chef_version: 17.6.18
transport:
  name: dokken
provisioner:
  name: dokken
verifier:
  name:  inspec
platforms:
- name: ubuntu-20.04
  driver:
    image: dokken/ubuntu-20.04
    pid_one_command: /bin/systemd
suites:
- name: default
  run_list:
  - recipe[cdo-jemalloc]
  - recipe[cdo-ruby]
