AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Buckets for Various Purposes"

Parameters:
  DeveloperAccount:
    Type: String
    NoEcho: true

Resources:
  CommonBucketProperties: &CommonBucketProperties
    BucketEncryption:
      ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: "aws:kms"
    PublicAccessBlockConfiguration:
      BlockPublicAcls: true
      BlockPublicPolicy: true
      IgnorePublicAcls: true
      RestrictPublicBuckets: true

  LibraryBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      <<: *CommonBucketProperties
      BucketName: "cdo-v3-libraries"
      VersioningConfiguration:
        Status: "Enabled"
      LoggingConfiguration:
        DestinationBucketName: "cdo-logs"
        LogFilePrefix: "s3/cdo-v3-libraries"

  SourcesBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      <<: *CommonBucketProperties
      BucketName: "cdo-v3-sources"
      VersioningConfiguration:
        Status: "Enabled"
      LifecycleConfiguration:
        Rules:
          - Id: "365-day expiration of old versions"
            NoncurrentVersionExpirationInDays: 365
            Prefix: "sources/"
            Status: "Enabled"
          - Id: "Clean Test Sources"
            NoncurrentVersionExpirationInDays: 1
            Prefix: "sources_test/"
            Status: "Enabled"
          - Id: "Clean Circle Sources"
            NoncurrentVersionExpirationInDays: 1
            Prefix: "sources_circle/"
            Status: "Enabled"
      LoggingConfiguration:
        DestinationBucketName: "cdo-logs"
        LogFilePrefix: "s3/cdo-v3-sources/"

  # If needed please add any other  bucket resources here...

  DataSharingInternalBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      <<: *CommonBucketProperties
      BucketName: "cdo-data-sharing-internal"

  MLModelsBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      <<: *CommonBucketProperties
      BucketName: "cdo-v3-trained-ml-models"
      VersioningConfiguration:
        Status: "Enabled"