AWSTemplateFormatVersion: 2010-09-09
Description: 'S3 Buckets'
Parameters:
  DeveloperAccount:
    Type: String
    NoEcho: true
Resources:
  ## Create S3 bucket for student libraries
  LibraryBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'cdo-v3-libraries'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
      VersioningConfiguration:
        Status: 'Enabled'
      LoggingConfiguration:
        DestinationBucketName: 'cdo-logs'
        LogFilePrefix: 's3/cdo-v3-libraries'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  DroneLibraryBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LibraryBucket
      PolicyDocument:
        Statement:
        - Sid: Grant Drone permission to objects created by CI tests.
          Effect: 'Allow'
          Action: 's3:*'
          Resource: 'arn:aws:s3:::cdo-v3-libraries/libraries_circle/*'
          Principal: {AWS: [!Sub "arn:aws:iam::${DeveloperAccount}:role/DroneWorker"]}
        - Sid: Grant Drone permission to list objects for CI tests.
          Effect: 'Allow'
          Action: 's3:ListBucket*'
          Resource: 'arn:aws:s3:::cdo-v3-libraries'
          Condition:
            StringLike:
              's3:Prefix': 'libraries_circle/*'
          Principal: {AWS: [!Sub "arn:aws:iam::${DeveloperAccount}:role/DroneWorker"]}
  SpritelabAnimationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'cdo-spritelab-animation-library'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
      VersioningConfiguration:
        Status: 'Enabled'
      LoggingConfiguration:
        DestinationBucketName: 'cdo-logs'
        LogFilePrefix: 's3/cdo-spritelab-animation-library'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  # for curriculumbuilder
  CurriculumBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'cdo-curriculum-devel'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
      VersioningConfiguration:
        Status: 'Enabled'
      LoggingConfiguration:
        DestinationBucketName: 'cdo-logs'
        LogFilePrefix: 's3/cdo-curriculum-devel'
  DataSharingInternalBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: 'cdo-data-sharing-internal'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
