compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

# Duplicates of `/frontend/.yarnrc.yml`'s catalog block
catalog:
  '@emotion/react': '^11.14.0'
  '@emotion/styled': '^11.14.1'
  '@mui/material': '^7.3.2'
