name: Apt package installer
jobs:
description: 'Apt package installer'
runs:
  using: "composite"
  steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get -y install libmagickwand-dev imagemagick ghostscript pdftk enscript
      shell: bash
