name: 'Test environment variables and diractories used by UI tests'
description: 'Set up the variables needed for the test to run'
runs:
  using: "composite"
  steps:
    - name: Setup locals
      env:        
        CIRCLE_NODE_TOTAL: 1
        CIRCLE_NODE_INDEX: 1
      run: |
          set -xe
          ulimit -n 4096
          export CI=true
          export CIRCLECI=true
          export RAILS_ENV=test
          export RACK_ENV=test
          export DISABLE_SPRING=1
          export LD_LIBRARY_PATH=/usr/local/lib
          # If running on Drone.io, DRONE_BUILD_NUMBER will be set: https://docs.drone.io/reference/environ/drone-build-number/
          # otherwise, use a random number instead. CIRCLE_BUILD_NUM determines where UI test cucumber logs are stored in S3.
          sudo mkdir -p ‘/home/circleci’
          export CIRCLE_BUILD_NUM=${DRONE_BUILD_NUMBER:-$RANDOM$RANDOM}
          export CIRCLE_NODE_INDEX=1
          export CIRCLE_TEST_REPORTS=/home/circleci/test_reports
          export CIRCLE_ARTIFACTS=/home/circleci/artifacts
          sudo mkdir -p $CIRCLE_TEST_REPORTS/cucumber
          sudo mkdir -p $CIRCLE_ARTIFACTS    
      shell: bash   
