apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-k8s-gitops
  namespace: {{ .Values.sharedResources.namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager-store-kargo-shared-resources
    kind: SecretStore
  target:
    name: kargo-k8s-gitops
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
      data:
        repoURL: https://github.com/code-dot-org/k8s-gitops.git
        username: "{{ `{{ .username }}` }}"
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: {{ printf "k8s/tofu/%s/kargo/gitops_repo_username" .Values.sharedResources.clusterName | quote }}
    - secretKey: password
      remoteRef:
        key: {{ printf "k8s/tofu/%s/kargo/gitops_repo_password" .Values.sharedResources.clusterName | quote }}
