apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: staging-
labels:
  - pairs:
      app.kubernetes.io/name: cdo
      app.kubernetes.io/instance: staging
    includeSelectors: true
    includeTemplates: true
patches:
  - path: deployment.patch.yaml
  # Enable these when gitops envType values start setting dashboard_workers again.
  # - path: locals.yml.patch.yaml
  # - path: deployment.resources.patch.yaml
