// Dance Party song titles mapped to the artist's Twitter handle to use in the // ShareDialog share links. Not all songs are available in all environments,
// and the full list of Dance Party songs can be found at: https://s3.console.aws.amazon.com/s3/buckets/cdo-sound-library/hoc_song_meta/?region=us-east-1&tab=overview

export const SongTitlesToArtistTwitterHandle = {
  "backtoyou_selenagomez" : "SelenaGomez",
  "bornthisway_ladygaga" : "LadyGaga",
  "callmemaybe_carlyraejepsen": "CarlyRaeJepsen",
  "cantfeelmyface_theweeknd" : "TheWeeknd",
  "cantholdus_macklemore" : "Macklemore",
  "cheapthrills_sia" : "SiaMusic",
  "countrygirl_lukebryan" : "LukeBryanOnline",
  "dancinginthedark_brucespringsteen" : "Springsteen",
  "danzakuduro_donomar" : "DONOMAR",
  "heyya_outkast" : "Outkast",
  "iliketomoveit_william" : "iamwill",
  "getintothegroove_madonna" : "Madonna",
  "levelup_ciara" : "Ciara",
  "macarena_losdelrio" : "LosDelRioMusic",
  "migente_jbalvin" : "JBalvin",
  "needyounow_ladyantebellum" : "LadyAntebellum",
  "nottearslefttocry_arianagrande" : "ArianGrande",
  "shapeofyou_edsheeran" : "EdSheeran",
  "somebodylikeyou_keithurban" : "KeithUrban",
  "sorry_justinbieber" : "JustinBieber",
  "summer_calvinharris" : "CalvinHarris",
  "takeonme_aha" : "Aha_Com",
  "isawthesign_aceofbase" : "AceofBase",
  "thunder_imaginedragons" : "ImagineDragons",
  "canttouchthis_mchammer" : "MCHammer",
  "uptownfunk_brunomars" : "BrunoMars",
  "vivalavida_coldplay" : "Coldplay",
  "wakemeup_aviciialoeblacc" : "AloeBlacc",
  "wecantstop_mileycyrus" : "MileyCyrus",
  "wenospeakamericano_yolandabecool" : "YolandaBeCool",
  "ymca_villagepeople" : "VillagePeople",
};
