// Dance Party song titles mapped to the artist's Twitter handle to use in the // ShareDialog share links. Not all songs are available in all environments,
// and the full list of in-use Dance Party songs can be found at: https://s3.console.aws.amazon.com/s3/buckets/cdo-sound-library/hoc_song_meta/?region=us-east-1&tab=overview
//Full list of songs including potential (reflected here) can be found at:
// https://tinyurl.com/y9r5xx5d

export const SongTitlesToArtistTwitterHandle = {
  "backtoyou_selenagomez" : "SelenaGomez",
  "bornthisway_ladygaga" : "LadyGaga",
  "callmemaybe_carlyraejepsen": "CarlyRaeJepsen",
  "cantfeelmyface_theweeknd" : "TheWeeknd",
  "cantholdus_macklemore" : "Macklemore",
  "cheapthrills_sia" : "Sia",
  "countrygirl_lukebryan" : "LukeBryanOnline",
  "dancinginthedark_brucespringsteen" : "Springsteen",
  "heyya_outkast" : "Outkast",
  "iliketomoveit_william" : "iamwill",
  "getintothegroove_madonna" : "Madonna",
  "levelup_ciara" : "Ciara",
  "macarena_losdelrio" : "LosDelRioMusic",
  "migente_jbalvin" : "JBalvin",
  "needyounow_ladyantebellum" : "LadyAntebellum",
  "notearslefttocry_arianagrande" : "ArianaGrande",
  "shapeofyou_edsheeran" : "EdSheeran",
  "somebodylikeyou_keithurban" : "KeithUrban",
  "sorry_justinbieber" : "JustinBieber",
  "summer_calvinharris" : "CalvinHarris",
  "takeonme_aha" : "Aha_Com",
  "isawthesign_aceofbase" : "AceofBase",
  "thunder_imaginedragons" : "ImagineDragons",
  "canttouchthis_mchammer" : "MCHammer",
  "uptownfunk_brunomars" : "BrunoMars",
  "vivalavida_coldplay" : "Coldplay",
  "wakemeup_aviciialoeblacc" : "AloeBlacc",
  "wecantstop_mileycyrus" : "MileyCyrus",
  "wenospeakamericano_yolandabecool" : "YolandaBeCool",
  "ymca_villagepeople" : "VillagePeople",
  "firework_katyperry" : "KatyPerry",
  // These tracks available locally, tweet @codeorg to avoid spamming anyone.
  "jazzy_beats" : "codeorg",
  "synthesize" : "codeorg",
  // These tracks are currently only potential. If we get licensing, we'll be
  // able to tweet the artist without an additional DTP.
  "onedance_drake" : "Drake",
  "starships_nickiminaj" : "NickiMinaj",
  "elprestamo_maluma" : "Maluma",
  "despacito_luisfonsi" : "LuisFonsi",
  "tunaktunaktun_dalermehndi" : "DalerMehndi",
  "sapescommejamias_maitregims" : "MaitreGIMS",
  "lesercitodelselfie_takagi" : "TakagiBeatz",
  "gangnamstyle_psy" : "Psy_Oppa",
  "sophia_alvarosoler" : "AsolerMusic",
  "danzakuduro_donomar" : "DONOMAR",
  "cestlavie_khaled" : "Khaled_Officiel",
  "occidentaliskarma_francescogabbani" : "FrankGabbani",
  "isthatforme_anitta" : "Anitta",
  "showdaspoderosas_anitta" : "Anitta",
  "janti_muratboz" : "MuratBoz",
  "gee_girlsgen" : "GirlsGeneration",
  "growingpains_alessiacara" : "AlessiaCara",
};
