# Access AWS Secrets Manager secrets via the External Secrets Operator (ESO).
#
# Syncs all secrets like: {namespace}/cdo/* into a single k8s secret 'cdo-secrets'
#
# See: k8s/tofu/codeai-k8s/external-secrets-operator.tf
{{- if .Values.use_aws_secrets_manager }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cdo-secrets
  labels:
    {{- include "cdo.labels" (merge (dict "component" "external-secrets") .) | nindent 4 }}
spec:
  # Syncing every 5 minutes we expect to cost $0.25/month per namespace
  # Assumptions: 100 keys per sync, needs 5 calls to BatchGetSecretValue, at $0.05 per 10k calls
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: cdo-secrets
  dataFrom:
    - find:
        path: {{ .Release.Namespace }}/cdo
{{- end }}
