# K8S Secrets injected into the CDO.* namespace, for secrets running in the pod
# as opposed to secrets from AWS Secrets Manager. For those, see aws-secrets-manager.yaml.

# $existing fetches the existing secret, so we can preserve generated passwords when we re-apply this manifest.
{{- $existing := lookup "v1" "Secret" .Release.Namespace "cdo-secrets-local" }}

apiVersion: v1
kind: Secret
metadata:
  name: cdo-secrets-local
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "cdo.labels" (merge (dict "component" "cdo-secrets-local") .) | nindent 4 }}
type: Opaque
stringData:


  # To change the MySQL root password, edit _mysql_root_password and redeploy this chart.
  {{ $mysqlRootPassword := include "cdo.secretValue" (dict "secret" $existing "key" "_mysql_root_password" "randLen" 24) }}
  _mysql_root_password: {{ $mysqlRootPassword | quote }} # caches the generated password
  {{ $mysqlHost := include "cdo.mysqlServiceName" . }}
  {{ $mysqlUsername := "root" }}

# MySQL CDO secrets for dashboard.
{{ if .Values.services.mysql.enabled }}
  db_writer: {{ printf "mysql://%s:%s@%s/" $mysqlUsername $mysqlRootPassword $mysqlHost | quote }}
  db_reader: {{ printf "mysql://%s:%s@%s/" $mysqlUsername $mysqlRootPassword $mysqlHost | quote }}

  reporting_db_writer: {{ printf "mysql://%s:%s@%s/" $mysqlUsername $mysqlRootPassword $mysqlHost | quote }}
  reporting_db_reader: {{ printf "mysql://%s:%s@%s/" $mysqlUsername $mysqlRootPassword $mysqlHost | quote }}

  db_credential_admin: {{ printf "{\"username\":\"%s\",\"password\":\"%s\"}" $mysqlUsername $mysqlRootPassword | quote }}
  db_credential_writer: {{ printf "{\"username\":\"%s\",\"password\":\"%s\"}" $mysqlUsername $mysqlRootPassword | quote }}
  db_credential_reader: {{ printf "{\"username\":\"%s\",\"password\":\"%s\"}" $mysqlUsername $mysqlRootPassword | quote }}
{{ end }}



  # To change the Redis password, edit _redis_password and redeploy this chart.
  {{ $redisPassword := include "cdo.secretValue" (dict "secret" $existing "key" "_redis_password" "randLen" 24) }}
  _redis_password: {{ $redisPassword | quote }} # caches the generated password

  {{ $redisHost := include "cdo.redisServiceName" . }}

# Redis CDO secrets for dashboard.
{{ if .Values.services.redis.enabled }}
  redis_url: {{ printf "redis://:%s@%s:6379/0" $redisPassword $redisHost | quote }}
  netsim_redis_groups: |
    - master: {{ printf "redis://:%s@%s:6379" $redisPassword $redisHost | quote }}
  
{{ end }}


  # To change the MinIO root password, edit _minio_root_password and redeploy this chart.
  {{ $minioRootPassword := include "cdo.secretValue" (dict "secret" $existing "key" "_minio_root_password" "randLen" 24) }}
  _minio_root_password: {{ $minioRootPassword | quote }} # caches the generated password

  # To change the MinIO root user, edit _minio_root_user and redeploy this chart.
  {{ $minioRootUser := include "cdo.secretValue" (dict "secret" $existing "key" "_minio_root_user" "default" "local-development") }}
  _minio_root_user: {{ $minioRootUser | quote }} # caches the generated username

# MinIO CDO secrets for dashboard.
{{ if .Values.services.minio.enabled }}
  aws_s3_access_key_id: {{ $minioRootUser | quote }}
  aws_s3_secret_access_key: {{ $minioRootPassword | quote }}
{{ end }}
