apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cdo.fullname" (merge (dict "component" "locals.yml") .) }}
  labels:
    {{ include "cdo.labels" (merge (dict "component" "locals.yml") .) | nindent 4 }}
data:
  locals.yml: |

    # MySQL connections
    db_writer: 'mysql://root@{{ include "cdo.fullname" (merge (dict "component" "mysql") .) }}/'

    # Redis connections
    geocoder_redis_url: redis://{{ include "cdo.fullname" (merge (dict "component" "redis") .) }}:6379/0/geocoder
    session_store_server: redis://{{ include "cdo.fullname" (merge (dict "component" "redis") .) }}:6379/0/session
    netsim_redis_groups:
    - master: redis://{{ include "cdo.fullname" (merge (dict "component" "redis") .) }}:6379

    dashboard_enable_pegasus: false
    build_apps: true
    use_my_apps: true

    # Should we use these?
    cloudfront_key_pair_id: localoverride
    cloudfront_private_key: localoverride
    slack_bot_token: localoverride
    properties_encryption_key: ''
