name: Rake dependencies installer
jobs:
description: 'Runs rake install and rake build'
runs:
  using: "composite"
  steps:
    - name: Install Rake
      run: bundle exec rake install
      shell: bash
    - name: Build rake
      run: bundle exec rake build
      shell: bash
