SELECT users.id,
       studio_person_id,
       IF(users.provider = 'migrated', authentication_options.email, users.email) AS email,
       parent_email,
       encrypted_password,
       reset_password_token,
       reset_password_sent_at,
       remember_created_at,
       sign_in_count,
       current_sign_in_at,
       last_sign_in_at,
       current_sign_in_ip,
       last_sign_in_ip,
       users.created_at AS created_at,
       users.updated_at AS updated_at,
       username,
       provider,
       UID,
       ADMIN,
       gender,
       name,
       locale,
       birthday,
       user_type,
       school,
       full_address,
       school_info_id,
       total_lines,
       secret_picture_id,
       active,
       IF(users.provider = 'migrated', authentication_options.hashed_email, users.hashed_email) AS hashed_email,
       users.deleted_at AS deleted_at,
       purged_at,
       secret_words,
       properties,
       invitation_token,
       invitation_created_at,
       invitation_sent_at,
       invitation_accepted_at,
       invitation_limit,
       invited_by_id,
       invited_by_type,
       invitations_count,
       terms_of_service_version,
       urm,
       races,
       primary_contact_info_id
FROM   users
       left join authentication_options
              ON users.primary_contact_info_id = authentication_options.id
