import {LevelPropertiesBaseSchema} from '@code-dot-org/core/api';
import type {MockJsonBody, MockRoute} from '@code-dot-org/core/api/mocks';
import {fixtureFactory} from '@code-dot-org/core/api/mocks';

// Level-properties builders: common wire defaults + per-level overrides,
// validated through the real schema so a fixture can't drift from the contract
// the API client parses. Lab-specific fields (mode, videoKey, levelData) ride
// along as overrides — the base schema strips them on parse, wire() keeps them.
const baseDefaults = {
  id: 0,
  name: 'stub',
  helpVideos: [],
  parentLevelLink: null,
  exemplarSources: null,
  offerBrowserTts: true,
  showExemplarLink: false,
  isAssessment: false,
};
const fishLevel = fixtureFactory(LevelPropertiesBaseSchema, {
  ...baseDefaults,
  appName: 'fish',
  type: 'Fish',
});
const videoLevel = fixtureFactory(LevelPropertiesBaseSchema, {
  ...baseDefaults,
  appName: 'standalone_video',
  type: 'StandaloneVideo',
});

// Wrap the level entries into the id-keyed map the endpoint returns; the key is
// always the entry's own id, so the map can't desync from its contents.
const lessonMap = (entries: Array<{id: number}>): MockJsonBody =>
  Object.fromEntries(entries.map(e => [String(e.id), e])) as MockJsonBody;

export const oceansCourseFixtures: MockRoute[] = [
  {
    path: '*/api/script_structure/courses/oceans/units/:unitPos',
    respond: {
      id: 446,
      name: 'oceans',
      title: 'AI for Oceans',
      tts: true,
      scriptPath: '/courses/oceans/units/1',
      lessons: [
        {
          script_id: 446,
          script_name: 'oceans',
          num_script_lessons: 1,
          id: 5066,
          position: 1,
          name: 'AI for Oceans',
          levels: [
            {
              id: '158432',
              ids: ['19423'],
              activeId: '19423',
              inactiveIds: [],
              position: 1,
              kind: 'puzzle',
              icon: 'fa-video-camera',
              is_concept_level: true,
              title: 1,
              url: '/courses/oceans/units/1/lessons/1/levels/1',
              path: '/courses/oceans/units/1/lessons/1/levels/1',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'standalone_video',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'AI Machine Learning - Video',
            },
            {
              id: '158433',
              ids: ['19419'],
              activeId: '19419',
              inactiveIds: [],
              position: 2,
              kind: 'puzzle',
              icon: null,
              is_concept_level: false,
              title: 2,
              url: '/courses/oceans/units/1/lessons/1/levels/2',
              path: '/courses/oceans/units/1/lessons/1/levels/2',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'fish',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'Train an AI to Clean the Ocean',
            },
            {
              id: '158434',
              ids: ['19418'],
              activeId: '19418',
              inactiveIds: [],
              position: 3,
              kind: 'puzzle',
              icon: null,
              is_concept_level: false,
              title: 3,
              url: '/courses/oceans/units/1/lessons/1/levels/3',
              path: '/courses/oceans/units/1/lessons/1/levels/3',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'fish',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'Train an AI to Clean the Ocean',
            },
            {
              id: '158435',
              ids: ['19417'],
              activeId: '19417',
              inactiveIds: [],
              position: 4,
              kind: 'puzzle',
              icon: null,
              is_concept_level: false,
              title: 4,
              url: '/courses/oceans/units/1/lessons/1/levels/4',
              path: '/courses/oceans/units/1/lessons/1/levels/4',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'fish',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'Train an AI to Clean the Ocean',
            },
            {
              id: '158436',
              ids: ['19425'],
              activeId: '19425',
              inactiveIds: [],
              position: 5,
              kind: 'puzzle',
              icon: 'fa-video-camera',
              is_concept_level: true,
              title: 5,
              url: '/courses/oceans/units/1/lessons/1/levels/5',
              path: '/courses/oceans/units/1/lessons/1/levels/5',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'standalone_video',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'AI: Training Data & Bias - Video',
            },
            {
              id: '158437',
              ids: ['19422'],
              activeId: '19422',
              inactiveIds: [],
              position: 6,
              kind: 'puzzle',
              icon: null,
              is_concept_level: false,
              title: 6,
              url: '/courses/oceans/units/1/lessons/1/levels/6',
              path: '/courses/oceans/units/1/lessons/1/levels/6',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'fish',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'Using Training Data',
            },
            {
              id: '158438',
              ids: ['19424'],
              activeId: '19424',
              inactiveIds: [],
              position: 7,
              kind: 'puzzle',
              icon: 'fa-video-camera',
              is_concept_level: true,
              title: 7,
              url: '/courses/oceans/units/1/lessons/1/levels/7',
              path: '/courses/oceans/units/1/lessons/1/levels/7',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'standalone_video',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'AI: Impact on Society - Video',
            },
            {
              id: '158439',
              ids: ['19420'],
              activeId: '19420',
              inactiveIds: [],
              position: 8,
              kind: 'puzzle',
              icon: null,
              is_concept_level: false,
              title: 8,
              url: '/courses/oceans/units/1/lessons/1/levels/8',
              path: '/courses/oceans/units/1/lessons/1/levels/8',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'fish',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'Teach AI a New Word',
            },
          ],
          finishLink: '/api/hour/finish/oceans',
          finishText: 'I finished!',
        },
      ],
    },
  },
  {
    path: '*/s/oceans/lessons/1/level_properties',
    respond: lessonMap([
      videoLevel.wire({
        id: 19423,
        name: 'Oceans_Video_Machine_Learning',
        videoKey: 'oceans_machine_learning',
        displayName: 'Video: Machine Learning',
        levelData: {
          src: 'https://www.youtube-nocookie.com/embed/KHbwOetbmbs/',
          key: 'oceans_machine_learning',
          name: 'Machine Learning',
          download:
            'https://videos.code.org/levelbuilder/01-ai-machinelearning-sm-mp4-mp4.mp4',
          thumbnail: '/c/video_thumbnails/oceans_machine_learning.jpg',
          enableFallback: true,
          autoplay: false,
        },
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/2',
      }),
      fishLevel.wire({
        id: 19419,
        name: 'Oceans_FishVTrash',
        mode: 'fishvtrash',
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/3',
      }),
      fishLevel.wire({
        id: 19418,
        name: 'Oceans_CreaturesVTrashDemo',
        mode: 'creaturesvtrashdemo',
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/4',
      }),
      fishLevel.wire({
        id: 19417,
        name: 'Oceans_CreaturesVTrash',
        mode: 'creaturesvtrash',
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/5',
      }),
      videoLevel.wire({
        id: 19425,
        name: 'Oceans_Video_Training_Data',
        videoKey: 'oceans_training_data',
        displayName: 'Video: Training Data',
        levelData: {
          src: 'https://www.youtube-nocookie.com/embed/x2mRoFNm22g/',
          key: 'oceans_training_data',
          name: 'Training Data',
          download:
            'https://videos.code.org/levelbuilder/02-ai-trainingdata-sm-mp4.mp4',
          thumbnail: '/c/video_thumbnails/oceans_training_data.jpg',
          enableFallback: true,
          autoplay: false,
        },
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/6',
      }),
      fishLevel.wire({
        id: 19422,
        name: 'Oceans_Short',
        mode: 'short',
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/7',
      }),
      videoLevel.wire({
        id: 19424,
        name: 'Oceans_Video_Societal_Implications',
        videoKey: 'oceans_societal_implications',
        displayName: 'Video: Societal Implications',
        levelData: {
          src: 'https://www.youtube-nocookie.com/embed/ng4c1g3COfs/',
          key: 'oceans_societal_implications',
          name: 'Societal Implications',
          download:
            'https://videos.code.org/levelbuilder/03-ai-impactonsociety-sm-mp4.mp4',
          thumbnail: '/c/video_thumbnails/oceans_societal_implications.jpg',
          enableFallback: true,
          autoplay: false,
        },
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/8',
      }),
      fishLevel.wire({
        id: 19420,
        name: 'Oceans_Long',
        mode: 'long',
        finishUrl: '/api/hour/finish/oceans',
      }),
    ]),
  },
];
