import type {MockRoute} from '@code-dot-org/core/api/mocks';

export const oceansCourseFixtures: MockRoute[] = [
  {
    path: '*/api/script_structure/courses/oceans/units/:unitPos',
    respond: {
      id: 446,
      name: 'oceans',
      title: 'AI for Oceans',
      tts: true,
      scriptPath: '/courses/oceans/units/1',
      lessons: [
        {
          script_id: 446,
          script_name: 'oceans',
          num_script_lessons: 1,
          id: 5066,
          position: 1,
          name: 'AI for Oceans',
          levels: [
            {
              id: '158432',
              ids: ['19423'],
              activeId: '19423',
              inactiveIds: [],
              position: 1,
              kind: 'puzzle',
              icon: 'fa-video-camera',
              is_concept_level: true,
              title: 1,
              url: '/courses/oceans/units/1/lessons/1/levels/1',
              path: '/courses/oceans/units/1/lessons/1/levels/1',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'standalone_video',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'AI Machine Learning - Video',
            },
            {
              id: '158433',
              ids: ['19419'],
              activeId: '19419',
              inactiveIds: [],
              position: 2,
              kind: 'puzzle',
              icon: null,
              is_concept_level: false,
              title: 2,
              url: '/courses/oceans/units/1/lessons/1/levels/2',
              path: '/courses/oceans/units/1/lessons/1/levels/2',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'fish',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'Train an AI to Clean the Ocean',
            },
            {
              id: '158434',
              ids: ['19418'],
              activeId: '19418',
              inactiveIds: [],
              position: 3,
              kind: 'puzzle',
              icon: null,
              is_concept_level: false,
              title: 3,
              url: '/courses/oceans/units/1/lessons/1/levels/3',
              path: '/courses/oceans/units/1/lessons/1/levels/3',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'fish',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'Train an AI to Clean the Ocean',
            },
            {
              id: '158435',
              ids: ['19417'],
              activeId: '19417',
              inactiveIds: [],
              position: 4,
              kind: 'puzzle',
              icon: null,
              is_concept_level: false,
              title: 4,
              url: '/courses/oceans/units/1/lessons/1/levels/4',
              path: '/courses/oceans/units/1/lessons/1/levels/4',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'fish',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'Train an AI to Clean the Ocean',
            },
            {
              id: '158436',
              ids: ['19425'],
              activeId: '19425',
              inactiveIds: [],
              position: 5,
              kind: 'puzzle',
              icon: 'fa-video-camera',
              is_concept_level: true,
              title: 5,
              url: '/courses/oceans/units/1/lessons/1/levels/5',
              path: '/courses/oceans/units/1/lessons/1/levels/5',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'standalone_video',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'AI: Training Data & Bias - Video',
            },
            {
              id: '158437',
              ids: ['19422'],
              activeId: '19422',
              inactiveIds: [],
              position: 6,
              kind: 'puzzle',
              icon: null,
              is_concept_level: false,
              title: 6,
              url: '/courses/oceans/units/1/lessons/1/levels/6',
              path: '/courses/oceans/units/1/lessons/1/levels/6',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'fish',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'Using Training Data',
            },
            {
              id: '158438',
              ids: ['19424'],
              activeId: '19424',
              inactiveIds: [],
              position: 7,
              kind: 'puzzle',
              icon: 'fa-video-camera',
              is_concept_level: true,
              title: 7,
              url: '/courses/oceans/units/1/lessons/1/levels/7',
              path: '/courses/oceans/units/1/lessons/1/levels/7',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'standalone_video',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'AI: Impact on Society - Video',
            },
            {
              id: '158439',
              ids: ['19420'],
              activeId: '19420',
              inactiveIds: [],
              position: 8,
              kind: 'puzzle',
              icon: null,
              is_concept_level: false,
              title: 8,
              url: '/courses/oceans/units/1/lessons/1/levels/8',
              path: '/courses/oceans/units/1/lessons/1/levels/8',
              freePlay: false,
              bonus: false,
              display_as_unplugged: false,
              app: 'fish',
              uses_lab2: false,
              is_validated: false,
              can_have_feedback: false,
              progression_display_name: 'Teach AI a New Word',
            },
          ],
          finishLink: '/api/hour/finish/oceans',
          finishText: 'I finished!',
        },
      ],
    },
  },
  {
    path: '*/courses/oceans/units/:unitPos/lessons/:lessonPos/level_properties',
    respond: {
      '19423': {
        videoKey: 'oceans_machine_learning',
        displayName: 'Video: Machine Learning',
        name: 'Oceans_Video_Machine_Learning',
        id: 19423,
        levelData: {
          src: 'https://www.youtube-nocookie.com/embed/KHbwOetbmbs/',
          key: 'oceans_machine_learning',
          name: 'Machine Learning',
          download:
            'https://videos.code.org/levelbuilder/01-ai-machinelearning-sm-mp4-mp4.mp4',
          thumbnail: '/c/video_thumbnails/oceans_machine_learning.jpg',
          enableFallback: true,
          autoplay: false,
        },
        helpVideos: [],
        type: 'StandaloneVideo',
        appName: 'standalone_video',
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/2',
        offerBrowserTts: true,
        isAssessment: false,
      },
      '19419': {
        mode: 'fishvtrash',
        name: 'Oceans_FishVTrash',
        id: 19419,
        helpVideos: [],
        type: 'Fish',
        appName: 'fish',
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/3',
        offerBrowserTts: true,
        isAssessment: false,
      },
      '19418': {
        mode: 'creaturesvtrashdemo',
        name: 'Oceans_CreaturesVTrashDemo',
        id: 19418,
        helpVideos: [],
        type: 'Fish',
        appName: 'fish',
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/4',
        offerBrowserTts: true,
        isAssessment: false,
      },
      '19417': {
        mode: 'creaturesvtrash',
        name: 'Oceans_CreaturesVTrash',
        id: 19417,
        helpVideos: [],
        type: 'Fish',
        appName: 'fish',
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/5',
        offerBrowserTts: true,
        isAssessment: false,
      },
      '19425': {
        videoKey: 'oceans_training_data',
        displayName: 'Video: Training Data',
        name: 'Oceans_Video_Training_Data',
        id: 19425,
        levelData: {
          src: 'https://www.youtube-nocookie.com/embed/x2mRoFNm22g/',
          key: 'oceans_training_data',
          name: 'Training Data',
          download:
            'https://videos.code.org/levelbuilder/02-ai-trainingdata-sm-mp4.mp4',
          thumbnail: '/c/video_thumbnails/oceans_training_data.jpg',
          enableFallback: true,
          autoplay: false,
        },
        helpVideos: [],
        type: 'StandaloneVideo',
        appName: 'standalone_video',
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/6',
        offerBrowserTts: true,
        isAssessment: false,
      },
      '19422': {
        mode: 'short',
        name: 'Oceans_Short',
        id: 19422,
        helpVideos: [],
        type: 'Fish',
        appName: 'fish',
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/7',
        offerBrowserTts: true,
        isAssessment: false,
      },
      '19424': {
        videoKey: 'oceans_societal_implications',
        displayName: 'Video: Societal Implications',
        name: 'Oceans_Video_Societal_Implications',
        id: 19424,
        levelData: {
          src: 'https://www.youtube-nocookie.com/embed/ng4c1g3COfs/',
          key: 'oceans_societal_implications',
          name: 'Societal Implications',
          download:
            'https://videos.code.org/levelbuilder/03-ai-impactonsociety-sm-mp4.mp4',
          thumbnail: '/c/video_thumbnails/oceans_societal_implications.jpg',
          enableFallback: true,
          autoplay: false,
        },
        helpVideos: [],
        type: 'StandaloneVideo',
        appName: 'standalone_video',
        finishUrl: '/courses/oceans/units/1/lessons/1/levels/8',
        offerBrowserTts: true,
        isAssessment: false,
      },
      '19420': {
        mode: 'long',
        name: 'Oceans_Long',
        id: 19420,
        helpVideos: [],
        type: 'Fish',
        appName: 'fish',
        finishUrl: '/api/hour/finish/oceans',
        offerBrowserTts: true,
        isAssessment: false,
      },
    },
  },
];
