apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshPolicy: CreatedOnce
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        dex.argocd.clientSecret: "{{ `{{ .password }}` }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: argocd-dex-client-secret
