require 'rake/testtask'

desc 'Run tests for dashboard/legacy directory'
task :test do
  Rake::TestTask.new do |t|
    t.warning = false
    t.test_files = FileList["test/**/test_*.rb"]
  end
end

task default: :test
