---
transport:
  name: ssh_tgz
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  data_path: test/shared
  require_chef_omnibus: 12.6.0

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[cdo-nodejs]
  - name: upgrade
    steps:
      - run_list:
        - recipe[nodejs_test::old]
      - run_list:
        - recipe[cdo-nodejs]
