// GENERATED by scripts/write-stock-backgrounds.mjs — do not edit.
//
// The stock backdrops on the shelf, by id. The bytes are NOT here: they are
// fetched by `yarn setup:world` from the URLs in backgrounds.txt and served
// from the background base URL (runtime/worldConfig), which is what the library
// dialog fetches when a learner imports one. See specs/BACKGROUNDS.md §7.

/** Every stock backdrop's id — `cave` is served as `cave.png`. */
export const STOCK_BACKGROUND_IDS: readonly string[] = [
  'cave',
  'city',
  'continuousGrass',
  'court',
  'desert',
  'desertRoad',
  'farmLand',
  'floatingGrass',
  'frontOfHouse',
  'space',
  'grid',
  'kitchen',
  'livingRoom',
  'meadow',
  'parkView',
  'pineTrees',
  'rainbow',
  'scifi',
  'soccerField',
  'stage',
  'santa',
  'subway',
  'sunAndRainbow',
  'sunshineShowers',
  'tennisCourt',
  'treeIsland',
  'underground',
  'underwater',
  'winter',
];
