apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patches:
  - path: deployment.patch.yaml
  - target:
      kind: Deployment
      name: cdo-dashboard
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/1/secretRef/optional
        value: true
labels:
  - pairs:
      app.kubernetes.io/name: cdo
      app.kubernetes.io/instance: cdo
    includeSelectors: true
    includeTemplates: true
