name: Apps-CI

on:
  workflow_call:

defaults:
  run:
    working-directory: ./apps

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            apps
            frontend
            .github
          # todo: I don't believe LFS is needed for unit tests or linting
          # lfs: true

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          cache-dependency-path: "apps/yarn.lock"

      - name: Install apps dependencies
        shell: bash
        run: yarn install

      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            apps
            frontend
            shared/fonts
            .github
            dashboard/app/views
          # todo: I don't believe LFS is needed for unit tests or linting
          # lfs: true

      - name: Setup Frontend
        uses: ./.github/actions/frontend/setup

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          cache-dependency-path: "apps/yarn.lock"

      - name: Install apps dependencies
        shell: bash
        run: yarn install
        working-directory: ./apps

      - name: Build
        run: yarn build
        working-directory: ./apps

      - name: Unit Tests
        run: yarn test
        working-directory: ./apps
