name: test docker file
on:
  workflow_dispatch:
jobs:
  run-tests:  
    runs-on: ubuntu-latest 
    env:        
      CI: true
      RAILS_ENV: test
      RACK_ENV: test
      DISABLE_SPRING: 1
      AWS_ACCESS_KEY_ID: $${{ secrets.CI_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: $${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}    
    steps:        
      - name: Get actions code
        uses: actions/checkout@v3    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
      - name: Check AWS credentials
        run: aws sts get-caller-identity --no-cli-pager        
      - name: say-hello
        uses: ./.github/actions/start-server-job-actions  
#      - name: run docker
#        run: docker build -t local < ./code-dot-org/docker/dockerfiles/Dockerfile
      - name: Setup locals
        run: |
          echo "
          bundler_use_sudo: false
          cloudfront_key_pair_id: $CLOUDFRONT_KEY_PAIR_ID
          cloudfront_private_key: \"$CLOUDFRONT_PRIVATE_KEY\"
          ignore_eyes_mismatches: true
          disable_all_eyes_running: true
          use_my_apps: true
          build_dashboard: true
          build_pegasus: true
          build_apps: true
          build_i18n: true
          localize_apps: true
          dashboard_enable_pegasus: true
          dashboard_workers: 5
          skip_seed_all: true
          optimize_webpack_assets: false
          optimize_rails_assets: false
          google_maps_api_key: boguskey
          dashboard_db_reader: \"mysql://readonly@localhost/dashboard_test\"
          " >> locals.yml
      - name: install docker
        run: |
          brew install docker-compose
          export FIXUID=$(id -u)   
          export FIXGID=$(id -g)
          docker-compose -f ./docker/setup-compose.yml up > output.txt
        continue-on-error: true
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3   
