# Build kubernetes oriented docker images using skaffold (see /skaffold.yaml and 
# k8s/README.md for details).
#
# This is currently an experimental feature, see: k8s/experimental.yaml

name: k8s
on:
  # Trigger on merges into production (i.e. DTP), or on any PR, however note that we filter
  # PRs down to PRs where the source-branch is *k8s* using `if:` blocks below.
  push:
    branches:
      - production
  pull_request:

jobs:
  # Step 1: build platform specific docker images: amd64, arm64, using `skaffold build`
  skaffold-build:
    if: github.event_name != 'pull_request' || contains(github.head_ref, 'k8s')
    name: skaffold build
    uses: ./.github/workflows/k8s-skaffold-build.yml
    # only run on PRs where the source branch is *k8s*:
    secrets: inherit

  # Step 2: stitch the platform specific images into a multi-platform image
  stitch-multiplatform-image:
    name: stitch multi-platform image
    uses: ./.github/workflows/k8s-stitch-multiplatform-image.yml
    needs: skaffold-build
    with:
      docker_tags_json: ${{ toJSON(needs.skaffold-build.outputs) }}
      docker_tag: ${{ needs.skaffold-build.outputs.docker_tag }}
    secrets: inherit

  commit-image-ref-to-argocd:
    name: commit new codeai docker image ref to k8s-gitops repo => trigger argocd
    uses: ./.github/workflows/k8s-commit-image-ref-to-argocd.yml
    needs: stitch-multiplatform-image
    if: github.event_name == 'push'
    with:
      branch_name: ${{ github.ref_name }}
      codeai_docker_image_ref: ${{ needs.stitch-multiplatform-image.outputs.codeai_docker_image_ref }}
    secrets: inherit

# Grant the GITHUB_TOKEN the necessary permissions for checkout and publishing to GitHub Packages
permissions:
  # permission to checkout this repo in the build workflow
  contents: read
  # permission to publish container images to ghcr.io
  packages: write
