# This is an experiment with triggering a GitHub worfklow AFTER Drone CI completes.
name: on-droneci-complete

on:
  workflow_dispatch:
    inputs:
      github_sha:
        description: "equivalent to github.sha in an ordinary workflow"
        required: true
      drone_build_status:
        required: true
        type: choice
        options:
          - success
          - failure

permissions:
  statuses: write

jobs:
  # We use applitools eyes from: drone and frontend-ci.yml. We need to close the eyes batch
  # after these are done. Drone is so slow that we assume Drone will be the last to finish,
  # but we check and throw an error if frontend-ci.yml is still running when drone completes.
  complete-applitools-eyes-batch:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "Triggered by Drone, on commit: ${{ inputs.github_sha }} on branch ${{ github.ref }}"
          echo "This job should succeed"
          true

      - name: Assert other eyes-using workflows are already complete
        uses: actions/github-script@v7
        with:
          script: |
            async function assertWorkflowNotPending(workflow_id) {
              const { data: { workflow_runs } } = await github.rest.actions.listWorkflowRuns({
                workflow_id,
                head_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });

              if (workflow_runs.length === 0) {
                console.log(`Workflow ${workflow_id} was not triggered by this commit, ignoring`);
              } else if (workflow_runs[0].status !== 'completed') {
                core.setFailed(`Error: ${workflow_id} is still pending, but we're closing the applitools batch now that drone is complete. This may cause problems for ${workflow_id}.`);
                process.exit(1);
              }
            }

            await assertWorkflowNotPending('frontend-ci.yml');

      # Close the eyes batch after all distributed eyes tests have completed
      - name: Mark Applitools Eyes batch as complete
        if: always()
        shell: bash
        env:
          APPLITOOLS_BATCH_ID: ${{ inputs.github_sha }}
        run: |
          curl -X POST "https://eyesapi.applitools.com/api/externals/github/servers/github.com/commit/${{ env.APPLITOOLS_BATCH_ID }}/${{ github.run_id }}/complete?apiKey=${{secrets.APPLITOOLS_API_KEY}}"


      # Running this step lets you see in the PR if the complete-applitools-eyes-batch job failed.
      # Otherwise, you have to browse github actions to see the failure. We only do this when
      # it failed. This reduces noise in daily development, but lets us avoid silent failure if some
      # year/condition Drone starts completing before frontend tests.
      - uses: actions/github-script@v7
        if: failure()
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              context: 'Mark Applitools Eyes batch as complete',
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ inputs.github_sha }}',
              state: '${{ job.status == 'success' && 'success' || 'failure' }}'
            })
