name: OpenTofu-Apply

on:
  push:
    branches: [staging]
    paths:
      - "**/*.tf"
      - "**/*.tfvars"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Make sure to keep these in sync with the plan job workspaces matrix
        workspace:
          - k8s/tofu/codeai-k8s/eks-cluster
          - k8s/tofu/codeai-k8s/eks-cluster-addons
          - k8s/tofu/codeai-k8s-dex
    defaults:
      run:
        working-directory: ${{ matrix.workspace }}
    environment: open-tofu-plan
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: opentofu/setup-opentofu@v2
        with:
          tofu_version: 1.6.0
          tofu_wrapper: true # Enables steps.*.outputs.stdout capture

      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Plan
        id: plan
        run: tofu plan -no-color -out=tfplan

      - name: Post Plan to Job Summary
        run: |
          echo "### Workspace: \`${{ matrix.workspace }}\`" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.plan.outputs.stdout }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Set artifact name
        id: artifact_name
        run: echo "name=tfplan-$(basename ${{ matrix.workspace }})" >> $GITHUB_OUTPUT

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.name }}
          path: ${{ matrix.workspace }}/tfplan
          retention-days: 1

  apply:
    needs: plan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - k8s/tofu/codeai-k8s/eks-cluster
          - k8s/tofu/codeai-k8s/eks-cluster-addons
          - k8s/tofu/codeai-k8s-dex
    defaults:
      run:
        working-directory: ${{ matrix.workspace }}
    environment: open-tofu-apply
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: opentofu/setup-opentofu@v2
        with:
          tofu_version: 1.6.0
          tofu_wrapper: true

      - name: Set artifact name
        id: artifact_name
        run: echo "name=tfplan-$(basename ${{ matrix.workspace }})" >> $GITHUB_OUTPUT

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.name }}
          path: ${{ matrix.workspace }}

      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Apply
        run: tofu apply -no-color -input=false -auto-approve tfplan
