name: Studio-CI

on:
  workflow_call:

defaults:
  run:
    shell: bash
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            frontend
            .github
          lfs: true

      - name: Setup Frontend
        uses: ./.github/actions/frontend/setup

      - name: Dryrun Release
        run: pnpm --filter @code-dot-org/studio release:dryrun
