---
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0
platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
suites:
  - name: default
    run_list:
      - recipe[cdo-postfix]
