apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdo-minio
  labels:
    app.kubernetes.io/component: minio
spec:
  serviceName: cdo-minio
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/component: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2025-02-07T23-21-09Z
          args:
            - server
            - /data
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: cdo-local-secrets
                  key: _minio_root_user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cdo-local-secrets
                  key: _minio_root_password
          volumeMounts:
            - name: minio-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
